# Environment Setup

In [4]:
! pip install transformers huggingface torch

Collecting transformers
  Downloading transformers-4.51.3-py3-none-any.whl.metadata (38 kB)
Collecting huggingface
  Downloading huggingface-0.0.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.1.0+cu118)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.9.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.30.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.24.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 5.5 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch) (4.4.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2025.3.2)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch) (2.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch) (1.3.0)
Downloading transformers-4.51.3-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 189.8 MB/s eta 0:00:000:00:01
Downloading huggingface-0.0.1-py3-none-any.whl (2.5 kB)
Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.7/781.7 kB 223.3 MB/s eta 0:00:00
Downloading tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 159.7 MB/s eta 0:00:00
Installing collected packages: huggingface, regex, tokenizers, transformers
Successfully installed huggingface-0.0.1 regex-2024.11.6 tokenizers-0.21.1 transformers-4.51.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1
[notice] To update, run: python -m pip install --upgrade pip

In [1]:
! pip install python-dotenv

Collecting python-dotenv
  Downloading python_dotenv-1.1.0-py3-none-any.whl.metadata (24 kB)
Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1
[notice] To update, run: python -m pip install --upgrade pip

In [2]:
! pip install accelerate

Collecting accelerate
  Downloading accelerate-1.6.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /usr/local/lib/python3.10/dist-packages (from accelerate) (1.24.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (23.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.6)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate) (6.0.1)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (2.1.0+cu118)
Collecting huggingface-hub>=0.21.0 (from accelerate)
  Downloading huggingface_hub-0.30.2-py3-none-any.whl.metadata (13 kB)
Collecting safetensors>=0.4.3 (from accelerate)
  Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (3.9.0)
Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.21.0->accelerate)
  Downloading fsspec-2025.3.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (2.31.0)
Collecting tqdm>=4.42.1 (from huggingface-hub>=0.21.0->accelerate)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (4.4.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (3.1.2)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (2.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2.0.0->accelerate) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2022.12.7)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=2.0.0->accelerate) (1.3.0)
Downloading accelerate-1.6.0-py3-none-any.whl (354 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.7/354.7 kB 18.6 MB/s eta 0:00:00
Downloading huggingface_hub-0.30.2-py3-none-any.whl (481 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 481.4/481.4 kB 80.0 MB/s eta 0:00:00
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 111.5 MB/s eta 0:00:00
Downloading fsspec-2025.3.2-py3-none-any.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.4/194.4 kB 64.0 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 32.7 MB/s eta 0:00:00
Installing collected packages: tqdm, safetensors, fsspec, huggingface-hub, accelerate
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2023.4.0
    Uninstalling fsspec-2023.4.0:
      Successfully uninstalled fsspec-2023.4.0
Successfully installed accelerate-1.6.0 fsspec-2025.3.2 huggingface-hub-0.30.2 safetensors-0.5.3 tqdm-4.67.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1
[notice] To update, run: python -m pip install --upgrade pip

## Import Library

In [5]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig,pipeline
from tqdm import tqdm

# Load Model

In [7]:
! nvidia-smi

Thu May  1 01:01:04 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.05             Driver Version: 550.127.05     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A40                     On  |   00000000:52:00.0 Off |                    0 |
|  0%   29C    P8             24W /  300W |       1MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
# token = "HF_TOKEN_REDACTED"

In [9]:
from huggingface_hub import login
import os

# Get HF token injected from RunPod secret
hf_token = os.getenv('HF_TOKEN')

# Login
login(token=hf_token)

print("Hugging Face login successful via RunPod Secret!")

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

Hugging Face login successful via RunPod Secret!

In [7]:
'''
from huggingface_hub import login
from dotenv import load_dotenv
import os

load_dotenv('/content/secret.env')

hf_token = os.getenv('HF_TOKEN')

if hf_token is None:
    raise ValueError("HF_TOKEN not found!")

login(token=hf_token)

print(" Logged into Hugging Face using .env file!")
'''

'\nfrom huggingface_hub import login\nfrom dotenv import load_dotenv\nimport os\n\nload_dotenv(\'/content/secret.env\')\n\nhf_token = os.getenv(\'HF_TOKEN\')\n\nif hf_token is None:\n    raise ValueError("HF_TOKEN not found!")\n\nlogin(token=hf_token)\n\nprint(" Logged into Hugging Face using .env file!")\n'

In [10]:
# meta-llama/Llama-3.1-8B-Instruct
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.1-8B-Instruct")
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.1-8B-Instruct")

tokenizer_config.json:   0%|          | 0.00/55.4k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/184 [00:00<?, ?B/s]

# Dataset processed

In [11]:
pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 2.1 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 143.7 MB/s eta 0:00:0000:01:01
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 98.6 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 kB 100.4 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2025.2 tzdata-2025.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

## Cloud

### Load

In [12]:
import pandas as pd

In [13]:
#from google.colab import drive
#drive.mount('/content/drive')

In [14]:
cloud = pd.read_excel("../../Dataset/cloud/split_data/cloud_test.xlsx")

In [15]:
cloud.drop(['Unnamed: 0'],axis=1,inplace=True)

In [16]:
cloud.head(2)

,title,body,tags,link,score,creation_date,answer_count,comments,answers,selected_answer,images
0,Some recently changed resources are not yet pu...,\n \nEvery once in a while i ge...,"['java', 'eclipse', 'google-app-engine', 'java...",https://stackoverflow.com/questions/49711724/s...,4,2018-04-07 20:34:12Z,1,"[""@code511788465541441, if you consider Chanse...",[{'body': '\n \nIf that happens...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,FAILED TO INITIALIZE RUN FROM PACKAGE.txt,\n \nOur pipeline indicates suc...,"['azure-web-app-service', 'azure-deployment', ...",https://stackoverflow.com/questions/65255839/f...,7,2020-12-11 17:20:22Z,2,"[""thanks for the hint. i am going to verify th...","[{'body': ""\nI am almost certain that the pack...",\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

### Processing

In [17]:
cloud=cloud[['title','body','selected_answer']]

In [18]:
cloud.head()

,title,body,selected_answer
0,Some recently changed resources are not yet pu...,\n \nEvery once in a while i ge...,"If that happens for whatever reasons, you need..."
1,FAILED TO INITIALIZE RUN FROM PACKAGE.txt,\n \nOur pipeline indicates suc...,\nI am almost certain that the package path is...
2,Deploy to Heroku button with env variables,"\n \nI'd like to add a ""Deploy ...","You may have found this already, but it looks ..."
3,Publish azure functions and use appsettings.json,\n \nI have an Azure Functions ...,The SO post you are referring to contains depr...
4,VSTS Build: Replacing token with build number,\n \nI'm trying to update a web...,"I did something similar using the ""Replace Tok..."

In [19]:
cloud['context'] = "title: " + cloud['title'].astype(str) + "\nbody: " + cloud['body'].astype(str).str.strip()

In [20]:
cloud_processed=pd.DataFrame(
    {
        'context':cloud['context'],
        'gt':cloud['selected_answer']
    }
)

In [21]:
cloud_processed.head(1)

,context,gt
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need..."

In [22]:
cloud_processed[cloud_processed.duplicated()].sum()

context    0
gt         0
dtype: object

## Device

### Load

In [73]:
import pandas as pd

In [74]:
#from google.colab import drive
#drive.mount('/content/drive')

In [75]:
device = pd.read_excel("../../Dataset/device/split_data/device_test.xlsx")

In [76]:
#device.drop(['Unnamed: 0'],axis=1,inplace=True)

In [77]:
device.head(2)

,title,body,tags,link,score,creation_date,answer_count,comments,answers,selected_answer,images
0,What is the purpose of the INPUT chain in the ...,\n \nWhat is the purpose of the...,"['linux', 'iptables', 'linux', 'iptables']",https://serverfault.com/questions/993878/what-...,1,2019-12-01 00:23:16Z,1,"['OK, also please add this to your answer so o...",[{'body': '\nIf some NAT operation needs to be...,\nIf some NAT operation needs to be only done ...,['https://i.sstatic.net/NUh2k.png']
1,"Logstash JDBC input, filter event timestamp di...",\n \nI am trying to change the ...,"['elasticsearch', 'logstash', 'elastic-stack',...",https://stackoverflow.com/questions/33787795/l...,0,2015-11-18 18:38:40Z,3,"['could you suggest how I could fix?', 'Your d...",[{'body': '\nOK I finally figure how to get th...,\nOK I finally figure how to get the @timestam...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

### Processing

In [78]:
device=device[['title','body','selected_answer']]

In [79]:
device.head()

,title,body,selected_answer
0,What is the purpose of the INPUT chain in the ...,\n \nWhat is the purpose of the...,\nIf some NAT operation needs to be only done ...
1,"Logstash JDBC input, filter event timestamp di...",\n \nI am trying to change the ...,\nOK I finally figure how to get the @timestam...
2,"iptables: DROP on an interface does nothing, b...",\n \nSetup:\nUbuntu 20.04 on a ...,\niptables works at the routing layer. It does...
3,How to create inbound rule which only accept L...,\n \nI installed an application...,"\nAs the error message says, 'Defer to user' r..."
4,Are username and password sent in plain text w...,\n \nIf I have the following bi...,\nOther answers here are misleading and incorr...

In [80]:
# Convert title and body as a question 
device['context'] = "title: " + device['title'].astype(str) + "\nbody: " + device['body'].astype(str).str.strip()

In [81]:
device_processed=pd.DataFrame(
    {
        'context':device['context'],
        'gt':device['selected_answer']
    }
)

In [82]:
device_processed.head(1)

,context,gt
0,title: What is the purpose of the INPUT chain ...,\nIf some NAT operation needs to be only done ...

In [83]:
device_processed[device_processed.duplicated()].sum()

context    0
gt         0
dtype: object

# Prompt Setup

## Cloud Question

### Zero Shot

In [23]:
zero_shot = '''
You are an expert cloud assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."

Question:
{}

Answer:

'''

In [24]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['context'])

cloud_processed['zero-shot-question'] = cloud_processed.apply(generate_zero_shot_prompt, axis=1)

In [25]:
print(cloud_processed['zero-shot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Answer:

### CoT

In [26]:
cot = '''
You are an expert cloud assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."
Question:
{}

Lets think step by step:
Answer:
'''

In [27]:
def generate_cot_prompt(row):
    return cot.format(row['context'])

cloud_processed['cot-question'] = cloud_processed.apply(generate_cot_prompt, axis=1)

In [28]:
print(cloud_processed['cot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."
Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Lets think step by step:
Answer:

In [29]:
cloud_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1627 entries, 0 to 1626
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   context             1627 non-null   object
 1   gt                  1627 non-null   object
 2   zero-shot-question  1627 non-null   object
 3   cot-question        1627 non-null   object
dtypes: object(4)
memory usage: 51.0+ KB

## Device Question

### Zero Shot

In [91]:
zero_shot = '''
You are an expert device assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."

Question:
{}

Answer:

'''

In [92]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['context'])

device_processed['zero-shot-question'] =device_processed.apply(generate_zero_shot_prompt, axis=1)

In [93]:
print(device_processed['zero-shot-question'][0])

You are an expert device assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."

Question:
title: What is the purpose of the INPUT chain in the nat table?
body: What is the purpose of the INPUT chain in the nat table ?

The PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".

The nat:INPUT and nat:PREROUTING chains seem redundant.

What would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?

Answer:

### CoT

In [94]:
cot = '''
You are an expert device assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."
Question:
{}

Lets think step by step:
Answer:
'''

In [95]:
def generate_cot_prompt(row):
    return cot.format(row['context'])

device_processed['cot-question'] = device_processed.apply(generate_cot_prompt, axis=1)

In [96]:
print(device_processed['cot-question'][0])

You are an expert device assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."
Question:
title: What is the purpose of the INPUT chain in the nat table?
body: What is the purpose of the INPUT chain in the nat table ?

The PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".

The nat:INPUT and nat:PREROUTING chains seem redundant.

What would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?

Lets think step by step:
Answer:

In [97]:
device_processed.head(2)

,context,gt,zero-shot-question,cot-question
0,title: What is the purpose of the INPUT chain ...,\nIf some NAT operation needs to be only done ...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...
1,"title: Logstash JDBC input, filter event times...",\nOK I finally figure how to get the @timestam...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...

## Extract Input Length

In [98]:
def prompt_length(text):
    if pd.isnull(text):
        return 0
    temp_inputs = tokenizer(text, return_tensors="pt")
    input_length = temp_inputs.input_ids.shape[1]
    return input_length

In [99]:
# Apply to both zero-shot and cot prompts -> Cloud Logs
cloud_processed['zero-shot-question-length'] = cloud_processed['zero-shot-question'].apply(prompt_length)
cloud_processed['cot-question-length'] = cloud_processed['cot-question'].apply(prompt_length)

In [100]:
# Apply to device_processed dataset -> Device logs
device_processed['zero-shot-question-length'] = device_processed['zero-shot-question'].apply(prompt_length)
device_processed['cot-question-length'] = device_processed['cot-question'].apply(prompt_length)

# Generate Response

In [30]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)  # move model to device once
model.eval()

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((4096,), eps=1e-05)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=128256, bias=False)
)

### Zero-Shot Inference

In [31]:
# Zero-Shot generated response
def generate_zero_shot_answer(row):
    try:
        # Set a fixed seed for reproducibility
        torch.manual_seed(42)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(42)

        #tokenize the text
        temp_inputs = tokenizer(row['zero-shot-question'], return_tensors="pt")
        input_length = temp_inputs.input_ids.shape[1] # input length -> optional
        # Apply truncation only if needed
        if input_length > 2048:
            inputs = tokenizer(
                row['zero-shot-question'],
                return_tensors="pt",
                truncation=True,
                max_length=2048,
                padding=False
            ).to(device)
        else:
            inputs = temp_inputs.to(device)

        input_ids = inputs.input_ids
        attention_mask = inputs.attention_mask
        prompt_length = input_ids.shape[1]

        max_new_tokens = 768

          # Generate response
        with torch.no_grad():
            output = model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                max_new_tokens=max_new_tokens,
                eos_token_id=tokenizer.eos_token_id,
                pad_token_id=tokenizer.eos_token_id,
                do_sample=True,
                temperature=0.6,
                top_p=0.9,
                repetition_penalty= 1.2
            )

        generated_tokens = output[0][prompt_length:]  # Remove prompt part
        answer = tokenizer.decode(generated_tokens, skip_special_tokens=True)
        return answer

    except Exception as e:
        print(f"Error while generating for question: {row['zero-shot-question'][:45]}")
        print("Error details:", e)
        return "[Error generating response]"

### CoT Inference

In [32]:
# Chain of Thought generated response
def generate_cot_answer(row):
    try:
        # Set a fixed seed for reproducibility
        torch.manual_seed(42)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(42)

        #tokenize the text
        temp_inputs = tokenizer(row['cot-question'], return_tensors="pt")
        input_length = temp_inputs.input_ids.shape[1] # input length -> optional

        # Apply truncation only if needed
        if input_length > 2048:
                inputs = tokenizer(
                row['cot-question'],
                return_tensors="pt",
                truncation=True,
                max_length=2048,
                padding=False
            ).to(device)
        else:
            inputs = temp_inputs.to(device)

        input_ids = inputs.input_ids
        attention_mask = inputs.attention_mask
        prompt_length = input_ids.shape[1]

        max_new_tokens = 768

        # Generate response
        with torch.no_grad():
            output = model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                max_new_tokens=max_new_tokens,
                eos_token_id=tokenizer.eos_token_id,
                pad_token_id=tokenizer.eos_token_id,
                do_sample=True,
                temperature=0.6,
                top_p=0.9,
                repetition_penalty= 1.2
            )

        generated_tokens = output[0][prompt_length:]  # Remove prompt part
        answer = tokenizer.decode(generated_tokens, skip_special_tokens=True)
        return answer

    except Exception as e:
        print(f"Error while generating for COT question: {row['cot-question'][:45]}")
        print("Error details:", e)
        return "[Error generating COT response]"

## Testing Samples

In [86]:
sample = cloud_processed.sort_values('zero-shot-question-length', ascending=False).head(3).reset_index(drop=True)

In [96]:
sample =cloud_processed[0:3]

In [97]:
sample.head(2)

,context,gt,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,114,120
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,383,389

In [98]:
print(sample['zero-shot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Answer:

In [99]:
zero_results = []

for idx, row in tqdm(sample.iterrows(), total=len(sample)):
    answer = generate_zero_shot_answer(row)
    zero_results.append(answer)
    if idx == 0:
        question_text = row['zero-shot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Question:\n")
        print(short_question)

        print("\n\nSample Response:\n")
        print(answer)
        
sample['zero-shot-generated-answer'] = zero_results

 33%|███▎      | 1/3 [00:27<00:54, 27.18s/it]

Sample Question:


You are an expert cloud assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."

Question:
title: Some recently changed resources are not yet published
body


Sample Response:

This issue is commonly known as the "stale object" problem in Google App Engine (GAE). It occurs when your local development environment still has references to outdated versions of your application's files.

To resolve this issue, try the following steps:

1.  **Delete the `appengine-generated` directory**: This folder contains cached data that might be causing conflicts between your local version and the latest changes on the remote repository or Cloud Storage bucket. You can find this directory at the root level of your project.
2.  **Update the Eclipse project configuration**:
    *   Open the Project Explorer view by navigating to Window > Show View > Other... and selecting General > Projects.
    *   Right-click on your project name and select Properties.
    *   In the properties dialog box, go to Run/Debug Settings, select your run configuration for the GAE app, and press Edit.
    *   On the Arguments tab, ensure that the working directory points directly to your project's root directory (`src/main/webapp`, `war`, etc.). Avoid using any subdirectories within these paths.
3.  **Clean up the Maven dependencies** (if applicable):
    *   Navigate to the command line interface and execute the following commands from the root of your project:
        ```
mvn clean package -DskipTests=true
```
4.  **Check for stale objects manually**:
    *   Inspect your `.settings/org.eclipse.wst.common.component` file inside your project directory to see if there are any entries referencing outdated versions or locations.
5.  **Verify the correct build path settings**:
    *   Ensure that all projects related to your main GAE project have their own individual configurations set correctly. Sometimes, incorrect configurations can cause issues like this one.
6.  **Try rebuilding the index**:
    *   Execute the following maven command:
        ```bash
 mvn compile ear:redeploy
```


By performing these troubleshooting steps, most users should be able to resolve the 'Some recently changed resources are not yet published' error. However, if none of these suggestions work, consider exploring other potential solutions such as resetting the entire workspace, checking for corrupted metadata, or seeking help through official support channels provided by your IDE or platform providers.



Please let me know if more assistance is needed!

100%|██████████| 3/3 [01:00<00:00, 20.27s/it]
/tmp/ipykernel_349/3501383990.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['zero-shot-generated-answer'] = zero_results

In [101]:
print(zero_results[2])

Unfortunately, the `app.json` schema does not provide a built-in mechanism to prompt users to input environment variables during installation or deployment.

However, you can use placeholders like `"replace_me"` (as suggested) and instruct your users to replace those values in your README file. This approach has its limitations since sensitive info might be exposed until replaced.

Another option would be using Heroku's **Config Vars** feature, which allows storing environment variable settings directly within Heroku itself, rather than relying on hardcoded values. You can then reference these config vars in your code instead of hardcoding them.

As for generating secrets programmatically, Heroku offers APIs and tools that allow automating this process, but they're more geared towards programmatic setup rather than interactive prompting during manual installations. So, while you can create secret keys via API calls, integrating this into a seamless 'Deploy to Heroku' flow isn't straightforward without some custom scripting or tooling.

Lastly, another alternative worth considering is leveraging CI/CD pipelines integrated with Heroku. Tools like TravisCI, CircleCI, etc., offer environments where you can store sensitive credentials securely. These environments automatically inject required configuration when deploying your apps to Heroku. While still requiring additional infrastructure setup beyond simple `app.json`, this method ensures secure handling of credentials throughout development cycles.

Keep in mind each solution comes with trade-offs between security, convenience, and complexity. Choose one based on your specific needs!

In [102]:
cot_results = []
for idx, row in tqdm(sample.iterrows(), total=len(sample)):
    answer = generate_cot_answer(row)
    cot_results.append(answer)

    if idx == 0:
        question_text = row['cot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Question (first 100 tokens):\n\n")
        print(short_question)

        print("\n\nSample Response:\n\n")
        print(answer)

# Save the results to the dataframe
sample['cot-generated-answer'] = cot_results

 33%|███▎      | 1/3 [00:37<01:15, 37.77s/it]

Sample Question (first 100 tokens):



You are an expert cloud assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."
Question:
title: Some recently changed resources are not yet published
body


Sample Response:


This issue is likely due to stale metadata on your local machine that's causing App Engine to serve outdated versions of your application.

To resolve this:

1\. Delete the `~/.appengine/default` directory (on Linux/Mac) or `%USERPROFILE%\.appengine\default` (on Windows).

2\. Run `gcloud app deploy --project <your-project-id>` from your terminal/command prompt.

3\. Make sure Eclipse is configured correctly for deployment; check your run configurations and ensure they're pointing at the correct SDK version.

4\. Try redeploying your application through Eclipse after making these changes.

5\. Consider increasing the `max_allowed_old_versions` setting in your `app.yaml`.

Note:\* You can find more details about this behavior [here](https://issuetracker.google.com/issues/36945422).\*\* This solution assumes you have already set up your environment using the Google Cloud SDK.\*\*

Please try these steps and let me know if any further assistance is required!

**Additional Tips**

\- Ensure your workspace folder doesn't contain duplicate `.iml` files which may cause issues during deployment

\- Verify that the 'Java Build Path' properties under Project Properties > Java Build Path match those specified in the pom.xml file (if applicable)

\- In some cases, updating Gradle might also be necessary - consult official documentation for instructions

I hope this helps resolve the problem!

Is there anything else I can help with?  Please provide more context or clarify the specific requirements.   :)


---

## Step 1: Identify the root cause of the issue
The user reports encountering an error where some recently changed resources are not yet published, even after clicking "Yes" to update their GAE server.


## Step 2: Determine possible solutions based on known behaviors
Based on similar reported issues ([issue tracker link](https://issuetracker.google.com/issues/36945422)), we suspect that stale metadata on the local machine could be the culprit behind serving outdated versions of the application.


## Step 3: Suggest deletion of stale metadata
Delete the `~/.appengine/default` directory (Linux/Mac) or `%USERPROFILE%\.appengine\default` (Windows), as recommended by other users who encountered similar problems.


## Step 4: Recommend re-deployment via command line tool
Run `gcloud app deploy --project <your-project-id>` from the terminal/command prompt to force a new build and deployment.


## Step 5: Check configuration settings in Eclipse
Verify that Eclipse is properly configured for deployment by checking the run configurations and ensuring they point to the correct SDK version.


## Step 6: Offer additional troubleshooting tips
Consider adjusting the `max_allowed_old_versions` setting in `app.yaml`, removing potential duplicates of `.iml` files within the workspace, verifying consistency between the Java Build Path properties and pom.xml (for Maven projects), and potentially updating Gradle (if used).


The final answer is: There isn't one single definitive answer here since the resolution depends heavily upon individual setups & circumstances. However, going through each suggested action should hopefully alleviate whatever underlying issue was preventing recent resource updates from being reflected accurately across all areas involved.

100%|██████████| 3/3 [01:21<00:00, 27.17s/it]
/tmp/ipykernel_349/3188392621.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['cot-generated-answer'] = cot_results

In [105]:
print(cot_results[2])

To deploy your application to Heroku using a `deploy` script in your `app.json`, you can't directly ask users to input environment variables. However, here are two possible solutions:

1. **Use placeholders**: As you mentioned, you can use placeholder values (e.g., `"replace_me"` or `{}`) in your `env` section of `app.json`. Then, instruct users to replace those values manually when prompted during installation. This approach works well for simple applications where users understand the process.

2. **Utilize Heroku's secrets management feature**: You're correct about this option! In your `app.json`, under the `scripts` section, define a `pre-install` hook. Within this hook, create a secret variable using the command `heroku config:set SECRET_NAME=your_secret_value --remote <repo-name>`. This sets an encrypted secret value named `<SECRET_NAME>` in your repository settings.

Here’s how you might implement both approaches together:

```json
{
  //... rest of your configuration...
  "scripts": {
    "pre-install": [
      "npm run pre-deploy",
      "echo 'Please fill out your credentials below' && \
       read -p 'Your API key:'YOUR_API_KEY && \
       heroku config:set MY_SECRET=${YOUR_API_KEY} --remote <repo-name>"
    ]
  },
  "env": {
    "MY_SECRET": "{}}"
  }
}
```

This example shows creating a new secret (`MY_SECRET`) after prompting the user for its value. The `--remote <repo-name>` flag ensures the change applies specifically to the current Git branch being deployed.

Note that while these methods help manage sensitive data securely within your project, they still rely on users entering information correctly at runtime.

By integrating one or both strategies above into your deployment workflow, you'll be able to safely store and utilize necessary environmental parameters without exposing them publicly through source control.

Let me know if any additional details are needed or clarification required!
The final answer is: No answer.  There is no direct method to prompt users via `app.json` alone; however, utilizing scripts and Heroku's built-in features provides secure alternatives.   We have outlined steps for handling sensitive information effectively during deployments.

In [87]:
sample.to_csv("sample_llm_text_llama_3_1_8b_instruct.csv")

## Cloud Testset

In [33]:
cloud_testset=cloud_processed

In [34]:
cloud_testset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1627 entries, 0 to 1626
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   context             1627 non-null   object
 1   gt                  1627 non-null   object
 2   zero-shot-question  1627 non-null   object
 3   cot-question        1627 non-null   object
dtypes: object(4)
memory usage: 51.0+ KB

In [35]:
cloud_testset.head(2)

,context,gt,zero-shot-question,cot-question
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...

### zero shot response

In [114]:
zero_cloud_results = [] # Store zero-shot generated answers

for idx, row in tqdm(cloud_testset.iterrows(), total=len(cloud_testset)):
    # Call inference function to generate answer 
    answer = generate_zero_shot_answer(row) 
    zero_cloud_results.append(answer)

    if idx == 0:
        question_text = row['zero-shot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Question:\n")
        print(short_question)

        print("\n\nSample Response:\n")
        print(answer)
        
# Save the results to the dataframe
cloud_testset['zero-shot-generated-answer'] = zero_cloud_results

  0%|          | 1/1627 [00:27<12:17:21, 27.21s/it]

Sample Question:


You are an expert cloud assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."

Question:
title: Some recently changed resources are not yet published
body


Sample Response:

This issue is commonly known as the "stale object" problem in Google App Engine (GAE). It occurs when your local development environment still has references to outdated versions of your application's files.

To resolve this issue, try the following steps:

1.  **Delete the `appengine-generated` directory**: This folder contains cached data that might be causing conflicts between your local version and the latest changes on the remote repository or Cloud Storage bucket. You can find this directory at the root level of your project.
2.  **Update the Eclipse project configuration**:
    *   Open the Project Explorer view by navigating to Window > Show View > Other... and selecting General > Projects.
    *   Right-click on your project name and select Properties.
    *   In the properties dialog box, go to Run/Debug Settings, select your run configuration for the GAE app, and press Edit.
    *   On the Arguments tab, ensure that the working directory points directly to your project's root directory (`src/main/webapp`, `war`, etc.). Avoid using any subdirectories within these paths.
3.  **Clean up the Maven dependencies** (if applicable):
    *   Navigate to the command line interface and execute the following commands from the root of your project:
        ```
mvn clean package -DskipTests=true
```
4.  **Check for stale objects manually**:
    *   Inspect your `.settings/org.eclipse.wst.common.component` file inside your project directory to see if there are any entries referencing outdated versions or locations.
5.  **Verify the correct build path settings**:
    *   Ensure that all projects related to your main GAE project have their own individual configurations set correctly. Sometimes, incorrect configurations can cause issues like this one.
6.  **Try rebuilding the index**:
    *   Execute the following maven command:
        ```bash
 mvn compile ear:redeploy
```


By performing these troubleshooting steps, most users should be able to resolve the 'Some recently changed resources are not yet published' error. However, if none of these suggestions work, consider exploring other potential solutions such as resetting the entire workspace, checking for corrupted metadata, or seeking help through official support channels provided by your IDE or platform providers.



Please let me know if more assistance is needed!

100%|██████████| 1627/1627 [10:37:49<00:00, 23.52s/it]

In [115]:
cloud_testset.head(2)

,context,gt,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero-shot-generated-answer
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,114,120,"This issue is commonly known as the ""stale obj..."
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,383,389,"Based on your description, there seems to be a..."

In [116]:
cloud_testset.to_excel("../responses/cloud/llm_text_response_cloud_llama_3_1_8b_instruct_zero_shot.xlsx", index=False)

### Cot Response

In [36]:
cot_cloud_results = [] # Store CoT generated answers
for idx, row in tqdm(cloud_testset.iterrows(), total=len(cloud_testset)):
    # Call inference function to generate answer 
    answer = generate_cot_answer(row)
    cot_cloud_results.append(answer)

    if idx == 0:
        question_text = row['cot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Question (first 100 tokens):\n\n")
        print(short_question)

        print("\n\nSample Response:\n\n")
        print(answer)

# Save the results to the dataframe
cloud_testset['cot-generated-answer'] = cot_cloud_results

  0%|          | 1/1627 [00:38<17:15:18, 38.20s/it]

Sample Question (first 100 tokens):



You are an expert cloud assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."
Question:
title: Some recently changed resources are not yet published
body


Sample Response:


This issue is likely due to stale metadata on your local machine that's causing App Engine to serve outdated versions of your application.

To resolve this:

1\. Delete the `~/.appengine/default` directory (on Linux/Mac) or `%USERPROFILE%\.appengine\default` (on Windows).

2\. Run `gcloud app deploy --project <your-project-id>` from your terminal/command prompt.

3\. Make sure Eclipse is configured correctly for deployment; check your run configurations and ensure they're pointing at the correct SDK version.

4\. Try redeploying your application through Eclipse after making these changes.

5\. Consider increasing the `max_allowed_old_versions` setting in your `app.yaml`.

Note:\* You can find more details about this behavior [here](https://issuetracker.google.com/issues/36945422).\*\* This solution assumes you have already set up your environment using the Google Cloud SDK.\*\*

Please try these steps and let me know if any further assistance is required!

**Additional Tips**

\- Ensure your workspace folder doesn't contain duplicate `.iml` files which may cause issues during deployment

\- Verify that the 'Java Build Path' properties under Project Properties > Java Build Path match those specified in the pom.xml file (if applicable)

\- In some cases, updating Gradle might also be necessary - consult official documentation for instructions

I hope this helps resolve the problem!

Is there anything else I can help with?  Please provide more context or clarify the specific requirements.   :)


---

## Step 1: Identify the root cause of the issue
The user reports encountering an error where some recently changed resources are not yet published, even after clicking "Yes" to update their GAE server.


## Step 2: Determine possible solutions based on known behaviors
Based on similar reported issues ([issue tracker link](https://issuetracker.google.com/issues/36945422)), we suspect that stale metadata on the local machine could be the culprit behind serving outdated versions of the application.


## Step 3: Suggest deletion of stale metadata
Delete the `~/.appengine/default` directory (Linux/Mac) or `%USERPROFILE%\.appengine\default` (Windows), as recommended by other users who encountered similar problems.


## Step 4: Recommend re-deployment via command line tool
Run `gcloud app deploy --project <your-project-id>` from the terminal/command prompt to force a new build and deployment.


## Step 5: Check configuration settings in Eclipse
Verify that Eclipse is properly configured for deployment by checking the run configurations and ensuring they point to the correct SDK version.


## Step 6: Offer additional troubleshooting tips
Consider adjusting the `max_allowed_old_versions` setting in `app.yaml`, removing potential duplicates of `.iml` files within the workspace, verifying consistency between the Java Build Path properties and pom.xml (for Maven projects), and potentially updating Gradle (if used).


The final answer is: There isn't one single definitive answer here since the resolution depends heavily upon individual setups & circumstances. However, going through each suggested action should hopefully alleviate whatever underlying issue was preventing recent resource updates from being reflected accurately across all areas involved.

100%|██████████| 1627/1627 [13:23:53<00:00, 29.65s/it]

In [37]:
cloud_testset.head(2)

,context,gt,zero-shot-question,cot-question,cot-generated-answer
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,This issue is likely due to stale metadata on ...
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,There could be several reasons for this issue....

In [38]:
cloud_testset.to_excel("../responses/cloud/llm_text_response_cloud_llama_3_1_8b_instruct_cot.xlsx", index=False)

## Device Testset

In [111]:
device_testset=device_processed

In [112]:
device_testset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1021 entries, 0 to 1020
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   context                    1021 non-null   object
 1   gt                         1021 non-null   object
 2   zero-shot-question         1021 non-null   object
 3   cot-question               1021 non-null   object
 4   zero-shot-question-length  1021 non-null   int64
 5   cot-question-length        1021 non-null   int64
dtypes: int64(2), object(4)
memory usage: 48.0+ KB

In [113]:
device_testset.shape

(1021, 6)

### Zero shot Response

In [114]:
zero_device_results = [] # Store zero shot generated answers

for idx, row in tqdm(device_testset.iterrows(), total=len(device_testset)):
    # Call inference function to generate answer 
    answer = generate_zero_shot_answer(row)
    zero_device_results.append(answer)

    if idx == 0:
        question_text = row['zero-shot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Question:\n")
        print(short_question)

        print("\n\nSample Response:\n")
        print(answer)
        
# Save the results to the dataframe
device_testset['zero-shot-generated-answer'] = zero_device_results

  0%|          | 1/1021 [00:32<9:10:06, 32.36s/it]

Sample Question:


You are an expert device assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."

Question:
title: What is the purpose of the INPUT chain in the


Sample Response:

There isn't enough specific context or details about how your system uses NAT rules for me to provide a precise explanation on this topic without potentially causing confusion. However, I can give some general guidance based on common practices.


In Linux's Netfilter framework, which includes iptables, there are several tables and chains used for network address translation (NAT). The main goal here seems to be to understand why one might choose to specifically target the `nat:INPUT` chain when it appears similar functionality could also be achieved through other means like the `nat:PREROUTING` chain.

1. **Understanding Chain Differences**: Each chain serves different purposes within the packet processing pipeline. Understanding these differences helps determine where to place specific rules:


   - **POSTROUTING** handles outgoing traffic after routing decisions have been made; useful for SNAT (Source NAT).

   - **OUTPUT** deals with outgoing local traffic before any routing decision has been taken into account; good for source port randomization among many things.

   - **PREROUTING**, as mentioned, does DNAT (Destination NAT), essentially changing the destination IP of incoming packets.

   - **INPUT** refers to handling incoming traffic once it’s decided by the router to go to this host but right before actually reaching its final process.



2. **Specific Use Cases for INPUT vs PREROUTING Chains**: While both chains can perform DNAT, their application scenarios differ slightly due to timing considerations during packet traversal:



    * If you want to ensure certain services or ports get translated even if they're not explicitly listed under default actions in higher precedence rules, using `nat:INPUT` ensures consistency across all incoming connections regardless of protocol or service type being accessed directly from outside.

    * Another scenario involves complex setups requiring multiple translations depending on various conditions met at input stage rather than just prerouting level, suggesting more fine-grained control over how inputs are handled.

3.  **Avoiding Conflicts and Simplifying Rulesets**: Sometimes splitting tasks between two seemingly overlapping features makes sense because each rule set can focus narrowly without conflicting priorities inherent in broader rule sets.

4. **Flexibility and Future-Proofing**: Even though functionalities overlap somewhat, having options allows for better adaptability in case future requirements demand changes that wouldn’t necessitate wholesale rewrites otherwise achievable solely via single feature implementation strategies.



Given the complexity involved, providing a definitive reason for choosing `nat:INPUT` over `nat:PREROUTING` requires detailed knowledge of your specific setup, including the operating environment, existing configuration, and security policies aimed to achieve through such configurations.



To clarify further, consulting official documentation or experienced professionals familiar with your particular infrastructure will offer insights tailored precisely to those specifics beyond generic descriptions provided above.

100%|██████████| 1021/1021 [6:45:14<00:00, 23.81s/it]

In [115]:
device_testset.head(2)

,context,gt,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero-shot-generated-answer
0,title: What is the purpose of the INPUT chain ...,\nIf some NAT operation needs to be only done ...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,144,150,There isn't enough specific context or details...
1,"title: Logstash JDBC input, filter event times...",\nOK I finally figure how to get the @timestam...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,550,556,You're experiencing issues with Logstash's `da...

In [116]:
device_testset.to_excel("../responses/device/llm_text_response_device_llama_3_1_8b_instruct_zero_shot.xlsx", index=False)

### CoT Response

In [119]:
cot_device_results = [] # Store CoT generated answers
for idx, row in tqdm(device_testset.iterrows(), total=len(device_testset)):
    # Call inference function to generate answer 
    answer = generate_cot_answer(row)
    cot_device_results.append(answer)

    if idx == 0:
        question_text = row['cot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Question:\n")
        print(short_question)

        print("\n\nSample Response:\n")
        print(answer)

# Save the results to the dataframe
device_testset['cot-generated-answer'] = cot_device_results

  0%|          | 1/1021 [00:19<5:24:59, 19.12s/it]

Sample Question:


You are an expert device assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."
Question:
title: What is the purpose of the INPUT chain in the


Sample Response:

There's no definitive rule for using one over another; however, if your network has both source NAT and destination NAT enabled on different interfaces, then it might make sense to have two separate chains - one for each type of operation.

For example:

*   If you're performing DNAT on interface eth0 but SNAT on interface eth1, having two separate chains allows for more fine-grained control over which operations occur when packets arrive from or leave via those respective interfaces.
*   In this scenario, packets arriving at `eth0` will undergo DNAT as they pass through the prerouting chain, while SNAT occurs after packet inspection within the routing decision process before being sent out via `eth1`. The input chain can then perform additional actions based solely upon where these modified packets originated from (`eth1`). This separation enables better security controls since now we only allow traffic coming into our system directly associated with specific outgoing connections rather than indiscriminately applying rules across all types of ingress traffic.



In summary, without any clear-cut guidelines regarding whether one should utilize either or both depending strictly upon functional requirements beyond simple port-forwarding scenarios described earlier, employing multiple chains appears beneficial under complex configurations involving mixed mode translations – particularly allowing greater flexibility during troubleshooting phases due increased visibility into distinct operational contexts provided per-rule basis throughout entire firewall policy hierarchy.


Note : While there isn't anything inherently wrong about placing them together under single default setup usually seen today, utilizing dual-chain approach provides certain advantages especially pertinent situations requiring granular level management capability above standard implementation norms typically observed elsewhere making argument fairly strong albeit lacking explicit mandate supporting usage pattern itself so far discussed here.

100%|██████████| 1021/1021 [8:07:04<00:00, 28.62s/it]

In [120]:
device_testset.head(2)

,context,gt,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero-shot-generated-answer,cot-generated-answer
0,title: What is the purpose of the INPUT chain ...,\nIf some NAT operation needs to be only done ...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,144,150,There isn't enough specific context or details...,There's no definitive rule for using one over ...
1,"title: Logstash JDBC input, filter event times...",\nOK I finally figure how to get the @timestam...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,550,556,You're experiencing issues with Logstash's `da...,The issue lies in how Logstash interprets the ...

In [121]:
device_testset.to_excel("../responses/device/llm_text_response_device_llama_3_1_8b_instruct_cot.xlsx", index=False)