# Environment

In [1]:
! pip install pandas

Looking in indexes: https://pypi.org/simple, https://pypi.org/simple
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.1)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

In [9]:
!pip install --upgrade transformers accelerate

Looking in indexes: https://pypi.org/simple, https://pypi.org/simple
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.43.4)
Collecting transformers
  Downloading transformers-4.52.4-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.10/dist-packages (0.32.0)
Collecting accelerate
  Downloading accelerate-1.8.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.14.0)
Collecting huggingface-hub<1.0,>=0.30.0 (from transformers)
  Downloading huggingface_hub-0.33.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.24.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.4.28)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.4)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.4)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.8)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (2.4.0a0+07cecf4168.nv24.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2024.3.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.11.0)
Collecting hf-xet<2.0.0,>=1.1.2 (from huggingface-hub<1.0,>=0.30.0->transformers)
  Downloading hf_xet-1.1.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (879 bytes)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (3.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2024.2.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2.0.0->accelerate) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=2.0.0->accelerate) (1.3.0)
Downloading transformers-4.52.4-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 79.2 kB/s eta 0:00:0000:0400:07
Downloading accelerate-1.8.1-py3-none-any.whl (365 kB)
Downloading huggingface_hub-0.33.0-py3-none-any.whl (514 kB)
Downloading tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 77.6 kB/s eta 0:00:00a 0:00:03
Downloading hf_xet-1.1.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 2.4/3.1 MB 102.7 kB/s eta 0:00:08^C
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 2.4/3.1 MB 102.7 kB/s eta 0:00:08

## Import Library

In [1]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm import tqdm
import pandas as pd
import json

/usr/local/lib/python3.10/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Load Model

In [2]:
! nvidia-smi

Mon Jun 23 04:32:27 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          Off |   00000000:EF:00.0 Off |                    0 |
| N/A   28C    P0             67W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [3]:
from huggingface_hub import login
import os

token = "HF_TOKEN_REDACTED"
os.environ['HF_TOKEN'] = token

login(token=token)
print("Logged in to Hugging Face!")

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /root/.cache/huggingface/token
Login successful
Logged in to Hugging Face!

### Deepseek R1-dsitill

In [4]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("deepseek-ai/DeepSeek-R1-Distill-Qwen-7B")
model = AutoModelForCausalLM.from_pretrained("deepseek-ai/DeepSeek-R1-Distill-Qwen-7B")

Downloading shards: 100%|██████████| 2/2 [05:10<00:00, 155.23s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:06<00:00,  3.33s/it]

# Load Datasets

In [5]:
import pandas as pd
cloud=pd.read_excel("../../../data/splits/cloud/cloud_test.xlsx")
device=pd.read_excel("../../../data/splits/device/device_test.xlsx")

## Ocr Load

In [6]:
# ocr json

import json

with open("../../../data/processed/ocr/cloud/ocr_extracted_cloud_test.jsonl", "r", encoding="utf-8") as file:
    cloud_test_ocr = [json.loads(line) for line in file]

with open("../../../data/processed/ocr/device/ocr_extracted_device_test.jsonl", "r", encoding="utf-8") as file:
    device_test_ocr = [json.loads(line) for line in file]

In [7]:
from typing import List, Dict, Any

def ocr_extract(data) -> List[str]:
    results: List[str] = []

    for entry in data:
        lines=[]

        for img_i, img in enumerate(entry.get("images", [])):
            lines.append(f"img{img_i}:")

            for resp in img.get("response", []):
                if isinstance(resp, dict):
                    # --- non-table text ---
                    ntt = resp.get("non_table_text")
                    if ntt:
                        lines.append("Non-table text:")
                        lines.extend(ntt if isinstance(ntt, list) else [str(ntt)])

                    # --- tables ---
                    tables = resp.get("table")
                    if tables:
                        lines.append("Tables:")
                        for t_i, tbl in enumerate(tables if isinstance(tables, list) else [tables]):
                            lines.append(f"Table {t_i}:")
                            lines.append(tbl.get("content", "") if isinstance(tbl, dict) else str(tbl))
                    continue

                # Unknown or malformed type
                lines.append(f"[WARN] Unhandled response type: {type(resp).__name__}")
                lines.append(str(resp))

        formatted = "\n".join(lines).strip()
        if formatted:
            results.append(formatted)

    return results

In [8]:
# format ocr response for prompt

cloud_test_ocr_response_format = ocr_extract(cloud_test_ocr)   
device_test_ocr_response_format = ocr_extract(device_test_ocr)

In [9]:
len(cloud_test_ocr_response_format),len(device_test_ocr_response_format)

(1568, 947)

In [14]:
cloud['images'][1423]

"['https://i.sstatic.net/AKSXF.png']"

In [15]:
cloud_test_ocr_response_format[1423]

'img0:\nTables:\nTable 0:\n+-----------------------------------+------------+-----------+-----------+\n| EC2 Instance Type                 | Software   | EC2       | Total     |\n+-----------------------------------+------------+-----------+-----------+\n| Standard Large (m1.large)         | $0.00/hr   | $0.265/hr | $0.265/hr |\n+-----------------------------------+------------+-----------+-----------+\n| Standard XL (m1.xlarge)           | $0.00/hr   | $0.53/hr  | $0.53/hr  |\n+-----------------------------------+------------+-----------+-----------+\n| High-Memory 2XL (m2.2xlarge)      | $0.00/hr   | $0.845/hr | $0.845/hr |\n+-----------------------------------+------------+-----------+-----------+\n| High-Memory 4XL (m2.4xlarge)      | $0.00/hr   | $1.69/hr  | $1.69/hr  |\n+-----------------------------------+------------+-----------+-----------+\n| M3 Extra Large (m3.xlarge)        | $0.00/hr   | $0.475/hr | $0.475/hr |\n+-----------------------------------+------------+-----------+-----------+\n| M3 Double Extra Large (m3.2xlarge | ) $0.00/hr | $0.95/hr  | $0.95/hr  |\n+-----------------------------------+------------+-----------+-----------+\nNon-table text:\n Pricing Details\n For region US East (Virginia)\n Hourly Fees\n Total hourly fees will vary by instance type and EC2 region.'

## Cloud

In [16]:
cloud.head(2)

,Unnamed: 0.1,Unnamed: 0,title,body,tags,link,score,creation_date,answer_count,comments,answers,selected_answer,images
0,0,33283,Some recently changed resources are not yet pu...,\r\n \r\nEvery once in a while ...,"['java', 'eclipse', 'google-app-engine', 'java...",https://stackoverflow.com/questions/49711724/s...,4,2018-04-07 20:34:12Z,1,"[""@code511788465541441, if you consider Chanse...",[{'body': '\n \nIf that happens...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,1,34179,FAILED TO INITIALIZE RUN FROM PACKAGE.txt,\r\n \r\nOur pipeline indicates...,"['azure-web-app-service', 'azure-deployment', ...",https://stackoverflow.com/questions/65255839/f...,7,2020-12-11 17:20:22Z,2,"[""thanks for the hint. i am going to verify th...","[{'body': ""\nI am almost certain that the pack...",\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

## Processed

In [17]:
cloud=cloud[['title','body','selected_answer','images']]

In [18]:
cloud.head(2)

,title,body,selected_answer,images
0,Some recently changed resources are not yet pu...,\r\n \r\nEvery once in a while ...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,FAILED TO INITIALIZE RUN FROM PACKAGE.txt,\r\n \r\nOur pipeline indicates...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

In [19]:
cloud['context'] = "title: " + cloud['title'].astype(str) + "\nbody: " + cloud['body'].astype(str).str.strip()

In [20]:
cloud_processed=pd.DataFrame(
    {
        'context':cloud['context'],
        'gt':cloud['selected_answer'],
        'img':cloud['images']
    }
)

In [21]:
cloud_processed['ocr']=cloud_test_ocr_response_format

In [22]:
cloud_processed.head(2)

,context,gt,img,ocr
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],img0:\nNon-table text:\n Stale resources dete...
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",img0:\nTables:\nTable 0:\n+----+--------------...

## Device

In [23]:
device.head(2)

,Unnamed: 0,title,body,tags,link,score,creation_date,answer_count,comments,answers,selected_answer,images
0,0,What is the purpose of the INPUT chain in the ...,\r\n \r\nWhat is the purpose of...,"['linux', 'iptables', 'linux', 'iptables']",https://serverfault.com/questions/993878/what-...,1,2019-12-01 00:23:16Z,1,"['OK, also please add this to your answer so o...",[{'body': '\nIf some NAT operation needs to be...,\r\nIf some NAT operation needs to be only don...,['https://i.sstatic.net/NUh2k.png']
1,1,"Logstash JDBC input, filter event timestamp di...",\r\n \r\nI am trying to change ...,"['elasticsearch', 'logstash', 'elastic-stack',...",https://stackoverflow.com/questions/33787795/l...,0,2015-11-18 18:38:40Z,3,"['could you suggest how I could fix?', 'Your d...",[{'body': '\nOK I finally figure how to get th...,\r\nOK I finally figure how to get the @timest...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

## Processed

In [24]:
device=device[['title','body','selected_answer','images']]

In [25]:
device.head(2)

,title,body,selected_answer,images
0,What is the purpose of the INPUT chain in the ...,\r\n \r\nWhat is the purpose of...,\r\nIf some NAT operation needs to be only don...,['https://i.sstatic.net/NUh2k.png']
1,"Logstash JDBC input, filter event timestamp di...",\r\n \r\nI am trying to change ...,\r\nOK I finally figure how to get the @timest...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

In [26]:
device['context'] = "title: " + device['title'].astype(str) + "\nbody: " + device['body'].astype(str).str.strip()

In [27]:
device_processed=pd.DataFrame(
    {
        'context':device['context'],
        'gt':device['selected_answer'],
        'img':device['images']
    }
)

In [28]:
device_processed['ocr']=device_test_ocr_response_format

In [29]:
device_processed.head(2)

,context,gt,img,ocr
0,title: What is the purpose of the INPUT chain ...,\r\nIf some NAT operation needs to be only don...,['https://i.sstatic.net/NUh2k.png'],img0:\nNon-table text:\n CT\n ...
1,"title: Logstash JDBC input, filter event times...",\r\nOK I finally figure how to get the @timest...,"['https://i.sstatic.net/3nAZ9.png', 'https://i...",img0:\nTables:\nTable 0:\n+-------------------...

# Prompt

## Cloud

### Zero Shot

In [30]:
zero_shot = '''
You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
{}

Question:
{}

Answer:

'''

In [31]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['ocr'],row['context'])

cloud_processed['zero-shot-question'] = cloud_processed.apply(generate_zero_shot_prompt, axis=1)

In [32]:
print(cloud_processed['zero-shot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
  Stale resources detected
                                                 ×
                                                 x
     Some recently changed resources are not yet published. Continue with launch?
 ?
                                             No
                                   Yes

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Answer:

### CoT

In [33]:
cot = '''
You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
{}

Question:
{}

Lets think step by step:
Answer:
'''

In [34]:
def generate_cot_prompt(row):
    return cot.format(row['ocr'],row['context'])

cloud_processed['cot-question'] = cloud_processed.apply(generate_cot_prompt, axis=1)

In [35]:
print(cloud_processed['cot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
  Stale resources detected
                                                 ×
                                                 x
     Some recently changed resources are not yet published. Continue with launch?
 ?
                                             No
                                   Yes

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Lets think step by step:
Answer:

In [36]:
cloud_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1568 entries, 0 to 1567
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   context             1568 non-null   object
 1   gt                  1568 non-null   object
 2   img                 1568 non-null   object
 3   ocr                 1568 non-null   object
 4   zero-shot-question  1568 non-null   object
 5   cot-question        1568 non-null   object
dtypes: object(6)
memory usage: 73.6+ KB

## Device

### Zero Shot

In [37]:
zero_shot = '''
You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
{}

Question:
{}

Answer:

'''

In [38]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['ocr'],row['context'])

device_processed['zero-shot-question'] =device_processed.apply(generate_zero_shot_prompt, axis=1)

In [39]:
print(device_processed['zero-shot-question'][0])

You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
       CT
                                                                                              iptables
                                                                                                                                                                              Transmit Packet to
Data Link Layer
outbound interface
              Tracked by ConnTrack
                                               Receive Packet from
Data Link Layer
inbound interface
                                                                                              raw table
PREROUTING chain
                                                                              Defrag
                                                                                                                                      Routing
                                                                                                         CT
                                                                                              mangle table
PREROUTING chain
                                                                                                                                                                     CT
              Host Inbound Firewall
                                                                                                                                                                                                       Translate w
ConnTrack's
History
                                                                                                                                                                                 SNAT
                                                                                                                                                        nat table
POSTROUTING chain
                                                                                            Is
this packet
a part of an existing
connection
                                                                                                                      Yes
                                                                                       No
                               mangle table
INPUT chain
                                                                                                       ?
                                                                                                                                                                             Is
this packet
a part of an existing
connection
                                                                                                                                          mangle table
FORWARD chain
                               filter table
INPUT chain
V
security table
INPUT chain
                                                                                                                    Translate w
ConnTrack's
History
                                                                            nat table
PREROUTING chain
                                                                                                                                                                      No
                                                                                                                                                                                                        Yes
                                                                                                                                          filter table
FORWARD chain
V
security table
FORWARD chain
                                                                                                                                                                                        ?
                               nat table
INPUT chain
                                                                                                                                                                             mangle table
POSTROUTING chain
                                                                                                  Is this host
the final
destination?
                                                                                       Yes
                                                                                                                      No
                                      CT
                                                                                                                   Drop
Packet
                                                                                                                                                                   Yes
                                                                                                                                 No
                                                                                                                                       Is this packet routable?
                            Network Socket
(Host Application)
                                                                              Host Outbound Firewall
                                                                                                                                                                               security table
OUTPUT chain
                                                                                 mangle table
OUTPUT chain
                                                                                                                                                filter table
OUTPUT chain
                                                                                                                nat table
OUTPUT chain
                                                 raw table
OUTPUT chain
   Packet from
Network Socket
                                                                      CT
                             Defrag

Question:
title: What is the purpose of the INPUT chain in the nat table?
body: What is the purpose of the INPUT chain in the nat table ?

The PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".

The nat:INPUT and nat:PREROUTING chains seem redundant.

What would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?

Answer:

### CoT

In [40]:
cot = '''
You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
{}

Question:
{}

Lets think step by step:
Answer:
'''

In [41]:
def generate_cot_prompt(row):
    return cot.format(row['ocr'],row['context'])

device_processed['cot-question'] = device_processed.apply(generate_cot_prompt, axis=1)

In [42]:
print(device_processed['cot-question'][0])

You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
       CT
                                                                                              iptables
                                                                                                                                                                              Transmit Packet to
Data Link Layer
outbound interface
              Tracked by ConnTrack
                                               Receive Packet from
Data Link Layer
inbound interface
                                                                                              raw table
PREROUTING chain
                                                                              Defrag
                                                                                                                                      Routing
                                                                                                         CT
                                                                                              mangle table
PREROUTING chain
                                                                                                                                                                     CT
              Host Inbound Firewall
                                                                                                                                                                                                       Translate w
ConnTrack's
History
                                                                                                                                                                                 SNAT
                                                                                                                                                        nat table
POSTROUTING chain
                                                                                            Is
this packet
a part of an existing
connection
                                                                                                                      Yes
                                                                                       No
                               mangle table
INPUT chain
                                                                                                       ?
                                                                                                                                                                             Is
this packet
a part of an existing
connection
                                                                                                                                          mangle table
FORWARD chain
                               filter table
INPUT chain
V
security table
INPUT chain
                                                                                                                    Translate w
ConnTrack's
History
                                                                            nat table
PREROUTING chain
                                                                                                                                                                      No
                                                                                                                                                                                                        Yes
                                                                                                                                          filter table
FORWARD chain
V
security table
FORWARD chain
                                                                                                                                                                                        ?
                               nat table
INPUT chain
                                                                                                                                                                             mangle table
POSTROUTING chain
                                                                                                  Is this host
the final
destination?
                                                                                       Yes
                                                                                                                      No
                                      CT
                                                                                                                   Drop
Packet
                                                                                                                                                                   Yes
                                                                                                                                 No
                                                                                                                                       Is this packet routable?
                            Network Socket
(Host Application)
                                                                              Host Outbound Firewall
                                                                                                                                                                               security table
OUTPUT chain
                                                                                 mangle table
OUTPUT chain
                                                                                                                                                filter table
OUTPUT chain
                                                                                                                nat table
OUTPUT chain
                                                 raw table
OUTPUT chain
   Packet from
Network Socket
                                                                      CT
                             Defrag

Question:
title: What is the purpose of the INPUT chain in the nat table?
body: What is the purpose of the INPUT chain in the nat table ?

The PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".

The nat:INPUT and nat:PREROUTING chains seem redundant.

What would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?

Lets think step by step:
Answer:

In [43]:
device_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 947 entries, 0 to 946
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   context             947 non-null    object
 1   gt                  947 non-null    object
 2   img                 947 non-null    object
 3   ocr                 947 non-null    object
 4   zero-shot-question  947 non-null    object
 5   cot-question        947 non-null    object
dtypes: object(6)
memory usage: 44.5+ KB

## Prompt Length

In [44]:
# extract prompt length
def prompt_length(text, add_special_tokens=True):
    if pd.isnull(text) or not isinstance(text, str) or not text.strip():
        return 0
    temp_inputs = tokenizer(text, return_tensors="pt", add_special_tokens=add_special_tokens)
    return temp_inputs.input_ids.shape[1]

In [45]:
# Prompt Length -> Cloud Logs
cloud_processed['zero-shot-question-length'] = cloud_processed['zero-shot-question'].apply(prompt_length)
cloud_processed['cot-question-length'] = cloud_processed['cot-question'].apply(prompt_length)

In [46]:
# Prompt Length -> Device Logs
device_processed['zero-shot-question-length'] = device_processed['zero-shot-question'].apply(prompt_length)
device_processed['cot-question-length'] = device_processed['cot-question'].apply(prompt_length)

# Generate Response

In [47]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

### Zero-Shot

In [48]:
import os
import torch
import gc
import traceback

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"
torch.set_grad_enabled(False)

torch.manual_seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

def generate_zero_shot_answer(row):
    try:
        # Encode the question and move to the model’s device
        input_ids = tokenizer(
            row["zero-shot-question"], return_tensors="pt"
        ).input_ids.to(model.device)
        prompt_length=input_ids.shape[1]

        # Generate a completion
        output = model.generate(
            input_ids,
            max_new_tokens=768,
            do_sample=False,
            use_cache=True
        )

        # Decode and return the answer only
        return tokenizer.decode(output[0][prompt_length:], skip_special_tokens=True)

    except Exception as e:
        # Return the error string (no prompt info)
        return f"[ERROR] {e}\n{traceback.format_exc()}"

    finally:
        # Clean up GPU / RAM
        for var in ("input_ids", "output"):
            if var in locals():
                del locals()[var]
        torch.cuda.empty_cache()
        gc.collect()

### CoT

In [49]:
import os
import torch
import gc
import traceback

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"
torch.set_grad_enabled(False)

torch.manual_seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

def generate_cot_answer(row):
    try:
        input_ids = tokenizer(
            row["cot-question"], return_tensors="pt"
        ).input_ids.to(model.device)
        prompt_length=input_ids.shape[1]

        output = model.generate(
            input_ids,
            max_new_tokens=768,
            do_sample=False,
            use_cache=True,
        )

        return tokenizer.decode(output[0][prompt_length:], skip_special_tokens=True)

    except Exception as e:
        return f"[ERROR] {e}\n{traceback.format_exc()}"

    finally:
        for var in ("input_ids", "output"):
            if var in locals():
                del locals()[var]
        torch.cuda.empty_cache()
        gc.collect()

## Testing Samples

In [50]:
sample = cloud_processed.sort_values('zero-shot-question-length', ascending=False).head(3).reset_index(drop=True)

In [51]:
sample =cloud_processed[0:3]

In [52]:
sample.head(2)

,context,gt,img,ocr,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],img0:\nNon-table text:\n Stale resources dete...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,169,175
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",img0:\nTables:\nTable 0:\n+----+--------------...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,3224,3230

In [53]:
print(sample['zero-shot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
  Stale resources detected
                                                 ×
                                                 x
     Some recently changed resources are not yet published. Continue with launch?
 ?
                                             No
                                   Yes

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Answer:

In [54]:
zero_results = []
failed_responses = []
jsonl_records = []

output_file="llm_ocr_sample_deepseek_r1_distill_qwen_7b_zero_shot_results.jsonl"
failed_file="llm_ocr_sample_deepseek_r1_distill_qwen_7b_zero_shot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass

for idx, row in tqdm(sample.iterrows(), total=len(sample)):
    answer = generate_zero_shot_answer(row)

    # Track response
    zero_results.append(answer)

    # Sample print preview
    if idx == 0:
        question_text = row['zero-shot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Question:\n")
        print(short_question)

        print("\n\nSample Response:\n")
        print(answer)

    # JSONL record
    record = {
        "row": idx,
        "question": row["zero-shot-question"],
        "response": answer
    }

    jsonl_records.append(record)
    
    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
             f.write(json.dumps(failed_responses) + "\n")
    

# Add generated answers to DataFrame
sample["zero-shot-generated-answer"] = zero_results

  0%|          | 0/3 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token.As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
 33%|███▎      | 1/3 [00:01<00:03,  1.95s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

Sample Question:


You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text


Sample Response:

</think>

The error message indicates that some recently changed resources are not yet published. To resolve this issue, ensure that the latest code is published before starting the GAE server. If the problem persists, consider checking the project settings, restarting the server, or seeking further assistance from the Google Cloud Platform community.

 67%|██████▋   | 2/3 [00:07<00:03,  3.85s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
100%|██████████| 3/3 [00:09<00:00,  3.08s/it]
/tmp/ipykernel_117/2873790280.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample["zero-shot-generated-answer"] = zero_results

In [55]:
print(zero_results[2])

</think>

To add a "Deploy to Heroku" button that requires environment variables, you can include these variables in your app.json schema. This allows users to set the necessary variables before deployment. For example, you can add a section in your app.json like:

```json
{
  "env": {
    "HEROKU_API_KEY": "your_api_key",
    "REPOSITORY_NAME": "your_repository_name"
  }
}
```

You can then instruct users to replace the placeholder values in your README file with their actual Heroku credentials. This approach keeps the deployment process user-friendly while ensuring security.

In [56]:
import json
from tqdm import tqdm

cot_results = []
failed_cot_responses = []
cot_jsonl_records = []

output_file="llm_ocr_sample_deepseek_r1_distill_qwen_7b_cot_results.jsonl"
failed_file="llm_ocr_sample_deepseek_r1_distill_qwen_7b_cot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass


for idx, row in tqdm(sample.iterrows(), total=len(sample)):
    answer = generate_cot_answer(row)

    # Append result
    cot_results.append(answer)

    # Show sample only for first entry
    if idx == 0:
        question_text = row['cot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample CoT Question:\n")
        print(short_question)

        print("\n\nSample CoT Response:\n")
        print(answer)

    # Record for JSONL
    record = {
        "index": idx,
        "question": row["cot-question"],
        "response": answer
    }
    jsonl_records.append(record)
    
    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
            f.write(json.dumps(record) + "\n")
    


# Add generated CoT answers to DataFrame
sample["cot-generated-answer"] = cot_results

  0%|          | 0/3 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
 33%|███▎      | 1/3 [00:01<00:02,  1.03s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

Sample CoT Question:


You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text


Sample CoT Response:

</think>

The error message indicates that some recently changed resources are not yet published. To resolve this, you should click "Yes" to proceed with the launch. If the issue persists, consider updating your codebase or seeking further assistance from the relevant community or support channels.

 67%|██████▋   | 2/3 [00:04<00:02,  2.65s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
100%|██████████| 3/3 [00:07<00:00,  2.58s/it]
/tmp/ipykernel_117/3151197572.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample["cot-generated-answer"] = cot_results

In [57]:
print(cot_results[2])

</think>

To add a "Deploy to Heroku" button that requires environment variables, you can:

1. **Prompt Users in App.json Schema**: Include a form in your app.json that asks users to input their Heroku credentials before deploying. This allows you to capture the necessary information directly within your app.

2. **Use Heroku's Secret Key**: Generate a secret key for your Heroku app and store it in your app.json. This ensures that the credentials are securely stored and not exposed in the code.

3. **Set Defaults in Code**: If you prefer not to use a form, you can set default values for the required environment variables in your code. However, this means users will need to manually update these values in their `.env` file.

By implementing one of these methods, you can streamline the deployment process for users while maintaining security and ease of use.

In [ ]:
sample.to_csv("sample_llm_ocr_deepseek_r1_distill_qwen_7b.csv")

## Cloud Testset

In [79]:
cloud_testset=cloud_processed

In [80]:
cloud_testset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1568 entries, 0 to 1567
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   context                    1568 non-null   object
 1   gt                         1568 non-null   object
 2   img                        1568 non-null   object
 3   ocr                        1568 non-null   object
 4   zero-shot-question         1568 non-null   object
 5   cot-question               1568 non-null   object
 6   zero-shot-question-length  1568 non-null   int64
 7   cot-question-length        1568 non-null   int64
dtypes: int64(2), object(6)
memory usage: 98.1+ KB

In [81]:
cloud_testset.head(2)

,context,gt,img,ocr,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],img0:\nNon-table text:\n Stale resources dete...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,169,175
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",img0:\nTables:\nTable 0:\n+----+--------------...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,3224,3230

### zero shot response

In [82]:
import json
from tqdm import tqdm

zero_cloud_results = []
zero_cloud_jsonl_records = []
zero_cloud_failed_responses = []

output_file="llm_ocr_cloud_deepseek_r1_distill_qwen_7b_zero_shot_results.jsonl"
failed_file="llm_ocr_cloud_deepseek_r1_distill_qwen_7b_zero_shot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass

for idx, row in tqdm(cloud_testset.iterrows(), total=len(cloud_testset)):
    # Generate answer
    answer = generate_zero_shot_answer(row)
    zero_cloud_results.append(answer)

    # Show the first response as a sample
    if idx == 0:
        question_text = row['zero-shot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Cloud Zero-Shot Question:\n")
        print(short_question)

        print("\n\nSample Cloud Zero-Shot Response:\n")
        print(answer)

    # Prepare JSONL record
    record = {
        "row": idx,
        "question": row["zero-shot-question"],
        "response": answer
    }
    zero_cloud_jsonl_records.append(record)

    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
          f.write(json.dumps(record) + "\n")

# Save results in the DataFrame
cloud_testset["zero-shot-generated-answer"] = zero_cloud_results

  0%|          | 0/1568 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 1/1568 [00:01<28:54,  1.11s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

Sample Cloud Zero-Shot Question:


You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text


Sample Cloud Zero-Shot Response:

</think>

The error message indicates that some recently changed resources are not yet published. To resolve this issue, ensure that the latest code is published before starting the GAE server. If the problem persists, consider checking the project settings, restarting the server, or seeking further assistance from the Google Cloud Platform community.

  0%|          | 2/1568 [00:06<1:30:17,  3.46s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 3/1568 [00:08<1:13:42,  2.83s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 4/1568 [00:11<1:18:48,  3.02s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 5/1568 [00:14<1:14:27,  2.86s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 6/1568 [00:16<1:06:18,  2.55s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 7/1568 [00:16<49:41,  1.91s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 8/1568 [00:18<46:29,  1.79s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 9/1568 [00:21<56:55,  2.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 10/1568 [00:23<59:59,  2.31s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 11/1568 [00:26<1:00:26,  2.33s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 12/1568 [00:30<1:15:59,  2.93s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 13/1568 [00:40<2:10:52,  5.05s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 14/1568 [00:42<1:46:02,  4.09s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 15/1568 [00:44<1:29:03,  3.44s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 16/1568 [00:49<1:44:20,  4.03s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 17/1568 [00:53<1:40:54,  3.90s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 18/1568 [01:04<2:36:01,  6.04s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 19/1568 [01:06<2:08:38,  4.98s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 20/1568 [01:08<1:40:10,  3.88s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 21/1568 [01:08<1:15:13,  2.92s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 22/1568 [01:13<1:27:56,  3.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 23/1568 [01:24<2:27:29,  5.73s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 24/1568 [01:26<1:55:36,  4.49s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 25/1568 [01:27<1:30:51,  3.53s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 26/1568 [01:30<1:30:20,  3.52s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 27/1568 [01:37<1:51:19,  4.33s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 28/1568 [01:43<2:06:54,  4.94s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 29/1568 [01:44<1:35:59,  3.74s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 30/1568 [01:46<1:25:04,  3.32s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 31/1568 [02:06<3:29:04,  8.16s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 32/1568 [02:07<2:35:31,  6.08s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 33/1568 [02:08<1:59:10,  4.66s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 34/1568 [02:09<1:31:01,  3.56s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 35/1568 [02:10<1:10:52,  2.77s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 36/1568 [02:11<57:13,  2.24s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 37/1568 [02:13<49:41,  1.95s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 38/1568 [02:15<56:43,  2.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 39/1568 [02:16<48:06,  1.89s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 40/1568 [02:17<40:31,  1.59s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 41/1568 [02:19<40:13,  1.58s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 42/1568 [02:24<1:04:25,  2.53s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 43/1568 [02:27<1:09:40,  2.74s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 44/1568 [02:29<1:03:39,  2.51s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 45/1568 [02:31<57:50,  2.28s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 46/1568 [02:32<51:41,  2.04s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 47/1568 [02:42<1:48:25,  4.28s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 48/1568 [02:43<1:23:20,  3.29s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 49/1568 [02:44<1:05:42,  2.60s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 50/1568 [02:47<1:12:15,  2.86s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 51/1568 [02:48<59:42,  2.36s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 52/1568 [02:54<1:22:25,  3.26s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 53/1568 [02:58<1:33:03,  3.69s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 54/1568 [03:02<1:30:38,  3.59s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▎         | 55/1568 [03:03<1:11:06,  2.82s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▎         | 56/1568 [03:03<52:08,  2.07s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▎         | 57/1568 [03:05<50:25,  2.00s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▎         | 58/1568 [03:06<42:57,  1.71s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 59/1568 [03:06<33:22,  1.33s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 60/1568 [03:14<1:20:28,  3.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 61/1568 [03:15<1:05:28,  2.61s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 62/1568 [03:19<1:13:25,  2.93s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 63/1568 [03:21<1:08:04,  2.71s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 64/1568 [03:23<1:01:05,  2.44s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 65/1568 [03:25<58:57,  2.35s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 66/1568 [03:27<56:34,  2.26s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 67/1568 [03:28<50:31,  2.02s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

In [83]:
zero_cloud_results[1]

'</think>\n\nThe issue arises because the artifact size in the deployment is incorrectly reported as 1 KB, while the actual artifact size is 17 MB. This discrepancy causes confusion about why the ZIP file cannot be extracted. The correct size is 17 MB, which aligns with the artifact observed when dragging and dropping the ZIP file into the Kudo Console. This indicates that the size reported in the deployment is incorrect, possibly due to a misconfiguration or error in the deployment task. The correct behavior is that the artifact size should match the actual size of the ZIP file, allowing it to be extracted and deployed successfully.\n\nAnswer:\n\nThe size of the artifact in the deployment is incorrectly reported as 1 KB, while the actual size of the ZIP file is 17 MB. This discrepancy causes the issue of the ZIP file not being extractable. The correct size should be 17 MB, which is the actual size of the artifact.'

In [84]:
cloud_testset.head(2)

,context,gt,img,ocr,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero-shot-generated-answer
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],img0:\nNon-table text:\n Stale resources dete...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,169,175,</think>\n\nThe error message indicates that s...
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",img0:\nTables:\nTable 0:\n+----+--------------...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,3224,3230,</think>\n\nThe issue arises because the artif...

In [85]:
cloud_testset.to_excel("../../../outputs/responses/baselines/llm_ocr/cloud/llm_ocr_response_cloud_deepseek_r1_distill_qwen_7b_zero_shot.xlsx", index=False)

### Cot Response

In [ ]:
import json
from tqdm import tqdm

cot_cloud_results = []
failed_cloud_cot_responses = []
cot_cloud_jsonl_records = []

output_file="llm_ocr_cloud_deepseek_r1_distill_qwen_7b_cot_results.jsonl"
failed_file="llm_ocr_cloud_deepseek_r1_distill_qwen_7b_cot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass


for idx, row in tqdm(cloud_testset.iterrows(), total=len(cloud_testset)):
    # Generate answer using CoT function
    answer = generate_cot_answer(row)
    cot_cloud_results.append(answer)

    # Sample output (first only)
    if idx == 0:
        question_text = row['cot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Cloud CoT Question:\n")
        print(short_question)

        print("\n\nSample Cloud CoT Response:\n")
        print(answer)

    # Prepare JSONL entry
    record = {
        "row": idx,
        "question": row["cot-question"],
        "response": answer
    }
    cot_cloud_jsonl_records.append(record)
    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
            f.write(json.dumps(record) + "\n")

# Append column to DataFrame
cloud_testset["cot-generated-answer"] = cot_cloud_results

  0%|          | 0/1568 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 1/1568 [00:00<25:38,  1.02it/s]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

Sample Cloud CoT Question:


You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text


Sample Cloud CoT Response:

</think>

The error message indicates that some recently changed resources are not yet published. To resolve this, you should click "Yes" to proceed with the launch. If the issue persists, consider updating your codebase or seeking further assistance from the relevant community or support channels.

  0%|          | 2/1568 [00:04<1:06:58,  2.57s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 3/1568 [00:07<1:10:42,  2.71s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 4/1568 [00:11<1:19:38,  3.06s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 5/1568 [00:12<1:03:10,  2.43s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 6/1568 [00:13<53:52,  2.07s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 7/1568 [00:14<40:52,  1.57s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 8/1568 [00:17<54:06,  2.08s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 9/1568 [00:29<2:18:14,  5.32s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 10/1568 [00:42<3:18:14,  7.63s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 11/1568 [00:44<2:33:16,  5.91s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 12/1568 [00:47<2:11:19,  5.06s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 13/1568 [00:56<2:38:12,  6.10s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 14/1568 [00:58<2:05:20,  4.84s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 15/1568 [00:59<1:32:53,  3.59s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 16/1568 [01:02<1:32:53,  3.59s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 17/1568 [01:05<1:27:23,  3.38s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 18/1568 [01:09<1:30:46,  3.51s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 19/1568 [01:16<1:56:31,  4.51s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 20/1568 [01:17<1:34:19,  3.66s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 21/1568 [01:19<1:17:23,  3.00s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 22/1568 [01:24<1:37:30,  3.78s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 23/1568 [01:37<2:47:24,  6.50s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 24/1568 [01:39<2:09:59,  5.05s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 25/1568 [01:41<1:49:31,  4.26s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 26/1568 [01:43<1:31:12,  3.55s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 27/1568 [01:51<2:02:41,  4.78s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 28/1568 [01:53<1:41:54,  3.97s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 29/1568 [01:54<1:22:48,  3.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 30/1568 [01:57<1:17:23,  3.02s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 31/1568 [02:19<3:43:24,  8.72s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 32/1568 [02:20<2:44:39,  6.43s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 33/1568 [02:21<2:04:44,  4.88s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 34/1568 [02:22<1:34:52,  3.71s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 35/1568 [02:27<1:43:25,  4.05s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 36/1568 [02:28<1:21:28,  3.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 37/1568 [02:29<1:05:35,  2.57s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 38/1568 [02:32<1:06:54,  2.62s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 39/1568 [02:33<54:34,  2.14s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 40/1568 [02:37<1:06:39,  2.62s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 41/1568 [02:49<2:22:00,  5.58s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 42/1568 [02:53<2:03:34,  4.86s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 43/1568 [02:55<1:47:48,  4.24s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 44/1568 [02:57<1:28:15,  3.47s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 45/1568 [02:59<1:13:42,  2.90s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 46/1568 [03:01<1:09:40,  2.75s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 47/1568 [03:05<1:15:50,  2.99s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 48/1568 [03:06<1:06:23,  2.62s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 49/1568 [03:19<2:23:55,  5.69s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 50/1568 [03:22<2:04:58,  4.94s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 51/1568 [03:25<1:43:47,  4.10s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 52/1568 [03:29<1:47:35,  4.26s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 53/1568 [03:32<1:33:01,  3.68s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 54/1568 [03:36<1:36:23,  3.82s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▎         | 55/1568 [03:37<1:18:41,  3.12s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▎         | 56/1568 [03:39<1:09:31,  2.76s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▎         | 57/1568 [03:41<1:00:11,  2.39s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▎         | 58/1568 [03:42<50:37,  2.01s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 59/1568 [03:48<1:18:58,  3.14s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 60/1568 [03:50<1:17:24,  3.08s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 61/1568 [03:53<1:11:39,  2.85s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 62/1568 [04:01<1:55:26,  4.60s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 63/1568 [04:06<1:52:52,  4.50s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 64/1568 [04:18<2:54:07,  6.95s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 65/1568 [04:20<2:16:21,  5.44s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 66/1568 [04:22<1:47:29,  4.29s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 67/1568 [04:24<1:28:36,  3.54s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

In [ ]:
cloud_testset.head(2)

In [ ]:
cloud_testset.to_excel("../../../outputs/responses/baselines/llm_ocr/cloud/llm_ocr_response_cloud_deepseek_r1_distill_qwen_7b_zero_shot.xlsx", index=False)

## Device Testset

In [58]:
device_testset=device_processed

In [59]:
device_testset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 947 entries, 0 to 946
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   context                    947 non-null    object
 1   gt                         947 non-null    object
 2   img                        947 non-null    object
 3   ocr                        947 non-null    object
 4   zero-shot-question         947 non-null    object
 5   cot-question               947 non-null    object
 6   zero-shot-question-length  947 non-null    int64
 7   cot-question-length        947 non-null    int64
dtypes: int64(2), object(6)
memory usage: 59.3+ KB

In [60]:
device_testset.shape

(947, 8)

### Zero shot Response

In [61]:
import json
from tqdm import tqdm

# Lists for tracking
zero_device_results = []
zero_device_jsonl_records = []
zero_device_failed_responses = []

output_file="llm_ocr_device_deepseek_r1_distill_qwen_7b_zero_shot_results.jsonl"
failed_file="llm_ocr_device_deepseek_r1_distill_qwen_7b_zero_shot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass

for idx, row in tqdm(device_testset.iterrows(), total=len(device_testset)):
    # Generate zero-shot answer
    answer = generate_zero_shot_answer(row)
    zero_device_results.append(answer)

    # Print one sample preview
    if idx == 0:
        question_text = row["zero-shot-question"]
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Device Zero-Shot Question:\n")
        print(short_question)

        print("\n\nSample Device Zero-Shot Response:\n")
        print(answer)

    # Build JSONL record
    record = {
        "row": idx,
        "question": row["zero-shot-question"],
        "response": answer
    }
    zero_device_jsonl_records.append(record)

    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
            f.write(json.dumps(record) + "\n")


# Add results to DataFrame
device_testset["zero-shot-generated-answer"] = zero_device_results

  0%|          | 0/947 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 1/947 [00:00<14:10,  1.11it/s]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

Sample Device Zero-Shot Question:


You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text


Sample Device Zero-Shot Response:

</think>

The purpose of the INPUT chain in the nat table is to handle the translation of source addresses (SNAT) for incoming packets, allowing for source address translation which is essential for establishing connections to external networks.

  0%|          | 2/947 [00:18<2:49:55, 10.79s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 3/947 [00:20<1:43:40,  6.59s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 4/947 [00:24<1:26:33,  5.51s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 5/947 [00:37<2:09:15,  8.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 6/947 [00:38<1:33:01,  5.93s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 7/947 [00:39<1:08:04,  4.35s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 8/947 [00:40<50:36,  3.23s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 9/947 [00:57<1:58:54,  7.61s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 10/947 [01:12<2:35:15,  9.94s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 11/947 [01:18<2:14:14,  8.61s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 12/947 [01:28<2:20:24,  9.01s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 13/947 [01:29<1:44:08,  6.69s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 14/947 [01:34<1:33:11,  5.99s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 15/947 [01:35<1:11:58,  4.63s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 16/947 [01:37<58:30,  3.77s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 17/947 [01:39<48:21,  3.12s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 18/947 [01:41<43:56,  2.84s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 19/947 [01:44<46:00,  2.97s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 20/947 [01:48<49:21,  3.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 21/947 [01:50<46:52,  3.04s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 22/947 [01:51<33:56,  2.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 23/947 [01:52<28:55,  1.88s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 24/947 [02:04<1:18:50,  5.12s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 25/947 [02:06<1:03:11,  4.11s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 26/947 [02:10<59:39,  3.89s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 27/947 [02:18<1:18:55,  5.15s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 28/947 [02:21<1:10:43,  4.62s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 29/947 [02:34<1:49:08,  7.13s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 30/947 [02:47<2:16:10,  8.91s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 31/947 [02:48<1:39:14,  6.50s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 32/947 [03:01<2:10:28,  8.56s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 33/947 [03:02<1:35:47,  6.29s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▎         | 34/947 [03:21<2:30:21,  9.88s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▎         | 35/947 [03:21<1:48:54,  7.16s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 36/947 [03:23<1:23:08,  5.48s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 37/947 [03:25<1:08:05,  4.49s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 38/947 [03:26<53:45,  3.55s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 39/947 [03:33<1:08:44,  4.54s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 40/947 [03:51<2:06:50,  8.39s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 41/947 [03:53<1:36:55,  6.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 42/947 [03:55<1:19:49,  5.29s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▍         | 43/947 [03:59<1:15:04,  4.98s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▍         | 44/947 [04:01<58:42,  3.90s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▍         | 45/947 [04:01<42:08,  2.80s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▍         | 46/947 [04:08<1:01:25,  4.09s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▍         | 47/947 [04:09<48:21,  3.22s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▌         | 48/947 [04:11<43:13,  2.88s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▌         | 49/947 [04:14<42:23,  2.83s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▌         | 50/947 [04:16<39:17,  2.63s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▌         | 51/947 [04:20<42:21,  2.84s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▌         | 52/947 [04:34<1:35:47,  6.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 53/947 [04:40<1:30:44,  6.09s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 54/947 [04:42<1:15:28,  5.07s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 55/947 [04:46<1:06:37,  4.48s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 56/947 [04:49<1:01:00,  4.11s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 57/947 [04:51<52:23,  3.53s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 58/947 [04:53<45:04,  3.04s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 59/947 [04:55<42:43,  2.89s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▋         | 60/947 [04:56<31:07,  2.10s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▋         | 61/947 [05:02<50:22,  3.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  7%|▋         | 62/947 [05:04<42:31,  2.88s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  7%|▋         | 63/947 [05:08<46:56,  3.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  7%|▋         | 64/947 [05:09<39:56,  2.71s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  7%|▋         | 65/947 [05:11<33:49,  2.30s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  7%|▋         | 66/947 [05:11<26:51,  1.83s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  7%|▋         | 67/947 [05:17<43:09,  2.94s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

In [62]:
device_testset.head(2)

,context,gt,img,ocr,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero-shot-generated-answer
0,title: What is the purpose of the INPUT chain ...,\r\nIf some NAT operation needs to be only don...,['https://i.sstatic.net/NUh2k.png'],img0:\nNon-table text:\n CT\n ...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,532,538,</think>\n\nThe purpose of the INPUT chain in ...
1,"title: Logstash JDBC input, filter event times...",\r\nOK I finally figure how to get the @timest...,"['https://i.sstatic.net/3nAZ9.png', 'https://i...",img0:\nTables:\nTable 0:\n+-------------------...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,4902,4908,</think>\n\nThe issue arises because the `@tim...

In [63]:
device_testset.to_excel("../../../outputs/responses/baselines/llm_ocr/device/llm_ocr_response_device_deepseek_r1_distill_qwen_7b_zero_shot.xlsx", index=False)

### CoT Response

In [64]:
import json
from tqdm import tqdm

# Containers
cot_device_results = []
cot_device_jsonl_records = []
cot_device_failed_responses = []

output_file="llm_ocr_device_deepseek_r1_distill_qwen_7b_cot_results.jsonl"
failed_file="llm_ocr_device_deepseek_r1_distill_qwen_7b_cot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass

for idx, row in tqdm(device_testset.iterrows(), total=len(device_testset)):
    # Generate CoT answer
    answer = generate_cot_answer(row)
    cot_device_results.append(answer)

    # Print one sample preview
    if idx == 0:
        question_text = row["cot-question"]
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Device CoT Question:\n")
        print(short_question)

        print("\n\nSample Device CoT Response:\n")
        print(answer)

    # JSONL record
    record = {
        "row": idx,
        "question": row["cot-question"],
        "response": answer
    }
    cot_device_jsonl_records.append(record)

    with open(output_file, "a") as f:
        f.write(json.dumps(jsonl_records) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
            f.write(json.dumps(failed_responses) + "\n")

# Write results back to DataFrame
device_testset["cot-generated-answer"] = cot_device_results

  0%|          | 0/947 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 1/947 [00:01<26:45,  1.70s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

Sample Device CoT Question:


You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text


Sample Device CoT Response:

</think>

The purpose of the INPUT chain in the nat table is to handle packets that originate from the local network, allowing them to be routed to the appropriate destination without modification. This is distinct from the PREROUTING chain, which processes incoming packets from external networks, applying DNAT for port forwarding. The INPUT chain is typically used for managing local traffic, such as handling local applications or services, whereas the PREROUTING chain is for external traffic management.

  0%|          | 2/947 [00:15<2:19:15,  8.84s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 3/947 [00:17<1:27:55,  5.59s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  0%|          | 4/947 [00:21<1:17:47,  4.95s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 5/947 [00:21<52:45,  3.36s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 6/947 [00:23<42:19,  2.70s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 7/947 [00:24<33:50,  2.16s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 8/947 [00:25<29:36,  1.89s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 9/947 [00:33<57:20,  3.67s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 10/947 [00:38<1:07:34,  4.33s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|          | 11/947 [00:45<1:16:20,  4.89s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 12/947 [00:47<1:02:32,  4.01s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 13/947 [00:49<55:28,  3.56s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  1%|▏         | 14/947 [00:54<59:58,  3.86s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 15/947 [01:06<1:40:58,  6.50s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 16/947 [01:09<1:24:39,  5.46s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 17/947 [01:13<1:16:10,  4.91s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 18/947 [01:15<1:03:04,  4.07s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 19/947 [01:18<55:53,  3.61s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 20/947 [01:21<56:40,  3.67s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 21/947 [01:26<59:49,  3.88s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 22/947 [01:30<1:02:21,  4.04s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  2%|▏         | 23/947 [01:33<57:52,  3.76s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 24/947 [01:46<1:38:36,  6.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 25/947 [01:48<1:16:37,  4.99s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 26/947 [01:53<1:18:19,  5.10s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 27/947 [02:02<1:37:11,  6.34s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 28/947 [02:03<1:13:05,  4.77s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 29/947 [02:16<1:50:01,  7.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 30/947 [02:21<1:39:41,  6.52s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 31/947 [02:22<1:12:24,  4.74s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 32/947 [02:29<1:26:20,  5.66s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  3%|▎         | 33/947 [02:39<1:43:50,  6.82s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▎         | 34/947 [02:44<1:34:52,  6.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▎         | 35/947 [02:45<1:12:20,  4.76s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 36/947 [02:46<55:45,  3.67s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 37/947 [02:57<1:27:12,  5.75s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 38/947 [02:58<1:06:23,  4.38s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 39/947 [03:11<1:43:20,  6.83s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 40/947 [03:14<1:28:34,  5.86s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 41/947 [03:16<1:08:56,  4.57s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  4%|▍         | 42/947 [03:20<1:05:03,  4.31s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▍         | 43/947 [03:25<1:10:23,  4.67s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▍         | 44/947 [03:27<59:55,  3.98s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▍         | 45/947 [03:29<49:41,  3.31s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▍         | 46/947 [03:35<1:03:06,  4.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▍         | 47/947 [03:37<52:14,  3.48s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▌         | 48/947 [03:39<45:02,  3.01s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▌         | 49/947 [03:42<45:24,  3.03s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▌         | 50/947 [03:44<39:18,  2.63s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▌         | 51/947 [03:48<45:13,  3.03s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  5%|▌         | 52/947 [03:54<1:00:09,  4.03s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 53/947 [04:00<1:06:08,  4.44s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 54/947 [04:02<55:23,  3.72s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 55/947 [04:08<1:07:09,  4.52s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 56/947 [04:12<1:05:52,  4.44s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 57/947 [04:19<1:14:24,  5.02s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 58/947 [04:20<59:42,  4.03s/it]  The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▌         | 59/947 [04:23<53:52,  3.64s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▋         | 60/947 [04:23<38:45,  2.62s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  6%|▋         | 61/947 [04:30<58:24,  3.96s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  7%|▋         | 62/947 [04:32<47:22,  3.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  7%|▋         | 63/947 [04:37<54:29,  3.70s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  7%|▋         | 64/947 [04:38<44:11,  3.00s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  7%|▋         | 65/947 [04:40<39:27,  2.68s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  7%|▋         | 66/947 [04:41<33:16,  2.27s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
  7%|▋         | 67/947 [04:57<1:34:01,  6.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

In [78]:
print(cot_device_results[123])

</think>

To examine your Windows Firewall outbound rules, use the **Firewall** command in the Command Prompt. Here's how:

1. Open the Command Prompt.
2. Type `firewall.exe` and press Enter.
3. In the Firewall Configuration window, click **View** > **Outbound Rules**.
4. Review the outbound rules, including the one for port 9000.

If the rule isn't listed, check the **General** menu for any additional outbound rules. If the issue persists, ensure the program is correctly listening on port 9000 and that the firewall permissions are set properly.

In [65]:
device_testset.head(2)

,context,gt,img,ocr,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero-shot-generated-answer,cot-generated-answer
0,title: What is the purpose of the INPUT chain ...,\r\nIf some NAT operation needs to be only don...,['https://i.sstatic.net/NUh2k.png'],img0:\nNon-table text:\n CT\n ...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,532,538,</think>\n\nThe purpose of the INPUT chain in ...,</think>\n\nThe purpose of the INPUT chain in ...
1,"title: Logstash JDBC input, filter event times...",\r\nOK I finally figure how to get the @timest...,"['https://i.sstatic.net/3nAZ9.png', 'https://i...",img0:\nTables:\nTable 0:\n+-------------------...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,4902,4908,</think>\n\nThe issue arises because the `@tim...,</think>\n\nThe user is experiencing a discrep...

In [66]:
device_testset.to_excel("../../../outputs/responses/baselines/llm_ocr/device/llm_ocr_response_device_deepseek_r1_distill_qwen_7b_zero_shot.xlsx", index=False)