# Environment

In [ ]:
! pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 2.0 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 239.4 MB/s eta 0:00:00 0:00:01
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 153.0 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 kB 128.8 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2025.2 tzdata-2025.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

In [ ]:
!pip install --upgrade transformers accelerate pillow

Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.1.0+cu118)
Collecting torch
  Downloading torch-2.7.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting transformers
  Downloading transformers-4.52.3-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.2/40.2 kB 14.5 MB/s eta 0:00:00
Collecting accelerate
  Downloading accelerate-1.7.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (9.3.0)
Collecting pillow
  Downloading pillow-11.2.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (8.9 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.9.0)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading typing_extensions-4.13.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2023.4.0)
Collecting nvidia-cuda-nvrtc-cu12==12.6.77 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.6.77 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.6.80 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.5.1.17 (from torch)
  Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.6.4.1 (from torch)
  Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.3.0.4 (from torch)
  Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.7.77 (from torch)
  Downloading nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.7.1.2 (from torch)
  Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.5.4.2 (from torch)
  Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparselt-cu12==0.6.3 (from torch)
  Downloading nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.26.2 (from torch)
  Downloading nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvtx-cu12==12.6.77 (from torch)
  Downloading nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nvjitlink-cu12==12.6.85 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufile-cu12==1.11.1.6 (from torch)
  Downloading nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.3.0 (from torch)
  Downloading triton-3.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: setuptools>=40.8.0 in /usr/local/lib/python3.10/dist-packages (from triton==3.3.0->torch) (68.2.2)
Collecting huggingface-hub<1.0,>=0.30.0 (from transformers)
  Downloading huggingface_hub-0.32.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.24.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 17.0 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting tqdm>=4.27 (from transformers)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 23.9 MB/s eta 0:00:00
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.6)
Collecting fsspec (from torch)
  Downloading fsspec-2025.5.1-py3-none-any.whl.metadata (11 kB)
Collecting hf-xet<2.0.0,>=1.1.2 (from huggingface-hub<1.0,>=0.30.0->transformers)
  Downloading hf_xet-1.1.2-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (879 bytes)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2022.12.7)
Downloading torch-2.7.0-cp310-cp310-manylinux_2_28_x86_64.whl (865.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 865.2/865.2 MB 19.6 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (393.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 39.3 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 242.6 MB/s eta 0:00:0000:01
Downloading nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 208.2 MB/s eta 0:00:00a 0:00:01
Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (897 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 kB 185.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl (571.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.0/571.0 MB 29.5 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (200.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 70.1 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 203.2 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 153.2 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (158.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 MB 80.0 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (216.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 MB 69.0 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl (156.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.8/156.8 MB 84.4 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (201.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.3/201.3 MB 71.7 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (19.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 212.3 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.3/89.3 kB 37.8 MB/s eta 0:00:00
Downloading triton-3.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (156.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.4/156.4 MB 78.7 MB/s eta 0:00:0000:0100:01
Downloading transformers-4.52.3-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 40.3 MB/s eta 0:00:0000:010:01
Downloading accelerate-1.7.0-py3-none-any.whl (362 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 362.1/362.1 kB 77.5 MB/s eta 0:00:00
Downloading pillow-11.2.1-cp310-cp310-manylinux_2_28_x86_64.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 179.1 MB/s eta 0:00:00
Downloading huggingface_hub-0.32.0-py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.3/509.3 kB 141.3 MB/s eta 0:00:00
Downloading fsspec-2025.5.1-py3-none-any.whl (199 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 kB 78.0 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.7/781.7 kB 167.6 MB/s eta 0:00:00
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 133.9 MB/s eta 0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 223.1 MB/s eta 0:00:00
Downloading tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 226.1 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 34.8 MB/s eta 0:00:00
Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 21.9 MB/s eta 0:00:00
Downloading hf_xet-1.1.2-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 83.7 MB/s eta 0:00:00a 0:00:01
Installing collected packages: nvidia-cusparselt-cu12, typing-extensions, triton, tqdm, sympy, safetensors, regex, pillow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, hf-xet, fsspec, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, accelerate
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.4.0
    Uninstalling typing_extensions-4.4.0:
      Successfully uninstalled typing_extensions-4.4.0
  Attempting uninstall: triton
    Found existing installation: triton 2.1.0
    Uninstalling triton-2.1.0:
      Successfully uninstalled triton-2.1.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12
    Uninstalling sympy-1.12:
      Successfully uninstalled sympy-1.12
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.3.0
    Uninstalling Pillow-9.3.0:
      Successfully uninstalled Pillow-9.3.0
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2023.4.0
    Uninstalling fsspec-2023.4.0:
      Successfully uninstalled fsspec-2023.4.0
  Attempting uninstall: torch
    Found existing installation: torch 2.1.0+cu118
    Uninstalling torch-2.1.0+cu118:
      Successfully uninstalled torch-2.1.0+cu118
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.0+cu118 requires torch==2.1.0, but you have torch 2.7.0 which is incompatible.
torchvision 0.16.0+cu118 requires torch==2.1.0, but you have torch 2.7.0 which is incompatible.
Successfully installed accelerate-1.7.0 fsspec-2025.5.1 hf-xet-1.1.2 huggingface-hub-0.32.0 nvidia-cublas-cu12-12.6.4.1 nvidia-cuda-cupti-cu12-12.6.80 nvidia-cuda-nvrtc-cu12-12.6.77 nvidia-cuda-runtime-cu12-12.6.77 nvidia-cudnn-cu12-9.5.1.17 nvidia-cufft-cu12-11.3.0.4 nvidia-cufile-cu12-1.11.1.6 nvidia-curand-cu12-10.3.7.77 nvidia-cusolver-cu12-11.7.1.2 nvidia-cusparse-cu12-12.5.4.2 nvidia-cusparselt-cu12-0.6.3 nvidia-nccl-cu12-2.26.2 nvidia-nvjitlink-cu12-12.6.85 nvidia-nvtx-cu12-12.6.77 pillow-11.2.1 regex-2024.11.6 safetensors-0.5.3 sympy-1.14.0 tokenizers-0.21.1 torch-2.7.0 tqdm-4.67.1 transformers-4.52.3 triton-3.3.0 typing-extensions-4.13.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

## Import Library

In [1]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm import tqdm
import pandas as pd
import json

/usr/local/lib/python3.10/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Load Model

In [2]:
! nvidia-smi

Tue Jun 24 04:44:17 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          Off |   00000000:85:00.0 Off |                    0 |
| N/A   28C    P0             69W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [3]:
from huggingface_hub import login
import os

token = "HF_TOKEN_REDACTED"
os.environ['HF_TOKEN'] = token

login(token=token)
print("Logged in to Hugging Face!")

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /root/.cache/huggingface/token
Login successful
Logged in to Hugging Face!

### LLama

In [4]:
# meta-llama/Llama-3.1-8B-Instruct
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.1-8B-Instruct")
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.1-8B-Instruct")

Downloading shards: 100%|██████████| 4/4 [03:29<00:00, 52.32s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:07<00:00,  1.80s/it]

# Load Datasets

In [5]:
import pandas as pd
cloud=pd.read_excel("../../../data/splits/cloud/cloud_test.xlsx")
device=pd.read_excel("../../../data/splits/device/device_test.xlsx")

## Ocr Load

In [6]:
# ocr json

import json

with open("../../../data/processed/ocr/cloud/ocr_extracted_cloud_test.jsonl", "r", encoding="utf-8") as file:
    cloud_test_ocr = [json.loads(line) for line in file]

with open("../../../data/processed/ocr/device/ocr_extracted_device_test.jsonl", "r", encoding="utf-8") as file:
    device_test_ocr = [json.loads(line) for line in file]

In [7]:
from typing import List, Dict, Any

def ocr_extract(data) -> List[str]:
    results: List[str] = []

    for entry in data:
        lines=[]

        for img_i, img in enumerate(entry.get("images", [])):
            lines.append(f"img{img_i}:")

            for resp in img.get("response", []):
                if isinstance(resp, dict):
                    # --- non-table text ---
                    ntt = resp.get("non_table_text")
                    if ntt:
                        lines.append("Non-table text:")
                        lines.extend(ntt if isinstance(ntt, list) else [str(ntt)])

                    # --- tables ---
                    tables = resp.get("table")
                    if tables:
                        lines.append("Tables:")
                        for t_i, tbl in enumerate(tables if isinstance(tables, list) else [tables]):
                            lines.append(f"Table {t_i}:")
                            lines.append(tbl.get("content", "") if isinstance(tbl, dict) else str(tbl))
                    continue

                # Unknown or malformed type
                lines.append(f"[WARN] Unhandled response type: {type(resp).__name__}")
                lines.append(str(resp))

        formatted = "\n".join(lines).strip()
        if formatted:
            results.append(formatted)

    return results

In [8]:
# format ocr response for prompt
cloud_test_ocr_response_format = ocr_extract(cloud_test_ocr)   
device_test_ocr_response_format = ocr_extract(device_test_ocr)

In [9]:
len(cloud_test_ocr_response_format),len(device_test_ocr_response_format)

(1568, 947)

In [10]:
cloud['images'][1423]

"['https://i.sstatic.net/AKSXF.png']"

In [11]:
cloud_test_ocr_response_format[1423]

'img0:\nTables:\nTable 0:\n+-----------------------------------+------------+-----------+-----------+\n| EC2 Instance Type                 | Software   | EC2       | Total     |\n+-----------------------------------+------------+-----------+-----------+\n| Standard Large (m1.large)         | $0.00/hr   | $0.265/hr | $0.265/hr |\n+-----------------------------------+------------+-----------+-----------+\n| Standard XL (m1.xlarge)           | $0.00/hr   | $0.53/hr  | $0.53/hr  |\n+-----------------------------------+------------+-----------+-----------+\n| High-Memory 2XL (m2.2xlarge)      | $0.00/hr   | $0.845/hr | $0.845/hr |\n+-----------------------------------+------------+-----------+-----------+\n| High-Memory 4XL (m2.4xlarge)      | $0.00/hr   | $1.69/hr  | $1.69/hr  |\n+-----------------------------------+------------+-----------+-----------+\n| M3 Extra Large (m3.xlarge)        | $0.00/hr   | $0.475/hr | $0.475/hr |\n+-----------------------------------+------------+-----------+-----------+\n| M3 Double Extra Large (m3.2xlarge | ) $0.00/hr | $0.95/hr  | $0.95/hr  |\n+-----------------------------------+------------+-----------+-----------+\nNon-table text:\n Pricing Details\n For region US East (Virginia)\n Hourly Fees\n Total hourly fees will vary by instance type and EC2 region.'

## Cloud

In [12]:
cloud.head(2)

,Unnamed: 0.1,Unnamed: 0,title,body,tags,link,score,creation_date,answer_count,comments,answers,selected_answer,images
0,0,33283,Some recently changed resources are not yet pu...,\r\n \r\nEvery once in a while ...,"['java', 'eclipse', 'google-app-engine', 'java...",https://stackoverflow.com/questions/49711724/s...,4,2018-04-07 20:34:12Z,1,"[""@code511788465541441, if you consider Chanse...",[{'body': '\n \nIf that happens...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,1,34179,FAILED TO INITIALIZE RUN FROM PACKAGE.txt,\r\n \r\nOur pipeline indicates...,"['azure-web-app-service', 'azure-deployment', ...",https://stackoverflow.com/questions/65255839/f...,7,2020-12-11 17:20:22Z,2,"[""thanks for the hint. i am going to verify th...","[{'body': ""\nI am almost certain that the pack...",\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

## Processed

In [13]:
cloud=cloud[['title','body','selected_answer','images']]

In [14]:
cloud.head(2)

,title,body,selected_answer,images
0,Some recently changed resources are not yet pu...,\r\n \r\nEvery once in a while ...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,FAILED TO INITIALIZE RUN FROM PACKAGE.txt,\r\n \r\nOur pipeline indicates...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

In [15]:
cloud['context'] = "title: " + cloud['title'].astype(str) + "\nbody: " + cloud['body'].astype(str).str.strip()

In [16]:
cloud_processed=pd.DataFrame(
    {
        'context':cloud['context'],
        'gt':cloud['selected_answer'],
        'img':cloud['images']
    }
)

In [17]:
cloud_processed['ocr']=cloud_test_ocr_response_format

In [18]:
cloud_processed.head(2)

,context,gt,img,ocr
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],img0:\nNon-table text:\n Stale resources dete...
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",img0:\nTables:\nTable 0:\n+----+--------------...

## Device

In [19]:
device.head(2)

,Unnamed: 0,title,body,tags,link,score,creation_date,answer_count,comments,answers,selected_answer,images
0,0,What is the purpose of the INPUT chain in the ...,\r\n \r\nWhat is the purpose of...,"['linux', 'iptables', 'linux', 'iptables']",https://serverfault.com/questions/993878/what-...,1,2019-12-01 00:23:16Z,1,"['OK, also please add this to your answer so o...",[{'body': '\nIf some NAT operation needs to be...,\r\nIf some NAT operation needs to be only don...,['https://i.sstatic.net/NUh2k.png']
1,1,"Logstash JDBC input, filter event timestamp di...",\r\n \r\nI am trying to change ...,"['elasticsearch', 'logstash', 'elastic-stack',...",https://stackoverflow.com/questions/33787795/l...,0,2015-11-18 18:38:40Z,3,"['could you suggest how I could fix?', 'Your d...",[{'body': '\nOK I finally figure how to get th...,\r\nOK I finally figure how to get the @timest...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

## Processed

In [20]:
device=device[['title','body','selected_answer','images']]

In [21]:
device.head(2)

,title,body,selected_answer,images
0,What is the purpose of the INPUT chain in the ...,\r\n \r\nWhat is the purpose of...,\r\nIf some NAT operation needs to be only don...,['https://i.sstatic.net/NUh2k.png']
1,"Logstash JDBC input, filter event timestamp di...",\r\n \r\nI am trying to change ...,\r\nOK I finally figure how to get the @timest...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

In [22]:
device['context'] = "title: " + device['title'].astype(str) + "\nbody: " + device['body'].astype(str).str.strip()

In [23]:
device_processed=pd.DataFrame(
    {
        'context':device['context'],
        'gt':device['selected_answer'],
        'img':device['images']
    }
)

In [24]:
device_processed['ocr']=device_test_ocr_response_format

In [25]:
device_processed.head(2)

,context,gt,img,ocr
0,title: What is the purpose of the INPUT chain ...,\r\nIf some NAT operation needs to be only don...,['https://i.sstatic.net/NUh2k.png'],img0:\nNon-table text:\n CT\n ...
1,"title: Logstash JDBC input, filter event times...",\r\nOK I finally figure how to get the @timest...,"['https://i.sstatic.net/3nAZ9.png', 'https://i...",img0:\nTables:\nTable 0:\n+-------------------...

# Prompt

## Cloud

### Zero Shot

In [26]:
zero_shot = '''
You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
{}

Question:
{}

Answer:

'''

In [27]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['ocr'],row['context'])

cloud_processed['zero-shot-question'] = cloud_processed.apply(generate_zero_shot_prompt, axis=1)

In [28]:
print(cloud_processed['zero-shot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
  Stale resources detected
                                                 ×
                                                 x
     Some recently changed resources are not yet published. Continue with launch?
 ?
                                             No
                                   Yes

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Answer:

### CoT

In [29]:
cot = '''
You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
{}

Question:
{}

Lets think step by step:
Answer:
'''

In [30]:
def generate_cot_prompt(row):
    return cot.format(row['ocr'],row['context'])

cloud_processed['cot-question'] = cloud_processed.apply(generate_cot_prompt, axis=1)

In [31]:
print(cloud_processed['cot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
  Stale resources detected
                                                 ×
                                                 x
     Some recently changed resources are not yet published. Continue with launch?
 ?
                                             No
                                   Yes

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Lets think step by step:
Answer:

In [32]:
cloud_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1568 entries, 0 to 1567
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   context             1568 non-null   object
 1   gt                  1568 non-null   object
 2   img                 1568 non-null   object
 3   ocr                 1568 non-null   object
 4   zero-shot-question  1568 non-null   object
 5   cot-question        1568 non-null   object
dtypes: object(6)
memory usage: 73.6+ KB

## Device

### Zero Shot

In [33]:
zero_shot = '''
You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
{}

Question:
{}

Answer:

'''

In [34]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['ocr'],row['context'])

device_processed['zero-shot-question'] =device_processed.apply(generate_zero_shot_prompt, axis=1)

In [35]:
print(device_processed['zero-shot-question'][0])

You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
       CT
                                                                                              iptables
                                                                                                                                                                              Transmit Packet to
Data Link Layer
outbound interface
              Tracked by ConnTrack
                                               Receive Packet from
Data Link Layer
inbound interface
                                                                                              raw table
PREROUTING chain
                                                                              Defrag
                                                                                                                                      Routing
                                                                                                         CT
                                                                                              mangle table
PREROUTING chain
                                                                                                                                                                     CT
              Host Inbound Firewall
                                                                                                                                                                                                       Translate w
ConnTrack's
History
                                                                                                                                                                                 SNAT
                                                                                                                                                        nat table
POSTROUTING chain
                                                                                            Is
this packet
a part of an existing
connection
                                                                                                                      Yes
                                                                                       No
                               mangle table
INPUT chain
                                                                                                       ?
                                                                                                                                                                             Is
this packet
a part of an existing
connection
                                                                                                                                          mangle table
FORWARD chain
                               filter table
INPUT chain
V
security table
INPUT chain
                                                                                                                    Translate w
ConnTrack's
History
                                                                            nat table
PREROUTING chain
                                                                                                                                                                      No
                                                                                                                                                                                                        Yes
                                                                                                                                          filter table
FORWARD chain
V
security table
FORWARD chain
                                                                                                                                                                                        ?
                               nat table
INPUT chain
                                                                                                                                                                             mangle table
POSTROUTING chain
                                                                                                  Is this host
the final
destination?
                                                                                       Yes
                                                                                                                      No
                                      CT
                                                                                                                   Drop
Packet
                                                                                                                                                                   Yes
                                                                                                                                 No
                                                                                                                                       Is this packet routable?
                            Network Socket
(Host Application)
                                                                              Host Outbound Firewall
                                                                                                                                                                               security table
OUTPUT chain
                                                                                 mangle table
OUTPUT chain
                                                                                                                                                filter table
OUTPUT chain
                                                                                                                nat table
OUTPUT chain
                                                 raw table
OUTPUT chain
   Packet from
Network Socket
                                                                      CT
                             Defrag

Question:
title: What is the purpose of the INPUT chain in the nat table?
body: What is the purpose of the INPUT chain in the nat table ?

The PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".

The nat:INPUT and nat:PREROUTING chains seem redundant.

What would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?

Answer:

### CoT

In [36]:
cot = '''
You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
{}

Question:
{}

Lets think step by step:
Answer:
'''

In [37]:
def generate_cot_prompt(row):
    return cot.format(row['ocr'],row['context'])

device_processed['cot-question'] = device_processed.apply(generate_cot_prompt, axis=1)

In [38]:
print(device_processed['cot-question'][0])

You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
       CT
                                                                                              iptables
                                                                                                                                                                              Transmit Packet to
Data Link Layer
outbound interface
              Tracked by ConnTrack
                                               Receive Packet from
Data Link Layer
inbound interface
                                                                                              raw table
PREROUTING chain
                                                                              Defrag
                                                                                                                                      Routing
                                                                                                         CT
                                                                                              mangle table
PREROUTING chain
                                                                                                                                                                     CT
              Host Inbound Firewall
                                                                                                                                                                                                       Translate w
ConnTrack's
History
                                                                                                                                                                                 SNAT
                                                                                                                                                        nat table
POSTROUTING chain
                                                                                            Is
this packet
a part of an existing
connection
                                                                                                                      Yes
                                                                                       No
                               mangle table
INPUT chain
                                                                                                       ?
                                                                                                                                                                             Is
this packet
a part of an existing
connection
                                                                                                                                          mangle table
FORWARD chain
                               filter table
INPUT chain
V
security table
INPUT chain
                                                                                                                    Translate w
ConnTrack's
History
                                                                            nat table
PREROUTING chain
                                                                                                                                                                      No
                                                                                                                                                                                                        Yes
                                                                                                                                          filter table
FORWARD chain
V
security table
FORWARD chain
                                                                                                                                                                                        ?
                               nat table
INPUT chain
                                                                                                                                                                             mangle table
POSTROUTING chain
                                                                                                  Is this host
the final
destination?
                                                                                       Yes
                                                                                                                      No
                                      CT
                                                                                                                   Drop
Packet
                                                                                                                                                                   Yes
                                                                                                                                 No
                                                                                                                                       Is this packet routable?
                            Network Socket
(Host Application)
                                                                              Host Outbound Firewall
                                                                                                                                                                               security table
OUTPUT chain
                                                                                 mangle table
OUTPUT chain
                                                                                                                                                filter table
OUTPUT chain
                                                                                                                nat table
OUTPUT chain
                                                 raw table
OUTPUT chain
   Packet from
Network Socket
                                                                      CT
                             Defrag

Question:
title: What is the purpose of the INPUT chain in the nat table?
body: What is the purpose of the INPUT chain in the nat table ?

The PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".

The nat:INPUT and nat:PREROUTING chains seem redundant.

What would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?

Lets think step by step:
Answer:

In [39]:
device_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 947 entries, 0 to 946
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   context             947 non-null    object
 1   gt                  947 non-null    object
 2   img                 947 non-null    object
 3   ocr                 947 non-null    object
 4   zero-shot-question  947 non-null    object
 5   cot-question        947 non-null    object
dtypes: object(6)
memory usage: 44.5+ KB

## Prompt Length

In [40]:
# extract prompt length
def prompt_length(text, add_special_tokens=True):
    if pd.isnull(text) or not isinstance(text, str) or not text.strip():
        return 0
    temp_inputs = tokenizer(text, return_tensors="pt", add_special_tokens=add_special_tokens)
    return temp_inputs.input_ids.shape[1]

In [41]:
# Prompt Length -> Cloud Logs
cloud_processed['zero-shot-question-length'] = cloud_processed['zero-shot-question'].apply(prompt_length)
cloud_processed['cot-question-length'] = cloud_processed['cot-question'].apply(prompt_length)

In [42]:
# Prompt Length -> Device Logs
device_processed['zero-shot-question-length'] = device_processed['zero-shot-question'].apply(prompt_length)
device_processed['cot-question-length'] = device_processed['cot-question'].apply(prompt_length)

# Generate Response

In [43]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

### Zero-Shot

In [72]:
import os
import torch
import gc
import traceback

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"
torch.set_grad_enabled(False)

torch.manual_seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

def generate_zero_shot_answer(row):
    try:
        # Encode the question and move to the model’s device
        input_ids = tokenizer(
            row["zero-shot-question"], return_tensors="pt"
        ).input_ids.to(model.device)
        prompt_length=input_ids.shape[1]

        # Generate a completion
        output = model.generate(
            input_ids,
            max_new_tokens=768,
            repetition_penalty=1.2,
            do_sample=False,
            use_cache=True
        )

        # Decode and return the answer only
        return tokenizer.decode(output[0][prompt_length:], skip_special_tokens=True)

    except Exception as e:
        # Return the error string (no prompt info)
        return f"[ERROR] {e}\n{traceback.format_exc()}"

    finally:
        # Clean up GPU / RAM
        for var in ("input_ids", "output"):
            if var in locals():
                del locals()[var]
        torch.cuda.empty_cache()
        gc.collect()

### CoT

In [73]:
import os
import torch
import gc
import traceback

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"
torch.set_grad_enabled(False)

torch.manual_seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

def generate_cot_answer(row):
    try:
        input_ids = tokenizer(
            row["cot-question"], return_tensors="pt"
        ).input_ids.to(model.device)
        prompt_length=input_ids.shape[1]

        output = model.generate(
            input_ids,
            max_new_tokens=768,
            repetition_penalty=1.2,
            do_sample=False,
            use_cache=True,
        )

        return tokenizer.decode(output[0][prompt_length:], skip_special_tokens=True)

    except Exception as e:
        return f"[ERROR] {e}\n{traceback.format_exc()}"

    finally:
        for var in ("input_ids", "output"):
            if var in locals():
                del locals()[var]
        torch.cuda.empty_cache()
        gc.collect()

## Testing Samples

In [46]:
sample = cloud_processed.sort_values('zero-shot-question-length', ascending=False).head(3).reset_index(drop=True)

In [63]:
sample =cloud_processed[0:15]

In [64]:
sample.head(2)

,context,gt,img,ocr,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],img0:\nNon-table text:\n Stale resources dete...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,169,175
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",img0:\nTables:\nTable 0:\n+----+--------------...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,3016,3022

In [65]:
print(sample['zero-shot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
  Stale resources detected
                                                 ×
                                                 x
     Some recently changed resources are not yet published. Continue with launch?
 ?
                                             No
                                   Yes

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Answer:

In [66]:
zero_results = []
failed_responses = []
jsonl_records = []

output_file="llm_ocr_sample_llama_3_1_8b_instruct_zero_shot_results.jsonl"
failed_file="llm_ocr_sample_llama_3_1_8b_instruct_zero_shot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass

for idx, row in tqdm(sample.iterrows(), total=len(sample)):
    answer = generate_zero_shot_answer(row)

    # Track response
    zero_results.append(answer)

    # Sample print preview
    if idx == 0:
        question_text = row['zero-shot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Question:\n")
        print(short_question)

        print("\n\nSample Response:\n")
        print(answer)

    # JSONL record
    record = {
        "row": idx,
        "question": row["zero-shot-question"],
        "response": answer
    }

    jsonl_records.append(record)
    
    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
             f.write(json.dumps(failed_responses) + "\n")
    

# Add generated answers to DataFrame
sample["zero-shot-generated-answer"] = zero_results

  0%|          | 0/15 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  7%|▋         | 1/15 [00:04<00:57,  4.09s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Sample Question:


You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text


Sample Response:

This is likely due to stale resources being used by your Google App Engine (GAE) server. When you make changes to your code or configuration, it may take some time for these changes to be reflected in the deployed application. Clicking 'Yes' will allow the deployment process to continue using outdated resources, resulting in running your app with old code. To resolve this issue, try checking if there are any pending updates or changes that need to be applied before redeploying your app. You can also consider increasing the timeout period for resource synchronization or adjusting your development environment settings to ensure that all changes are properly synchronized before deploying. Additionally, verifying that your Eclipse setup is up-to-date and configured correctly might help alleviate this problem.

Note: The provided OCR text does not contain enough context about the specific situation or steps taken prior to encountering the error message. Therefore, the response focuses on general troubleshooting strategies related to stale resources and deployment issues in GAE.  Suggested actions include checking for pending updates, adjusting timeouts, ensuring proper synchronization of changes, and verifying Eclipse setup. These suggestions aim to address potential root causes without requiring additional details from the original poster.  However, further clarification would be beneficial for providing more tailored advice.

 13%|█▎        | 2/15 [00:14<01:43,  7.98s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 20%|██        | 3/15 [00:18<01:10,  5.86s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 27%|██▋       | 4/15 [00:21<00:53,  4.89s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 33%|███▎      | 5/15 [00:24<00:41,  4.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 40%|████      | 6/15 [00:30<00:42,  4.74s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 47%|████▋     | 7/15 [00:32<00:31,  3.92s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 53%|█████▎    | 8/15 [00:35<00:25,  3.71s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 60%|██████    | 9/15 [00:40<00:24,  4.09s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 67%|██████▋   | 10/15 [00:43<00:18,  3.71s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 73%|███████▎  | 11/15 [00:47<00:15,  3.77s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 80%|████████  | 12/15 [00:51<00:11,  3.76s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 87%|████████▋ | 13/15 [00:55<00:07,  4.00s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 93%|█████████▎| 14/15 [01:00<00:04,  4.13s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
100%|██████████| 15/15 [01:06<00:00,  4.41s/it]
/tmp/ipykernel_117/2873790280.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample["zero-shot-generated-answer"] = zero_results

In [71]:
print(zero_results[7])

To get the cost for each Azure Function within the Azure Function App, you can use the Azure Monitor or Azure Log Analytics tools. These services provide detailed insights into your resource usage and costs at a granular level.

In Azure Monitor, navigate to **Function Apps** > select your Function App > click on **Metrics**. Then, apply filters as needed to view specific data points such as **FunctionExecutionCount**, **FunctionExecutionUnits**, etc., grouped by individual functions.

Alternatively, using Azure Log Analytics, create a query that aggregates costs per function instance, e.g., `AzureDiagnostics | where Category == 'Functions' | summarize sum(Quantity) by Resource = functionName`.

By leveraging these tools, you'll be able to identify which Azure Functions contribute most significantly to your overall expenses, enabling informed decisions about optimizing resources and reducing unnecessary costs. No additional setup is required beyond accessing these built-in features of Azure Monitoring Services.

In [74]:
import json
from tqdm import tqdm

cot_results = []
failed_cot_responses = []
cot_jsonl_records = []

output_file="llm_ocr_sample_llama_3_1_8b_instruct_cot_results.jsonl"
failed_file="llm_ocr_sample_llama_3_1_8b_instruct_cot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass


for idx, row in tqdm(sample.iterrows(), total=len(sample)):
    answer = generate_cot_answer(row)

    # Append result
    cot_results.append(answer)

    # Show sample only for first entry
    if idx == 0:
        question_text = row['cot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample CoT Question:\n")
        print(short_question)

        print("\n\nSample CoT Response:\n")
        print(answer)

    # Record for JSONL
    record = {
        "index": idx,
        "question": row["cot-question"],
        "response": answer
    }
    jsonl_records.append(record)
    
    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
            f.write(json.dumps(record) + "\n")
    


# Add generated CoT answers to DataFrame
sample["cot-generated-answer"] = cot_results

  0%|          | 0/15 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  7%|▋         | 1/15 [00:01<00:27,  1.94s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Sample CoT Question:


You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text


Sample CoT Response:

This is likely due to stale resources being used during deployment. When you see the prompt about some recently changed resources not being published, clicking 'Yes' will deploy your application using those stale resources instead of recompiling them. To resolve this, try invalidating the cache (cleaning) or use the `--clear_datastore` flag when deploying. This should ensure that fresh resources are used for deployment. Additionally, consider setting up automatic publishing of changes through Eclipse's settings. This way, whenever you make changes, they'll be automatically reflected without needing manual intervention.

 13%|█▎        | 2/15 [00:08<01:00,  4.62s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 20%|██        | 3/15 [00:12<00:53,  4.45s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 27%|██▋       | 4/15 [00:19<01:00,  5.54s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 33%|███▎      | 5/15 [00:24<00:53,  5.33s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 40%|████      | 6/15 [00:30<00:48,  5.44s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 47%|████▋     | 7/15 [00:33<00:36,  4.55s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 53%|█████▎    | 8/15 [00:44<00:47,  6.73s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 60%|██████    | 9/15 [00:50<00:38,  6.46s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 67%|██████▋   | 10/15 [00:54<00:29,  5.84s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 73%|███████▎  | 11/15 [00:57<00:19,  4.96s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 80%|████████  | 12/15 [01:02<00:14,  4.79s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 87%|████████▋ | 13/15 [01:08<00:10,  5.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 93%|█████████▎| 14/15 [01:13<00:05,  5.11s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
100%|██████████| 15/15 [01:20<00:00,  5.40s/it]
/tmp/ipykernel_117/3151197572.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample["cot-generated-answer"] = cot_results

In [79]:
print(cot_results[5])

Based on your description of the issue, it seems that the problem lies within how you're interacting with the UI rather than any underlying configuration or permissions issues. You mentioned that when you right-click and inspect the HTML, changing the value for the 'Hosted' option to match the ID of the missing 'Default' queue allows you to see both options. This suggests that there might be some sort of rendering or display issue at play here.



However, without more detailed error messages or logs from either the client-side (Visual Studio) or server-side (VSTS), it's difficult to pinpoint exactly what could cause such behavior.



Given your update where installing a fresh build agent on a different environment resolves the issue, it implies that something specific to your original setup may have caused the discrepancy between what was displayed in the UI versus actual available pools.



To troubleshoot further:

* Check if there were any errors logged during the installation process of the initial build agent.
* Verify whether the original build agent was properly registered and recognized by VSTS.
* Consider reinstalling the original build agent under the same conditions to see if the issue persists.
* If possible, try reproducing the issue on another machine or environment to isolate potential factors contributing to the discrepancy.



In terms of immediate solutions, considering your constraints against using hosted agents due to Unity support limitations, having a dedicated physical or virtual machine specifically set aside for hosting your own build agent seems to be the most viable path forward until you can identify and resolve whatever led to the discrepancy initially observed.

In [ ]:
sample.to_csv("sample_llm_ocr_llama_3_1_8b_instruct.csv")

## Cloud Testset

In [80]:
cloud_testset=cloud_processed

In [81]:
cloud_testset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1568 entries, 0 to 1567
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   context                    1568 non-null   object
 1   gt                         1568 non-null   object
 2   img                        1568 non-null   object
 3   ocr                        1568 non-null   object
 4   zero-shot-question         1568 non-null   object
 5   cot-question               1568 non-null   object
 6   zero-shot-question-length  1568 non-null   int64
 7   cot-question-length        1568 non-null   int64
dtypes: int64(2), object(6)
memory usage: 98.1+ KB

In [82]:
cloud_testset.head(2)

,context,gt,img,ocr,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],img0:\nNon-table text:\n Stale resources dete...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,169,175
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",img0:\nTables:\nTable 0:\n+----+--------------...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,3016,3022

### zero shot response

In [83]:
import json
from tqdm import tqdm

zero_cloud_results = []
zero_cloud_jsonl_records = []
zero_cloud_failed_responses = []

output_file="llm_ocr_cloud_llama_3_1_8b_instruct_zero_shot_results.jsonl"
failed_file="llm_ocr_cloud_llama_3_1_8b_instruct_zero_shot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass

for idx, row in tqdm(cloud_testset.iterrows(), total=len(cloud_testset)):
    # Generate answer
    answer = generate_zero_shot_answer(row)
    zero_cloud_results.append(answer)

    # Show the first response as a sample
    if idx == 0:
        question_text = row['zero-shot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Cloud Zero-Shot Question:\n")
        print(short_question)

        print("\n\nSample Cloud Zero-Shot Response:\n")
        print(answer)

    # Prepare JSONL record
    record = {
        "row": idx,
        "question": row["zero-shot-question"],
        "response": answer
    }
    zero_cloud_jsonl_records.append(record)

    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
          f.write(json.dumps(record) + "\n")

# Save results in the DataFrame
cloud_testset["zero-shot-generated-answer"] = zero_cloud_results

  0%|          | 0/1568 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 1/1568 [00:04<1:47:25,  4.11s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Sample Cloud Zero-Shot Question:


You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text


Sample Cloud Zero-Shot Response:

This is likely due to stale resources being used by your Google App Engine (GAE) server. When you make changes to your code or configuration, it may take some time for these changes to be reflected in the deployed application. Clicking 'Yes' will allow the deployment process to continue using outdated resources, resulting in running your app with old code. To resolve this issue, try checking if there are any pending updates or changes that need to be applied before redeploying your app. You can also consider increasing the timeout period for resource synchronization or adjusting your development environment settings to ensure that all changes are properly synchronized before deploying. Additionally, verifying that your Eclipse setup is up-to-date and configured correctly might help alleviate this problem.

Note: The provided OCR text does not contain enough context about the specific situation or steps taken prior to encountering the error message. Therefore, the response focuses on general troubleshooting strategies related to stale resources and deployment issues in GAE.  Suggested actions include checking for pending updates, adjusting timeouts, ensuring proper synchronization of changes, and verifying Eclipse setup. These suggestions aim to address potential root causes without requiring additional details from the original poster.  However, further clarification would be beneficial for providing more tailored advice.

  0%|          | 2/1568 [00:14<3:28:40,  8.00s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 3/1568 [00:18<2:32:49,  5.86s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 4/1568 [00:21<2:07:18,  4.88s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 5/1568 [00:24<1:49:12,  4.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 6/1568 [00:30<2:03:27,  4.74s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 7/1568 [00:32<1:42:02,  3.92s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 8/1568 [00:35<1:36:29,  3.71s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 9/1568 [00:40<1:46:01,  4.08s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 10/1568 [00:43<1:36:15,  3.71s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 11/1568 [00:47<1:37:33,  3.76s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 12/1568 [00:51<1:37:09,  3.75s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 13/1568 [00:55<1:43:28,  3.99s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 14/1568 [01:00<1:46:57,  4.13s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 15/1568 [01:06<2:01:25,  4.69s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 16/1568 [01:15<2:36:15,  6.04s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 17/1568 [01:18<2:13:23,  5.16s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 18/1568 [01:22<2:03:46,  4.79s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 19/1568 [01:26<1:55:15,  4.46s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|▏         | 20/1568 [01:28<1:36:06,  3.73s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|▏         | 21/1568 [01:29<1:21:15,  3.15s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|▏         | 22/1568 [01:34<1:30:55,  3.53s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|▏         | 23/1568 [01:40<1:50:23,  4.29s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 24/1568 [01:42<1:34:51,  3.69s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 25/1568 [01:44<1:18:16,  3.04s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 26/1568 [01:54<2:16:23,  5.31s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 27/1568 [02:00<2:22:17,  5.54s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 28/1568 [02:02<1:53:35,  4.43s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 29/1568 [02:06<1:51:24,  4.34s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 30/1568 [02:15<2:23:23,  5.59s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 31/1568 [02:24<2:50:07,  6.64s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 32/1568 [02:29<2:38:39,  6.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 33/1568 [02:33<2:17:36,  5.38s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 34/1568 [02:37<2:09:12,  5.05s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 35/1568 [02:42<2:07:28,  4.99s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 36/1568 [02:45<1:56:43,  4.57s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 37/1568 [02:52<2:09:45,  5.09s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 38/1568 [02:58<2:16:04,  5.34s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 39/1568 [03:01<2:00:59,  4.75s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 40/1568 [03:03<1:43:25,  4.06s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 41/1568 [03:07<1:41:34,  3.99s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 42/1568 [03:14<2:06:20,  4.97s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 43/1568 [03:18<1:53:08,  4.45s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 44/1568 [03:20<1:33:21,  3.68s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 45/1568 [03:27<2:03:08,  4.85s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 46/1568 [03:32<2:03:07,  4.85s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 47/1568 [03:40<2:24:24,  5.70s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 48/1568 [03:47<2:35:33,  6.14s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 49/1568 [03:54<2:42:28,  6.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 50/1568 [03:57<2:19:07,  5.50s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 51/1568 [04:00<2:01:41,  4.81s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 52/1568 [04:08<2:18:50,  5.50s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 53/1568 [04:14<2:23:04,  5.67s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 54/1568 [04:17<2:08:56,  5.11s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▎         | 55/1568 [04:20<1:47:35,  4.27s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▎         | 56/1568 [04:25<1:53:20,  4.50s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▎         | 57/1568 [04:29<1:50:17,  4.38s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▎         | 58/1568 [04:38<2:27:00,  5.84s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 59/1568 [04:41<2:05:08,  4.98s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 60/1568 [04:49<2:26:04,  5.81s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 61/1568 [05:03<3:32:12,  8.45s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 62/1568 [05:11<3:25:57,  8.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 63/1568 [05:16<3:03:44,  7.32s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 64/1568 [05:20<2:32:45,  6.09s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 65/1568 [05:25<2:26:27,  5.85s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 66/1568 [05:29<2:10:36,  5.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 67/1568 [05:35<2:22:01,  5.68s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [84]:
cloud_testset.head(2)

,context,gt,img,ocr,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero-shot-generated-answer
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],img0:\nNon-table text:\n Stale resources dete...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,169,175,This is likely due to stale resources being us...
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",img0:\nTables:\nTable 0:\n+----+--------------...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,3016,3022,"Based on your description, it seems like there..."

In [85]:
cloud_testset.to_excel("../../../outputs/responses/baselines/llm_ocr/cloud/llm_ocr_response_cloud_llama_3_1_8b_instruct_zero_shot.xlsx", index=False)

### Cot Response

In [ ]:
import json
from tqdm import tqdm

cot_cloud_results = []
failed_cloud_cot_responses = []
cot_cloud_jsonl_records = []

output_file="llm_ocr_cloud_llama_3_1_8b_instruct_cot_results.jsonl"
failed_file="llm_ocr_cloud_llama_3_1_8b_instruct_cot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass


for idx, row in tqdm(cloud_testset.iterrows(), total=len(cloud_testset)):
    # Generate answer using CoT function
    answer = generate_cot_answer(row)
    cot_cloud_results.append(answer)

    # Sample output (first only)
    if idx == 0:
        question_text = row['cot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Cloud CoT Question:\n")
        print(short_question)

        print("\n\nSample Cloud CoT Response:\n")
        print(answer)

    # Prepare JSONL entry
    record = {
        "row": idx,
        "question": row["cot-question"],
        "response": answer
    }
    cot_cloud_jsonl_records.append(record)
    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
            f.write(json.dumps(record) + "\n")

# Append column to DataFrame
cloud_testset["cot-generated-answer"] = cot_cloud_results

  0%|          | 0/1568 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 1/1568 [00:01<50:00,  1.91s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Sample Cloud CoT Question:


You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text


Sample Cloud CoT Response:

This is likely due to stale resources being used during deployment. When you see the prompt about some recently changed resources not being published, clicking 'Yes' will deploy your application using those stale resources instead of recompiling them. To resolve this, try invalidating the cache (cleaning) or use the `--clear_datastore` flag when deploying. This should ensure that fresh resources are used for deployment. Additionally, consider setting up automatic publishing of changes through Eclipse's settings. This way, whenever you make changes, they'll be automatically reflected without needing manual intervention.

  0%|          | 2/1568 [00:08<1:59:46,  4.59s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 3/1568 [00:12<1:55:29,  4.43s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 4/1568 [00:19<2:24:47,  5.55s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 5/1568 [00:24<2:19:17,  5.35s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 6/1568 [00:30<2:22:37,  5.48s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 7/1568 [00:33<1:59:02,  4.58s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 8/1568 [00:44<2:55:34,  6.75s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 9/1568 [00:50<2:48:22,  6.48s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 10/1568 [00:55<2:32:03,  5.86s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 11/1568 [00:58<2:09:50,  5.00s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 12/1568 [01:02<2:04:43,  4.81s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 13/1568 [01:08<2:15:36,  5.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 14/1568 [01:13<2:13:23,  5.15s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 15/1568 [01:21<2:32:28,  5.89s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 16/1568 [01:26<2:27:38,  5.71s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 17/1568 [01:30<2:15:56,  5.26s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 18/1568 [01:35<2:10:40,  5.06s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 19/1568 [01:43<2:33:15,  5.94s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|▏         | 20/1568 [01:45<2:05:01,  4.85s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|▏         | 21/1568 [01:47<1:40:49,  3.91s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|▏         | 22/1568 [01:50<1:31:09,  3.54s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|▏         | 23/1568 [01:55<1:44:01,  4.04s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 24/1568 [01:56<1:25:47,  3.33s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 25/1568 [02:01<1:36:53,  3.77s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 26/1568 [02:07<1:48:31,  4.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 27/1568 [02:20<2:58:46,  6.96s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 28/1568 [02:28<3:05:04,  7.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 29/1568 [02:33<2:50:32,  6.65s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 30/1568 [02:39<2:45:22,  6.45s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 31/1568 [02:54<3:47:51,  8.89s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 32/1568 [02:59<3:19:13,  7.78s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 33/1568 [03:03<2:50:24,  6.66s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 34/1568 [03:09<2:48:21,  6.59s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 35/1568 [03:15<2:40:28,  6.28s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 36/1568 [03:20<2:31:34,  5.94s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 37/1568 [03:30<3:00:20,  7.07s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 38/1568 [03:39<3:14:41,  7.63s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 39/1568 [03:43<2:50:38,  6.70s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 40/1568 [03:46<2:22:17,  5.59s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 41/1568 [03:49<2:03:09,  4.84s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 42/1568 [03:55<2:12:43,  5.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 43/1568 [04:02<2:20:30,  5.53s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 44/1568 [04:10<2:44:50,  6.49s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 45/1568 [04:21<3:19:32,  7.86s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 46/1568 [04:27<2:59:01,  7.06s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 47/1568 [04:35<3:06:46,  7.37s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 48/1568 [04:40<2:53:55,  6.87s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 49/1568 [04:46<2:44:06,  6.48s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 50/1568 [04:59<3:34:04,  8.46s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 51/1568 [05:09<3:48:28,  9.04s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 52/1568 [05:13<3:05:53,  7.36s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 53/1568 [05:18<2:51:28,  6.79s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 54/1568 [05:24<2:46:57,  6.62s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▎         | 55/1568 [05:40<3:53:08,  9.25s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▎         | 56/1568 [05:47<3:39:52,  8.73s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▎         | 57/1568 [05:56<3:39:16,  8.71s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▎         | 58/1568 [06:04<3:31:11,  8.39s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 59/1568 [06:13<3:41:24,  8.80s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 60/1568 [06:19<3:17:07,  7.84s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 61/1568 [06:23<2:46:58,  6.65s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 62/1568 [06:31<3:01:21,  7.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 63/1568 [06:37<2:50:52,  6.81s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 64/1568 [06:42<2:33:01,  6.10s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 65/1568 [06:48<2:34:45,  6.18s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 66/1568 [06:51<2:12:20,  5.29s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 67/1568 [06:56<2:08:46,  5.15s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [ ]:
cloud_testset.head(2)

In [ ]:
cloud_testset.to_excel("../../../outputs/responses/baselines/llm_ocr/cloud/llm_ocr_response_cloud_llama_3_1_8b_instruct_cot.xlsx", index=False)

## Device Testset

In [ ]:
device_testset=device_processed

In [ ]:
device_testset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1021 entries, 0 to 1020
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   context                    1021 non-null   object
 1   gt                         1021 non-null   object
 2   zero-shot-question         1021 non-null   object
 3   cot-question               1021 non-null   object
 4   zero-shot-question-length  1021 non-null   int64
 5   cot-question-length        1021 non-null   int64
dtypes: int64(2), object(4)
memory usage: 48.0+ KB

In [ ]:
device_testset.shape

(1021, 6)

### Zero shot Response

In [ ]:
import json
from tqdm import tqdm

# Lists for tracking
zero_device_results = []
zero_device_jsonl_records = []
zero_device_failed_responses = []

output_file="llm_ocr_device_llama_3_1_8b_instruct_zero_shot_results.jsonl"
failed_file="llm_ocr_device_llama_3_1_8b_instruct_zero_shot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass

for idx, row in tqdm(device_testset.iterrows(), total=len(device_testset)):
    # Generate zero-shot answer
    answer = generate_zero_shot_answer(row)
    zero_device_results.append(answer)

    # Print one sample preview
    if idx == 0:
        question_text = row["zero-shot-question"]
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Device Zero-Shot Question:\n")
        print(short_question)

        print("\n\nSample Device Zero-Shot Response:\n")
        print(answer)

    # Build JSONL record
    record = {
        "row": idx,
        "question": row["zero-shot-question"],
        "response": answer
    }
    zero_device_jsonl_records.append(record)

    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
            f.write(json.dumps(record) + "\n")


# Add results to DataFrame
device_testset["zero-shot-generated-answer"] = zero_device_results

  0%|          | 1/1021 [00:32<9:10:06, 32.36s/it]

Sample Question:


You are an expert device assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."

Question:
title: What is the purpose of the INPUT chain in the


Sample Response:

There isn't enough specific context or details about how your system uses NAT rules for me to provide a precise explanation on this topic without potentially causing confusion. However, I can give some general guidance based on common practices.


In Linux's Netfilter framework, which includes iptables, there are several tables and chains used for network address translation (NAT). The main goal here seems to be to understand why one might choose to specifically target the `nat:INPUT` chain when it appears similar functionality could also be achieved through other means like the `nat:PREROUTING` chain.

1. **Understanding Chain Differences**: Each chain serves different purposes within the packet processing pipeline. Understanding these differences helps determine where to place specific rules:


   - **POSTROUTING** handles outgoing traffic after routing decisions have been made; useful for SNAT (Source NAT).

   - **OUTPUT** deals with outgoing local traffic before any routing decision has been taken into account; good for source port randomization among many things.

   - **PREROUTING**, as mentioned, does DNAT (Destination NAT), essentially changing the destination IP of incoming packets.

   - **INPUT** refers to handling incoming traffic once it’s decided by the router to go to this host but right before actually reaching its final process.



2. **Specific Use Cases for INPUT vs PREROUTING Chains**: While both chains can perform DNAT, their application scenarios differ slightly due to timing considerations during packet traversal:



    * If you want to ensure certain services or ports get translated even if they're not explicitly listed under default actions in higher precedence rules, using `nat:INPUT` ensures consistency across all incoming connections regardless of protocol or service type being accessed directly from outside.

    * Another scenario involves complex setups requiring multiple translations depending on various conditions met at input stage rather than just prerouting level, suggesting more fine-grained control over how inputs are handled.

3.  **Avoiding Conflicts and Simplifying Rulesets**: Sometimes splitting tasks between two seemingly overlapping features makes sense because each rule set can focus narrowly without conflicting priorities inherent in broader rule sets.

4. **Flexibility and Future-Proofing**: Even though functionalities overlap somewhat, having options allows for better adaptability in case future requirements demand changes that wouldn’t necessitate wholesale rewrites otherwise achievable solely via single feature implementation strategies.



Given the complexity involved, providing a definitive reason for choosing `nat:INPUT` over `nat:PREROUTING` requires detailed knowledge of your specific setup, including the operating environment, existing configuration, and security policies aimed to achieve through such configurations.



To clarify further, consulting official documentation or experienced professionals familiar with your particular infrastructure will offer insights tailored precisely to those specifics beyond generic descriptions provided above.

100%|██████████| 1021/1021 [6:45:14<00:00, 23.81s/it]

In [ ]:
device_testset.head(2)

,context,gt,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero-shot-generated-answer
0,title: What is the purpose of the INPUT chain ...,\nIf some NAT operation needs to be only done ...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,144,150,There isn't enough specific context or details...
1,"title: Logstash JDBC input, filter event times...",\nOK I finally figure how to get the @timestam...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,550,556,You're experiencing issues with Logstash's `da...

In [ ]:
device_testset.to_excel("../../../outputs/responses/baselines/llm_ocr/device/llm_ocr_response_device_llama_3_1_8b_instruct_zero_shot.xlsx", index=False)

### CoT Response

In [ ]:
import json
from tqdm import tqdm

# Containers
cot_device_results = []
cot_device_jsonl_records = []
cot_device_failed_responses = []

output_file="llm_ocr_device_llama_3_1_8b_instruct_cot_results.jsonl"
failed_file="llm_ocr_device_llama_3_1_8b_instruct_cot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass

for idx, row in tqdm(device_testset.iterrows(), total=len(device_testset)):
    # Generate CoT answer
    answer = generate_cot_answer(row)
    cot_device_results.append(answer)

    # Print one sample preview
    if idx == 0:
        question_text = row["cot-question"]
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Device CoT Question:\n")
        print(short_question)

        print("\n\nSample Device CoT Response:\n")
        print(answer)

    # JSONL record
    record = {
        "row": idx,
        "question": row["cot-question"],
        "response": answer
    }
    cot_device_jsonl_records.append(record)

    with open(output_file, "a") as f:
        f.write(json.dumps(jsonl_records) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
            f.write(json.dumps(failed_responses) + "\n")

# Write results back to DataFrame
device_testset["cot-generated-answer"] = cot_device_results

  0%|          | 1/1021 [00:19<5:24:59, 19.12s/it]

Sample Question:


You are an expert device assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."
Question:
title: What is the purpose of the INPUT chain in the


Sample Response:

There's no definitive rule for using one over another; however, if your network has both source NAT and destination NAT enabled on different interfaces, then it might make sense to have two separate chains - one for each type of operation.

For example:

*   If you're performing DNAT on interface eth0 but SNAT on interface eth1, having two separate chains allows for more fine-grained control over which operations occur when packets arrive from or leave via those respective interfaces.
*   In this scenario, packets arriving at `eth0` will undergo DNAT as they pass through the prerouting chain, while SNAT occurs after packet inspection within the routing decision process before being sent out via `eth1`. The input chain can then perform additional actions based solely upon where these modified packets originated from (`eth1`). This separation enables better security controls since now we only allow traffic coming into our system directly associated with specific outgoing connections rather than indiscriminately applying rules across all types of ingress traffic.



In summary, without any clear-cut guidelines regarding whether one should utilize either or both depending strictly upon functional requirements beyond simple port-forwarding scenarios described earlier, employing multiple chains appears beneficial under complex configurations involving mixed mode translations – particularly allowing greater flexibility during troubleshooting phases due increased visibility into distinct operational contexts provided per-rule basis throughout entire firewall policy hierarchy.


Note : While there isn't anything inherently wrong about placing them together under single default setup usually seen today, utilizing dual-chain approach provides certain advantages especially pertinent situations requiring granular level management capability above standard implementation norms typically observed elsewhere making argument fairly strong albeit lacking explicit mandate supporting usage pattern itself so far discussed here.

100%|██████████| 1021/1021 [8:07:04<00:00, 28.62s/it]

In [ ]:
device_testset.head(2)

,context,gt,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero-shot-generated-answer,cot-generated-answer
0,title: What is the purpose of the INPUT chain ...,\nIf some NAT operation needs to be only done ...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,144,150,There isn't enough specific context or details...,There's no definitive rule for using one over ...
1,"title: Logstash JDBC input, filter event times...",\nOK I finally figure how to get the @timestam...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,550,556,You're experiencing issues with Logstash's `da...,The issue lies in how Logstash interprets the ...

In [ ]:
device_testset.to_excel("../../../outputs/responses/baselines/llm_ocr/device/llm_ocr_response_device_llama_3_1_8b_instruct_cot.xlsx", index=False)