# Environment

In [4]:
! pip install pandas

Collecting pandas
  Downloading pandas-2.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 2.3 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 216.5 MB/s eta 0:00:0000:010:01
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 150.3 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 kB 131.1 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.3.0 pytz-2025.2 tzdata-2025.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

In [5]:
!pip install --upgrade torch transformers accelerate pillow

Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.1.0+cu118)
Collecting torch
  Downloading torch-2.7.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting transformers
  Downloading transformers-4.52.4-py3-none-any.whl.metadata (38 kB)
Collecting accelerate
  Downloading accelerate-1.8.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (9.3.0)
Collecting pillow
  Downloading pillow-11.2.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (8.9 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.9.0)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading typing_extensions-4.14.0-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2023.4.0)
Collecting nvidia-cuda-nvrtc-cu12==12.6.77 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.6.77 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.6.80 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.5.1.17 (from torch)
  Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.6.4.1 (from torch)
  Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.3.0.4 (from torch)
  Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.7.77 (from torch)
  Downloading nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.7.1.2 (from torch)
  Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.5.4.2 (from torch)
  Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparselt-cu12==0.6.3 (from torch)
  Downloading nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.26.2 (from torch)
  Downloading nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvtx-cu12==12.6.77 (from torch)
  Downloading nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nvjitlink-cu12==12.6.85 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufile-cu12==1.11.1.6 (from torch)
  Downloading nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.3.1 (from torch)
  Downloading triton-3.3.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: setuptools>=40.8.0 in /usr/local/lib/python3.10/dist-packages (from triton==3.3.1->torch) (68.2.2)
Collecting huggingface-hub<1.0,>=0.30.0 (from transformers)
  Downloading huggingface_hub-0.33.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.24.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 20.5 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting tqdm>=4.27 (from transformers)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 33.7 MB/s eta 0:00:00
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.6)
Collecting fsspec (from torch)
  Downloading fsspec-2025.5.1-py3-none-any.whl.metadata (11 kB)
Collecting hf-xet<2.0.0,>=1.1.2 (from huggingface-hub<1.0,>=0.30.0->transformers)
  Downloading hf_xet-1.1.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (879 bytes)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2022.12.7)
Downloading torch-2.7.1-cp310-cp310-manylinux_2_28_x86_64.whl (821.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 821.2/821.2 MB 14.3 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (393.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 26.3 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 233.9 MB/s eta 0:00:0000:01
Downloading nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 193.7 MB/s eta 0:00:00a 0:00:01
Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (897 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 kB 179.6 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl (571.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.0/571.0 MB 21.0 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (200.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 60.1 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 225.3 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 148.5 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (158.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 MB 53.1 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (216.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 MB 44.2 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl (156.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.8/156.8 MB 63.2 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (201.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.3/201.3 MB 44.8 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (19.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 98.2 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.3/89.3 kB 38.3 MB/s eta 0:00:00
Downloading triton-3.3.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (155.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 MB 62.1 MB/s eta 0:00:0000:0100:01
Downloading transformers-4.52.4-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 250.4 MB/s eta 0:00:0000:01
Downloading accelerate-1.8.1-py3-none-any.whl (365 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 365.3/365.3 kB 11.4 MB/s eta 0:00:00
Downloading pillow-11.2.1-cp310-cp310-manylinux_2_28_x86_64.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 198.5 MB/s eta 0:00:00
Downloading huggingface_hub-0.33.1-py3-none-any.whl (515 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.4/515.4 kB 127.0 MB/s eta 0:00:00
Downloading fsspec-2025.5.1-py3-none-any.whl (199 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 kB 71.3 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.7/781.7 kB 154.3 MB/s eta 0:00:00
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 111.8 MB/s eta 0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 232.4 MB/s eta 0:00:00
Downloading tokenizers-0.21.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 56.7 MB/s eta 0:00:00a 0:00:01
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 24.5 MB/s eta 0:00:00
Downloading typing_extensions-4.14.0-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 15.1 MB/s eta 0:00:00
Downloading hf_xet-1.1.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 172.3 MB/s eta 0:00:00
Installing collected packages: nvidia-cusparselt-cu12, typing-extensions, triton, tqdm, sympy, safetensors, regex, pillow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, hf-xet, fsspec, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, accelerate
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.4.0
    Uninstalling typing_extensions-4.4.0:
      Successfully uninstalled typing_extensions-4.4.0
  Attempting uninstall: triton
    Found existing installation: triton 2.1.0
    Uninstalling triton-2.1.0:
      Successfully uninstalled triton-2.1.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12
    Uninstalling sympy-1.12:
      Successfully uninstalled sympy-1.12
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.3.0
    Uninstalling Pillow-9.3.0:
      Successfully uninstalled Pillow-9.3.0
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2023.4.0
    Uninstalling fsspec-2023.4.0:
      Successfully uninstalled fsspec-2023.4.0
  Attempting uninstall: torch
    Found existing installation: torch 2.1.0+cu118
    Uninstalling torch-2.1.0+cu118:
      Successfully uninstalled torch-2.1.0+cu118
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.0+cu118 requires torch==2.1.0, but you have torch 2.7.1 which is incompatible.
torchvision 0.16.0+cu118 requires torch==2.1.0, but you have torch 2.7.1 which is incompatible.
Successfully installed accelerate-1.8.1 fsspec-2025.5.1 hf-xet-1.1.5 huggingface-hub-0.33.1 nvidia-cublas-cu12-12.6.4.1 nvidia-cuda-cupti-cu12-12.6.80 nvidia-cuda-nvrtc-cu12-12.6.77 nvidia-cuda-runtime-cu12-12.6.77 nvidia-cudnn-cu12-9.5.1.17 nvidia-cufft-cu12-11.3.0.4 nvidia-cufile-cu12-1.11.1.6 nvidia-curand-cu12-10.3.7.77 nvidia-cusolver-cu12-11.7.1.2 nvidia-cusparse-cu12-12.5.4.2 nvidia-cusparselt-cu12-0.6.3 nvidia-nccl-cu12-2.26.2 nvidia-nvjitlink-cu12-12.6.85 nvidia-nvtx-cu12-12.6.77 pillow-11.2.1 regex-2024.11.6 safetensors-0.5.3 sympy-1.14.0 tokenizers-0.21.2 torch-2.7.1 tqdm-4.67.1 transformers-4.52.4 triton-3.3.1 typing-extensions-4.14.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

In [6]:
! pip install huggingface_hub

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.10/dist-packages (0.33.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (3.9.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (2025.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (6.0.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (2022.12.7)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

## Import Library

In [7]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm import tqdm
import pandas as pd
import json

# Load Model

In [8]:
! nvidia-smi

Wed Jun 25 12:05:46 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.05             Driver Version: 550.127.05     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A40                     On  |   00000000:4F:00.0 Off |                    0 |
|  0%   25C    P8             21W /  300W |       1MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [9]:
from huggingface_hub import login
import os

token = "HF_TOKEN_REDACTED"
os.environ['HF_TOKEN'] = token

login(token=token)
print("Logged in to Hugging Face!")

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Logged in to Hugging Face!

### Ministral

In [10]:
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("mistralai/Ministral-8B-Instruct-2410", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("mistralai/Ministral-8B-Instruct-2410", trust_remote_code=True)

tokenizer_config.json:   0%|          | 0.00/181k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.

config.json:   0%|          | 0.00/624 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(

model.safetensors.index.json:   0%|          | 0.00/26.9k [00:00<?, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/1.07G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

# Load Datasets

In [12]:
import pandas as pd
cloud=pd.read_excel("../../Dataset/cloud/split_data/cloud_test.xlsx")
device=pd.read_excel("../../Dataset/device/split_data/device_test.xlsx")

## Ocr Load

In [13]:
# ocr json

import json

with open("../../Ocr/extracted_data/cloud/ocr_extracted_cloud_test.jsonl", "r", encoding="utf-8") as file:
    cloud_test_ocr = [json.loads(line) for line in file]

with open("../../Ocr/extracted_data/device/ocr_extracted_device_test.jsonl", "r", encoding="utf-8") as file:
    device_test_ocr = [json.loads(line) for line in file]

In [14]:
from typing import List, Dict, Any

def ocr_extract(data) -> List[str]:
    results: List[str] = []

    for entry in data:
        lines=[]

        for img_i, img in enumerate(entry.get("images", [])):
            lines.append(f"img{img_i}:")

            for resp in img.get("response", []):
                if isinstance(resp, dict):
                    # --- non-table text ---
                    ntt = resp.get("non_table_text")
                    if ntt:
                        lines.append("Non-table text:")
                        lines.extend(ntt if isinstance(ntt, list) else [str(ntt)])

                    # --- tables ---
                    tables = resp.get("table")
                    if tables:
                        lines.append("Tables:")
                        for t_i, tbl in enumerate(tables if isinstance(tables, list) else [tables]):
                            lines.append(f"Table {t_i}:")
                            lines.append(tbl.get("content", "") if isinstance(tbl, dict) else str(tbl))
                    continue

                # Unknown or malformed type
                lines.append(f"[WARN] Unhandled response type: {type(resp).__name__}")
                lines.append(str(resp))

        formatted = "\n".join(lines).strip()
        if formatted:
            results.append(formatted)

    return results

In [15]:
# format ocr response for prompt
cloud_test_ocr_response_format = ocr_extract(cloud_test_ocr)   
device_test_ocr_response_format = ocr_extract(device_test_ocr)

In [16]:
len(cloud_test_ocr_response_format),len(device_test_ocr_response_format)

(1568, 947)

In [17]:
cloud['images'][1423]

"['https://i.sstatic.net/AKSXF.png']"

In [18]:
cloud_test_ocr_response_format[1423]

'img0:\nTables:\nTable 0:\n+-----------------------------------+------------+-----------+-----------+\n| EC2 Instance Type                 | Software   | EC2       | Total     |\n+-----------------------------------+------------+-----------+-----------+\n| Standard Large (m1.large)         | $0.00/hr   | $0.265/hr | $0.265/hr |\n+-----------------------------------+------------+-----------+-----------+\n| Standard XL (m1.xlarge)           | $0.00/hr   | $0.53/hr  | $0.53/hr  |\n+-----------------------------------+------------+-----------+-----------+\n| High-Memory 2XL (m2.2xlarge)      | $0.00/hr   | $0.845/hr | $0.845/hr |\n+-----------------------------------+------------+-----------+-----------+\n| High-Memory 4XL (m2.4xlarge)      | $0.00/hr   | $1.69/hr  | $1.69/hr  |\n+-----------------------------------+------------+-----------+-----------+\n| M3 Extra Large (m3.xlarge)        | $0.00/hr   | $0.475/hr | $0.475/hr |\n+-----------------------------------+------------+-----------+-----------+\n| M3 Double Extra Large (m3.2xlarge | ) $0.00/hr | $0.95/hr  | $0.95/hr  |\n+-----------------------------------+------------+-----------+-----------+\nNon-table text:\n Pricing Details\n For region US East (Virginia)\n Hourly Fees\n Total hourly fees will vary by instance type and EC2 region.'

## Cloud

In [19]:
cloud.head(2)

,Unnamed: 0.1,Unnamed: 0,title,body,tags,link,score,creation_date,answer_count,comments,answers,selected_answer,images
0,0,33283,Some recently changed resources are not yet pu...,\r\n \r\nEvery once in a while ...,"['java', 'eclipse', 'google-app-engine', 'java...",https://stackoverflow.com/questions/49711724/s...,4,2018-04-07 20:34:12Z,1,"[""@code511788465541441, if you consider Chanse...",[{'body': '\n \nIf that happens...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,1,34179,FAILED TO INITIALIZE RUN FROM PACKAGE.txt,\r\n \r\nOur pipeline indicates...,"['azure-web-app-service', 'azure-deployment', ...",https://stackoverflow.com/questions/65255839/f...,7,2020-12-11 17:20:22Z,2,"[""thanks for the hint. i am going to verify th...","[{'body': ""\nI am almost certain that the pack...",\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

## Processed

In [20]:
cloud=cloud[['title','body','selected_answer','images']]

In [21]:
cloud.head(2)

,title,body,selected_answer,images
0,Some recently changed resources are not yet pu...,\r\n \r\nEvery once in a while ...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,FAILED TO INITIALIZE RUN FROM PACKAGE.txt,\r\n \r\nOur pipeline indicates...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

In [22]:
cloud['context'] = "title: " + cloud['title'].astype(str) + "\nbody: " + cloud['body'].astype(str).str.strip()

In [23]:
cloud_processed=pd.DataFrame(
    {
        'context':cloud['context'],
        'gt':cloud['selected_answer'],
        'img':cloud['images']
    }
)

In [24]:
cloud_processed['ocr']=cloud_test_ocr_response_format

In [25]:
cloud_processed.head(2)

,context,gt,img,ocr
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],img0:\nNon-table text:\n Stale resources dete...
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",img0:\nTables:\nTable 0:\n+----+--------------...

## Device

In [26]:
device.head(2)

,Unnamed: 0,title,body,tags,link,score,creation_date,answer_count,comments,answers,selected_answer,images
0,0,What is the purpose of the INPUT chain in the ...,\r\n \r\nWhat is the purpose of...,"['linux', 'iptables', 'linux', 'iptables']",https://serverfault.com/questions/993878/what-...,1,2019-12-01 00:23:16Z,1,"['OK, also please add this to your answer so o...",[{'body': '\nIf some NAT operation needs to be...,\r\nIf some NAT operation needs to be only don...,['https://i.sstatic.net/NUh2k.png']
1,1,"Logstash JDBC input, filter event timestamp di...",\r\n \r\nI am trying to change ...,"['elasticsearch', 'logstash', 'elastic-stack',...",https://stackoverflow.com/questions/33787795/l...,0,2015-11-18 18:38:40Z,3,"['could you suggest how I could fix?', 'Your d...",[{'body': '\nOK I finally figure how to get th...,\r\nOK I finally figure how to get the @timest...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

## Processed

In [27]:
device=device[['title','body','selected_answer','images']]

In [28]:
device.head(2)

,title,body,selected_answer,images
0,What is the purpose of the INPUT chain in the ...,\r\n \r\nWhat is the purpose of...,\r\nIf some NAT operation needs to be only don...,['https://i.sstatic.net/NUh2k.png']
1,"Logstash JDBC input, filter event timestamp di...",\r\n \r\nI am trying to change ...,\r\nOK I finally figure how to get the @timest...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

In [29]:
device['context'] = "title: " + device['title'].astype(str) + "\nbody: " + device['body'].astype(str).str.strip()

In [30]:
device_processed=pd.DataFrame(
    {
        'context':device['context'],
        'gt':device['selected_answer'],
        'img':device['images']
    }
)

In [31]:
device_processed['ocr']=device_test_ocr_response_format

In [32]:
device_processed.head(2)

,context,gt,img,ocr
0,title: What is the purpose of the INPUT chain ...,\r\nIf some NAT operation needs to be only don...,['https://i.sstatic.net/NUh2k.png'],img0:\nNon-table text:\n CT\n ...
1,"title: Logstash JDBC input, filter event times...",\r\nOK I finally figure how to get the @timest...,"['https://i.sstatic.net/3nAZ9.png', 'https://i...",img0:\nTables:\nTable 0:\n+-------------------...

# Prompt

## Cloud

### Zero Shot

In [33]:
zero_shot = '''
You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
{}

Question:
{}

Answer:

'''

In [34]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['ocr'],row['context'])

cloud_processed['zero-shot-question'] = cloud_processed.apply(generate_zero_shot_prompt, axis=1)

In [35]:
print(cloud_processed['zero-shot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
  Stale resources detected
                                                 ×
                                                 x
     Some recently changed resources are not yet published. Continue with launch?
 ?
                                             No
                                   Yes

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Answer:

### CoT

In [36]:
cot = '''
You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
{}

Question:
{}

Lets think step by step:
Answer:
'''

In [37]:
def generate_cot_prompt(row):
    return cot.format(row['ocr'],row['context'])

cloud_processed['cot-question'] = cloud_processed.apply(generate_cot_prompt, axis=1)

In [38]:
print(cloud_processed['cot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
  Stale resources detected
                                                 ×
                                                 x
     Some recently changed resources are not yet published. Continue with launch?
 ?
                                             No
                                   Yes

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Lets think step by step:
Answer:

In [39]:
cloud_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1568 entries, 0 to 1567
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   context             1568 non-null   object
 1   gt                  1568 non-null   object
 2   img                 1568 non-null   object
 3   ocr                 1568 non-null   object
 4   zero-shot-question  1568 non-null   object
 5   cot-question        1568 non-null   object
dtypes: object(6)
memory usage: 73.6+ KB

## Device

### Zero Shot

In [40]:
zero_shot = '''
You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
{}

Question:
{}

Answer:

'''

In [41]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['ocr'],row['context'])

device_processed['zero-shot-question'] =device_processed.apply(generate_zero_shot_prompt, axis=1)

In [42]:
print(device_processed['zero-shot-question'][0])

You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
       CT
                                                                                              iptables
                                                                                                                                                                              Transmit Packet to
Data Link Layer
outbound interface
              Tracked by ConnTrack
                                               Receive Packet from
Data Link Layer
inbound interface
                                                                                              raw table
PREROUTING chain
                                                                              Defrag
                                                                                                                                      Routing
                                                                                                         CT
                                                                                              mangle table
PREROUTING chain
                                                                                                                                                                     CT
              Host Inbound Firewall
                                                                                                                                                                                                       Translate w
ConnTrack's
History
                                                                                                                                                                                 SNAT
                                                                                                                                                        nat table
POSTROUTING chain
                                                                                            Is
this packet
a part of an existing
connection
                                                                                                                      Yes
                                                                                       No
                               mangle table
INPUT chain
                                                                                                       ?
                                                                                                                                                                             Is
this packet
a part of an existing
connection
                                                                                                                                          mangle table
FORWARD chain
                               filter table
INPUT chain
V
security table
INPUT chain
                                                                                                                    Translate w
ConnTrack's
History
                                                                            nat table
PREROUTING chain
                                                                                                                                                                      No
                                                                                                                                                                                                        Yes
                                                                                                                                          filter table
FORWARD chain
V
security table
FORWARD chain
                                                                                                                                                                                        ?
                               nat table
INPUT chain
                                                                                                                                                                             mangle table
POSTROUTING chain
                                                                                                  Is this host
the final
destination?
                                                                                       Yes
                                                                                                                      No
                                      CT
                                                                                                                   Drop
Packet
                                                                                                                                                                   Yes
                                                                                                                                 No
                                                                                                                                       Is this packet routable?
                            Network Socket
(Host Application)
                                                                              Host Outbound Firewall
                                                                                                                                                                               security table
OUTPUT chain
                                                                                 mangle table
OUTPUT chain
                                                                                                                                                filter table
OUTPUT chain
                                                                                                                nat table
OUTPUT chain
                                                 raw table
OUTPUT chain
   Packet from
Network Socket
                                                                      CT
                             Defrag

Question:
title: What is the purpose of the INPUT chain in the nat table?
body: What is the purpose of the INPUT chain in the nat table ?

The PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".

The nat:INPUT and nat:PREROUTING chains seem redundant.

What would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?

Answer:

### CoT

In [43]:
cot = '''
You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
{}

Question:
{}

Lets think step by step:
Answer:
'''

In [44]:
def generate_cot_prompt(row):
    return cot.format(row['ocr'],row['context'])

device_processed['cot-question'] = device_processed.apply(generate_cot_prompt, axis=1)

In [45]:
print(device_processed['cot-question'][0])

You are an expert device assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
       CT
                                                                                              iptables
                                                                                                                                                                              Transmit Packet to
Data Link Layer
outbound interface
              Tracked by ConnTrack
                                               Receive Packet from
Data Link Layer
inbound interface
                                                                                              raw table
PREROUTING chain
                                                                              Defrag
                                                                                                                                      Routing
                                                                                                         CT
                                                                                              mangle table
PREROUTING chain
                                                                                                                                                                     CT
              Host Inbound Firewall
                                                                                                                                                                                                       Translate w
ConnTrack's
History
                                                                                                                                                                                 SNAT
                                                                                                                                                        nat table
POSTROUTING chain
                                                                                            Is
this packet
a part of an existing
connection
                                                                                                                      Yes
                                                                                       No
                               mangle table
INPUT chain
                                                                                                       ?
                                                                                                                                                                             Is
this packet
a part of an existing
connection
                                                                                                                                          mangle table
FORWARD chain
                               filter table
INPUT chain
V
security table
INPUT chain
                                                                                                                    Translate w
ConnTrack's
History
                                                                            nat table
PREROUTING chain
                                                                                                                                                                      No
                                                                                                                                                                                                        Yes
                                                                                                                                          filter table
FORWARD chain
V
security table
FORWARD chain
                                                                                                                                                                                        ?
                               nat table
INPUT chain
                                                                                                                                                                             mangle table
POSTROUTING chain
                                                                                                  Is this host
the final
destination?
                                                                                       Yes
                                                                                                                      No
                                      CT
                                                                                                                   Drop
Packet
                                                                                                                                                                   Yes
                                                                                                                                 No
                                                                                                                                       Is this packet routable?
                            Network Socket
(Host Application)
                                                                              Host Outbound Firewall
                                                                                                                                                                               security table
OUTPUT chain
                                                                                 mangle table
OUTPUT chain
                                                                                                                                                filter table
OUTPUT chain
                                                                                                                nat table
OUTPUT chain
                                                 raw table
OUTPUT chain
   Packet from
Network Socket
                                                                      CT
                             Defrag

Question:
title: What is the purpose of the INPUT chain in the nat table?
body: What is the purpose of the INPUT chain in the nat table ?

The PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".

The nat:INPUT and nat:PREROUTING chains seem redundant.

What would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?

Lets think step by step:
Answer:

In [46]:
device_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 947 entries, 0 to 946
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   context             947 non-null    object
 1   gt                  947 non-null    object
 2   img                 947 non-null    object
 3   ocr                 947 non-null    object
 4   zero-shot-question  947 non-null    object
 5   cot-question        947 non-null    object
dtypes: object(6)
memory usage: 44.5+ KB

## Prompt Length

In [47]:
# extract prompt length
def prompt_length(text, add_special_tokens=True):
    if pd.isnull(text) or not isinstance(text, str) or not text.strip():
        return 0
    temp_inputs = tokenizer(text, return_tensors="pt", add_special_tokens=add_special_tokens)
    return temp_inputs.input_ids.shape[1]

In [48]:
# Prompt Length -> Cloud Logs
cloud_processed['zero-shot-question-length'] = cloud_processed['zero-shot-question'].apply(prompt_length)
cloud_processed['cot-question-length'] = cloud_processed['cot-question'].apply(prompt_length)

In [49]:
# Prompt Length -> Device Logs
device_processed['zero-shot-question-length'] = device_processed['zero-shot-question'].apply(prompt_length)
device_processed['cot-question-length'] = device_processed['cot-question'].apply(prompt_length)

# Generate Response

In [50]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

### Zero-Shot

In [51]:
import os
import torch
import gc
import traceback

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"
torch.set_grad_enabled(False)

torch.manual_seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

def generate_zero_shot_answer(row):
    try:
        # Encode the question and move to the model’s device
        input_ids = tokenizer(
            row["zero-shot-question"], return_tensors="pt"
        ).input_ids.to(model.device)
        prompt_length=input_ids.shape[1]

        # Generate a completion
        output = model.generate(
            input_ids,
            max_new_tokens=768,
            do_sample=False,
            use_cache=True
        )

        # Decode and return the answer only
        return tokenizer.decode(output[0][prompt_length:], skip_special_tokens=True)

    except Exception as e:
        # Return the error string (no prompt info)
        return f"[ERROR] {e}\n{traceback.format_exc()}"

    finally:
        # Clean up GPU / RAM
        for var in ("input_ids", "output"):
            if var in locals():
                del locals()[var]
        torch.cuda.empty_cache()
        gc.collect()

### CoT

In [52]:
import os
import torch
import gc
import traceback

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"
torch.set_grad_enabled(False)

torch.manual_seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

def generate_cot_answer(row):
    try:
        input_ids = tokenizer(
            row["cot-question"], return_tensors="pt"
        ).input_ids.to(model.device)
        prompt_length=input_ids.shape[1]

        output = model.generate(
            input_ids,
            max_new_tokens=768,
            do_sample=False,
            use_cache=True,
        )

        return tokenizer.decode(output[0][prompt_length:], skip_special_tokens=True)

    except Exception as e:
        return f"[ERROR] {e}\n{traceback.format_exc()}"

    finally:
        for var in ("input_ids", "output"):
            if var in locals():
                del locals()[var]
        torch.cuda.empty_cache()
        gc.collect()

## Testing Samples

In [53]:
sample = cloud_processed.sort_values('zero-shot-question-length', ascending=False).head(3).reset_index(drop=True)

In [61]:
sample =cloud_processed[0:9]

In [62]:
sample.head(2)

,context,gt,img,ocr,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],img0:\nNon-table text:\n Stale resources dete...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,171,178
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",img0:\nTables:\nTable 0:\n+----+--------------...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,3421,3428

In [63]:
print(sample['zero-shot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
  Stale resources detected
                                                 ×
                                                 x
     Some recently changed resources are not yet published. Continue with launch?
 ?
                                             No
                                   Yes

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Answer:

In [64]:
zero_results = []
failed_responses = []
jsonl_records = []

output_file="llm_ocr_sample_mistral_8b_instruct_2410_zero_shot_results.jsonl"
failed_file="llm_ocr_sample_mistral_8b_instruct_2410_zero_shot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass

for idx, row in tqdm(sample.iterrows(), total=len(sample)):
    answer = generate_zero_shot_answer(row)

    # Track response
    zero_results.append(answer)

    # Sample print preview
    if idx == 0:
        question_text = row['zero-shot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Question:\n")
        print(short_question)

        print("\n\nSample Response:\n")
        print(answer)

    # JSONL record
    record = {
        "row": idx,
        "question": row["zero-shot-question"],
        "response": answer
    }

    jsonl_records.append(record)
    
    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
             f.write(json.dumps(failed_responses) + "\n")
    

# Add generated answers to DataFrame
sample["zero-shot-generated-answer"] = zero_results

  0%|          | 0/9 [00:00<?, ?it/s]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 11%|█         | 1/9 [00:00<00:04,  1.87it/s]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

Sample Question:


You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR


Sample Response:

No answer.

 22%|██▏       | 2/9 [00:11<00:45,  6.48s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 33%|███▎      | 3/9 [00:11<00:22,  3.82s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 44%|████▍     | 4/9 [00:49<01:26, 17.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 56%|█████▌    | 5/9 [01:00<00:59, 14.89s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 67%|██████▋   | 6/9 [01:05<00:34, 11.57s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 78%|███████▊  | 7/9 [01:07<00:16,  8.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 89%|████████▉ | 8/9 [01:21<00:10, 10.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
100%|██████████| 9/9 [01:25<00:00,  9.53s/it]
/tmp/ipykernel_349/2873790280.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample["zero-shot-generated-answer"] = zero_results

In [70]:
print(zero_results[1])

The issue seems to be with the deployment task itself. The artifact is correctly created and is not corrupt, as demonstrated by the successful deployment using the "Zip Push Deploy" feature in the Kudu console. The deployment task might be incorrectly handling the artifact, resulting in a 1 KB file being uploaded instead of the actual 17 MB artifact. This could be due to a bug or misconfiguration in the deployment task.

In [71]:
import json
from tqdm import tqdm

cot_results = []
failed_cot_responses = []
cot_jsonl_records = []

output_file="llm_ocr_sample_mistral_8b_instruct_2410_cot_results.jsonl"
failed_file="llm_ocr_sample_mistral_8b_instruct_2410_cot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass


for idx, row in tqdm(sample.iterrows(), total=len(sample)):
    answer = generate_cot_answer(row)

    # Append result
    cot_results.append(answer)

    # Show sample only for first entry
    if idx == 0:
        question_text = row['cot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample CoT Question:\n")
        print(short_question)

        print("\n\nSample CoT Response:\n")
        print(answer)

    # Record for JSONL
    record = {
        "row": idx,
        "question": row["cot-question"],
        "response": answer
    }
    jsonl_records.append(record)
    
    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
            f.write(json.dumps(record) + "\n")
    


# Add generated CoT answers to DataFrame
sample["cot-generated-answer"] = cot_results

  0%|          | 0/9 [00:00<?, ?it/s]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 11%|█         | 1/9 [00:14<01:57, 14.65s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

Sample CoT Question:


You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR


Sample CoT Response:

The issue you're experiencing is likely due to the fact that the resources you've changed are not yet published to the Google App Engine. When you click "Yes", the server starts with the old code because the new changes haven't been published yet. To resolve this issue, you should try the following steps:

1. **Publish the changes**: Make sure to publish the changes to the Google App Engine. You can do this by clicking on the "Deploy" button in the Google Cloud Console or by using the `gcloud` command-line tool.

2. **Clear the cache**: Sometimes, the issue might be due to a cached version of your application. Try clearing the cache by deleting the `app.yaml` file and redeploying your application.

3. **Check for errors**: Make sure there are no errors in your code that might be preventing the changes from being published. You can check the logs in the Google Cloud Console for any error messages.

4. **Restart the server**: After publishing the changes, restart the server to ensure that the new code is being used.

If you've tried all these steps and the issue persists, it might be helpful to reach out to Google Cloud support for further assistance.

 22%|██▏       | 2/9 [00:24<01:21, 11.63s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 33%|███▎      | 3/9 [00:24<00:39,  6.63s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 44%|████▍     | 4/9 [00:47<01:04, 12.81s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 56%|█████▌    | 5/9 [00:58<00:48, 12.15s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 67%|██████▋   | 6/9 [01:03<00:29,  9.82s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 78%|███████▊  | 7/9 [01:05<00:14,  7.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
 89%|████████▉ | 8/9 [01:14<00:07,  7.89s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
100%|██████████| 9/9 [01:27<00:00,  9.76s/it]
/tmp/ipykernel_349/4282560175.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample["cot-generated-answer"] = cot_results

In [77]:
print(cot_results[6])

The cost for units of write capacity beyond the free tier is $0.00065 per hour.

In [ ]:
sample.to_csv("sample_llm_ocr_mistral_8b_instruct_2410.csv")

## Cloud Testset

In [78]:
cloud_testset=cloud_processed

In [79]:
cloud_testset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1568 entries, 0 to 1567
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   context                    1568 non-null   object
 1   gt                         1568 non-null   object
 2   img                        1568 non-null   object
 3   ocr                        1568 non-null   object
 4   zero-shot-question         1568 non-null   object
 5   cot-question               1568 non-null   object
 6   zero-shot-question-length  1568 non-null   int64
 7   cot-question-length        1568 non-null   int64
dtypes: int64(2), object(6)
memory usage: 98.1+ KB

In [80]:
cloud_testset.head(2)

,context,gt,img,ocr,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],img0:\nNon-table text:\n Stale resources dete...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,171,178
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",img0:\nTables:\nTable 0:\n+----+--------------...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,3421,3428

### zero shot response

In [81]:
import json
from tqdm import tqdm

zero_cloud_results = []
zero_cloud_jsonl_records = []
zero_cloud_failed_responses = []

output_file="llm_ocr_cloud_mistral_8b_instruct_2410_zero_shot_results.jsonl"
failed_file="llm_ocr_cloud_mistral_8b_instruct_2410_zero_shot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass

for idx, row in tqdm(cloud_testset.iterrows(), total=len(cloud_testset)):
    # Generate answer
    answer = generate_zero_shot_answer(row)
    zero_cloud_results.append(answer)

    # Show the first response as a sample
    if idx == 0:
        question_text = row['zero-shot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Cloud Zero-Shot Question:\n")
        print(short_question)

        print("\n\nSample Cloud Zero-Shot Response:\n")
        print(answer)

    # Prepare JSONL record
    record = {
        "row": idx,
        "question": row["zero-shot-question"],
        "response": answer
    }
    zero_cloud_jsonl_records.append(record)

    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
          f.write(json.dumps(record) + "\n")

# Save results in the DataFrame
cloud_testset["zero-shot-generated-answer"] = zero_cloud_results

  0%|          | 0/1568 [00:00<?, ?it/s]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  0%|          | 1/1568 [00:00<13:44,  1.90it/s]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

Sample Cloud Zero-Shot Question:


You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR


Sample Cloud Zero-Shot Response:

No answer.

  0%|          | 2/1568 [00:11<2:49:28,  6.49s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  0%|          | 3/1568 [00:11<1:39:44,  3.82s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  0%|          | 4/1568 [00:49<7:29:22, 17.24s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  0%|          | 5/1568 [01:00<6:28:16, 14.90s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  0%|          | 6/1568 [01:05<5:01:41, 11.59s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  0%|          | 7/1568 [01:07<3:38:56,  8.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|          | 8/1568 [01:21<4:25:47, 10.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|          | 9/1568 [01:25<3:37:14,  8.36s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|          | 10/1568 [01:38<4:14:08,  9.79s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|          | 11/1568 [01:53<4:53:23, 11.31s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|          | 12/1568 [01:54<3:29:06,  8.06s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|          | 13/1568 [02:23<6:19:40, 14.65s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|          | 14/1568 [02:27<4:54:29, 11.37s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|          | 15/1568 [02:47<5:56:57, 13.79s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|          | 16/1568 [02:53<4:56:43, 11.47s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|          | 17/1568 [03:10<5:40:25, 13.17s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|          | 18/1568 [03:28<6:15:41, 14.54s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|          | 19/1568 [03:41<6:06:49, 14.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|▏         | 20/1568 [03:48<5:07:11, 11.91s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|▏         | 21/1568 [03:56<4:42:53, 10.97s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|▏         | 22/1568 [04:15<5:39:36, 13.18s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  1%|▏         | 23/1568 [04:30<5:54:02, 13.75s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 24/1568 [04:30<4:12:45,  9.82s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 25/1568 [04:45<4:48:37, 11.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 26/1568 [04:57<4:55:27, 11.50s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 27/1568 [05:12<5:22:32, 12.56s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 28/1568 [05:26<5:28:59, 12.82s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 29/1568 [05:44<6:13:46, 14.57s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 30/1568 [06:34<10:45:58, 25.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 31/1568 [07:34<15:09:03, 35.49s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 32/1568 [07:47<12:16:27, 28.77s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 33/1568 [08:12<11:51:54, 27.83s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 34/1568 [08:20<9:13:05, 21.63s/it] The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 35/1568 [08:35<8:24:22, 19.74s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 36/1568 [08:43<6:55:05, 16.26s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 37/1568 [08:44<4:55:50, 11.59s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 38/1568 [09:00<5:29:08, 12.91s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  2%|▏         | 39/1568 [09:01<3:57:28,  9.32s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 40/1568 [09:05<3:20:46,  7.88s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 41/1568 [09:13<3:17:38,  7.77s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 42/1568 [09:41<5:57:26, 14.05s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 43/1568 [10:17<8:40:53, 20.49s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 44/1568 [10:18<6:12:36, 14.67s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 45/1568 [10:26<5:21:59, 12.68s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 46/1568 [10:27<3:51:28,  9.13s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 47/1568 [11:06<7:41:07, 18.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 48/1568 [11:07<5:30:27, 13.04s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 49/1568 [11:20<5:29:26, 13.01s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 50/1568 [11:27<4:44:25, 11.24s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 51/1568 [11:28<3:24:22,  8.08s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 52/1568 [11:35<3:18:42,  7.86s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 53/1568 [11:36<2:24:34,  5.73s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  3%|▎         | 54/1568 [11:37<1:49:24,  4.34s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▎         | 55/1568 [11:50<2:53:19,  6.87s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▎         | 56/1568 [12:00<3:15:57,  7.78s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▎         | 57/1568 [12:19<4:43:27, 11.26s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▎         | 58/1568 [12:22<3:38:53,  8.70s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▍         | 59/1568 [12:23<2:42:40,  6.47s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▍         | 60/1568 [12:39<3:53:30,  9.29s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▍         | 61/1568 [12:56<4:53:09, 11.67s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▍         | 62/1568 [13:32<7:51:57, 18.80s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▍         | 63/1568 [13:52<7:58:13, 19.07s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▍         | 64/1568 [13:58<6:26:17, 15.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▍         | 65/1568 [14:00<4:43:22, 11.31s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▍         | 66/1568 [14:18<5:36:03, 13.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▍         | 67/1568 [14:36<6:06:09, 14.64s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  4%|▍         | 68/1568 [14:44<5:19:22, 12.78s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

In [82]:
cloud_testset.head(2)

,context,gt,img,ocr,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero-shot-generated-answer
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],img0:\nNon-table text:\n Stale resources dete...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,171,178,No answer.
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",img0:\nTables:\nTable 0:\n+----+--------------...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,3421,3428,The issue seems to be with the deployment task...

In [83]:
cloud_testset.to_excel("../responses/cloud/llm_ocr_response_cloud_mistral_8b_instruct_2410.xlsx", index=False)

### Cot Response

In [ ]:
import json
from tqdm import tqdm

cot_cloud_results = []
failed_cloud_cot_responses = []
cot_cloud_jsonl_records = []

output_file="llm_ocr_cloud_mistral_8b_instruct_2410_cot_results.jsonl"
failed_file="llm_ocr_cloud_mistral_8b_instruct_2410_cot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass


for idx, row in tqdm(cloud_testset.iterrows(), total=len(cloud_testset)):
    # Generate answer using CoT function
    answer = generate_cot_answer(row)
    cot_cloud_results.append(answer)

    # Sample output (first only)
    if idx == 0:
        question_text = row['cot-question']
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Cloud CoT Question:\n")
        print(short_question)

        print("\n\nSample Cloud CoT Response:\n")
        print(answer)

    # Prepare JSONL entry
    record = {
        "row": idx,
        "question": row["cot-question"],
        "response": answer
    }
    cot_cloud_jsonl_records.append(record)
    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
            f.write(json.dumps(record) + "\n")

# Append column to DataFrame
cloud_testset["cot-generated-answer"] = cot_cloud_results

  0%|          | 1/1627 [00:38<17:15:18, 38.20s/it]

Sample Question (first 100 tokens):



You are an expert cloud assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."
Question:
title: Some recently changed resources are not yet published
body


Sample Response:


This issue is likely due to stale metadata on your local machine that's causing App Engine to serve outdated versions of your application.

To resolve this:

1\. Delete the `~/.appengine/default` directory (on Linux/Mac) or `%USERPROFILE%\.appengine\default` (on Windows).

2\. Run `gcloud app deploy --project <your-project-id>` from your terminal/command prompt.

3\. Make sure Eclipse is configured correctly for deployment; check your run configurations and ensure they're pointing at the correct SDK version.

4\. Try redeploying your application through Eclipse after making these changes.

5\. Consider increasing the `max_allowed_old_versions` setting in your `app.yaml`.

Note:\* You can find more details about this behavior [here](https://issuetracker.google.com/issues/36945422).\*\* This solution assumes you have already set up your environment using the Google Cloud SDK.\*\*

Please try these steps and let me know if any further assistance is required!

**Additional Tips**

\- Ensure your workspace folder doesn't contain duplicate `.iml` files which may cause issues during deployment

\- Verify that the 'Java Build Path' properties under Project Properties > Java Build Path match those specified in the pom.xml file (if applicable)

\- In some cases, updating Gradle might also be necessary - consult official documentation for instructions

I hope this helps resolve the problem!

Is there anything else I can help with?  Please provide more context or clarify the specific requirements.   :)


---

## Step 1: Identify the root cause of the issue
The user reports encountering an error where some recently changed resources are not yet published, even after clicking "Yes" to update their GAE server.


## Step 2: Determine possible solutions based on known behaviors
Based on similar reported issues ([issue tracker link](https://issuetracker.google.com/issues/36945422)), we suspect that stale metadata on the local machine could be the culprit behind serving outdated versions of the application.


## Step 3: Suggest deletion of stale metadata
Delete the `~/.appengine/default` directory (Linux/Mac) or `%USERPROFILE%\.appengine\default` (Windows), as recommended by other users who encountered similar problems.


## Step 4: Recommend re-deployment via command line tool
Run `gcloud app deploy --project <your-project-id>` from the terminal/command prompt to force a new build and deployment.


## Step 5: Check configuration settings in Eclipse
Verify that Eclipse is properly configured for deployment by checking the run configurations and ensuring they point to the correct SDK version.


## Step 6: Offer additional troubleshooting tips
Consider adjusting the `max_allowed_old_versions` setting in `app.yaml`, removing potential duplicates of `.iml` files within the workspace, verifying consistency between the Java Build Path properties and pom.xml (for Maven projects), and potentially updating Gradle (if used).


The final answer is: There isn't one single definitive answer here since the resolution depends heavily upon individual setups & circumstances. However, going through each suggested action should hopefully alleviate whatever underlying issue was preventing recent resource updates from being reflected accurately across all areas involved.

100%|██████████| 1627/1627 [13:23:53<00:00, 29.65s/it]

In [ ]:
cloud_testset.head(2)

,context,gt,zero-shot-question,cot-question,cot-generated-answer
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,This issue is likely due to stale metadata on ...
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,There could be several reasons for this issue....

In [ ]:
cloud_testset.to_excel("../responses/cloud/llm_ocr_response_cloud_mistral_8b_instruct_2410_cot.xlsx", index=False)

## Device Testset

In [ ]:
device_testset=device_processed

In [ ]:
device_testset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1021 entries, 0 to 1020
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   context                    1021 non-null   object
 1   gt                         1021 non-null   object
 2   zero-shot-question         1021 non-null   object
 3   cot-question               1021 non-null   object
 4   zero-shot-question-length  1021 non-null   int64
 5   cot-question-length        1021 non-null   int64
dtypes: int64(2), object(4)
memory usage: 48.0+ KB

In [ ]:
device_testset.shape

(1021, 6)

### Zero shot Response

In [ ]:
import json
from tqdm import tqdm

# Lists for tracking
zero_device_results = []
zero_device_jsonl_records = []
zero_device_failed_responses = []

output_file="llm_ocr_device_mistral_8b_instruct_2410_zero_shot_results.jsonl"
failed_file="llm_ocr_device_mistral_8b_instruct_2410_zero_shot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass

for idx, row in tqdm(device_testset.iterrows(), total=len(device_testset)):
    # Generate zero-shot answer
    answer = generate_zero_shot_answer(row)
    zero_device_results.append(answer)

    # Print one sample preview
    if idx == 0:
        question_text = row["zero-shot-question"]
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Device Zero-Shot Question:\n")
        print(short_question)

        print("\n\nSample Device Zero-Shot Response:\n")
        print(answer)

    # Build JSONL record
    record = {
        "row": idx,
        "question": row["zero-shot-question"],
        "response": answer
    }
    zero_device_jsonl_records.append(record)

    with open(output_file, "a") as f:
        f.write(json.dumps(record) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
            f.write(json.dumps(record) + "\n")


# Add results to DataFrame
device_testset["zero-shot-generated-answer"] = zero_device_results

  0%|          | 1/1021 [00:32<9:10:06, 32.36s/it]

Sample Question:


You are an expert device assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."

Question:
title: What is the purpose of the INPUT chain in the


Sample Response:

There isn't enough specific context or details about how your system uses NAT rules for me to provide a precise explanation on this topic without potentially causing confusion. However, I can give some general guidance based on common practices.


In Linux's Netfilter framework, which includes iptables, there are several tables and chains used for network address translation (NAT). The main goal here seems to be to understand why one might choose to specifically target the `nat:INPUT` chain when it appears similar functionality could also be achieved through other means like the `nat:PREROUTING` chain.

1. **Understanding Chain Differences**: Each chain serves different purposes within the packet processing pipeline. Understanding these differences helps determine where to place specific rules:


   - **POSTROUTING** handles outgoing traffic after routing decisions have been made; useful for SNAT (Source NAT).

   - **OUTPUT** deals with outgoing local traffic before any routing decision has been taken into account; good for source port randomization among many things.

   - **PREROUTING**, as mentioned, does DNAT (Destination NAT), essentially changing the destination IP of incoming packets.

   - **INPUT** refers to handling incoming traffic once it’s decided by the router to go to this host but right before actually reaching its final process.



2. **Specific Use Cases for INPUT vs PREROUTING Chains**: While both chains can perform DNAT, their application scenarios differ slightly due to timing considerations during packet traversal:



    * If you want to ensure certain services or ports get translated even if they're not explicitly listed under default actions in higher precedence rules, using `nat:INPUT` ensures consistency across all incoming connections regardless of protocol or service type being accessed directly from outside.

    * Another scenario involves complex setups requiring multiple translations depending on various conditions met at input stage rather than just prerouting level, suggesting more fine-grained control over how inputs are handled.

3.  **Avoiding Conflicts and Simplifying Rulesets**: Sometimes splitting tasks between two seemingly overlapping features makes sense because each rule set can focus narrowly without conflicting priorities inherent in broader rule sets.

4. **Flexibility and Future-Proofing**: Even though functionalities overlap somewhat, having options allows for better adaptability in case future requirements demand changes that wouldn’t necessitate wholesale rewrites otherwise achievable solely via single feature implementation strategies.



Given the complexity involved, providing a definitive reason for choosing `nat:INPUT` over `nat:PREROUTING` requires detailed knowledge of your specific setup, including the operating environment, existing configuration, and security policies aimed to achieve through such configurations.



To clarify further, consulting official documentation or experienced professionals familiar with your particular infrastructure will offer insights tailored precisely to those specifics beyond generic descriptions provided above.

100%|██████████| 1021/1021 [6:45:14<00:00, 23.81s/it]

In [ ]:
device_testset.head(2)

,context,gt,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero-shot-generated-answer
0,title: What is the purpose of the INPUT chain ...,\nIf some NAT operation needs to be only done ...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,144,150,There isn't enough specific context or details...
1,"title: Logstash JDBC input, filter event times...",\nOK I finally figure how to get the @timestam...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,550,556,You're experiencing issues with Logstash's `da...

In [ ]:
device_testset.to_excel("../responses/device/llm_ocr_response_device_mistral_8b_instruct_2410.xlsx", index=False)

### CoT Response

In [ ]:
import json
from tqdm import tqdm

# Containers
cot_device_results = []
cot_device_jsonl_records = []
cot_device_failed_responses = []

output_file="llm_ocr_device_mistral_8b_instruct_2410_cot_results.jsonl"
failed_file="llm_ocr_device_mistral_8b_instruct_2410_cot_failed.jsonl"

# Clear output files first
with open(output_file, "w"): pass
with open(failed_file, "w"): pass

for idx, row in tqdm(device_testset.iterrows(), total=len(device_testset)):
    # Generate CoT answer
    answer = generate_cot_answer(row)
    cot_device_results.append(answer)

    # Print one sample preview
    if idx == 0:
        question_text = row["cot-question"]
        question_tokens = tokenizer.tokenize(question_text)[:45]
        short_question = tokenizer.convert_tokens_to_string(question_tokens)

        print("\n\nSample Device CoT Question:\n")
        print(short_question)

        print("\n\nSample Device CoT Response:\n")
        print(answer)

    # JSONL record
    record = {
        "row": idx,
        "question": row["cot-question"],
        "response": answer
    }
    cot_device_jsonl_records.append(record)

    with open(output_file, "a") as f:
        f.write(json.dumps(jsonl_records) + "\n")

    # Track failures
    if isinstance(answer, str) and answer.startswith("[ERROR]"):
        failed_responses.append(record)
        with open(failed_file, "a") as f:
            f.write(json.dumps(failed_responses) + "\n")

# Write results back to DataFrame
device_testset["cot-generated-answer"] = cot_device_results

  0%|          | 1/1021 [00:19<5:24:59, 19.12s/it]

Sample Question:


You are an expert device assistant. Provide a concise answer to the following question.
If you lack sufficient information to answer, respond with "No answer."
Question:
title: What is the purpose of the INPUT chain in the


Sample Response:

There's no definitive rule for using one over another; however, if your network has both source NAT and destination NAT enabled on different interfaces, then it might make sense to have two separate chains - one for each type of operation.

For example:

*   If you're performing DNAT on interface eth0 but SNAT on interface eth1, having two separate chains allows for more fine-grained control over which operations occur when packets arrive from or leave via those respective interfaces.
*   In this scenario, packets arriving at `eth0` will undergo DNAT as they pass through the prerouting chain, while SNAT occurs after packet inspection within the routing decision process before being sent out via `eth1`. The input chain can then perform additional actions based solely upon where these modified packets originated from (`eth1`). This separation enables better security controls since now we only allow traffic coming into our system directly associated with specific outgoing connections rather than indiscriminately applying rules across all types of ingress traffic.



In summary, without any clear-cut guidelines regarding whether one should utilize either or both depending strictly upon functional requirements beyond simple port-forwarding scenarios described earlier, employing multiple chains appears beneficial under complex configurations involving mixed mode translations – particularly allowing greater flexibility during troubleshooting phases due increased visibility into distinct operational contexts provided per-rule basis throughout entire firewall policy hierarchy.


Note : While there isn't anything inherently wrong about placing them together under single default setup usually seen today, utilizing dual-chain approach provides certain advantages especially pertinent situations requiring granular level management capability above standard implementation norms typically observed elsewhere making argument fairly strong albeit lacking explicit mandate supporting usage pattern itself so far discussed here.

100%|██████████| 1021/1021 [8:07:04<00:00, 28.62s/it]

In [ ]:
device_testset.head(2)

,context,gt,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero-shot-generated-answer,cot-generated-answer
0,title: What is the purpose of the INPUT chain ...,\nIf some NAT operation needs to be only done ...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,144,150,There isn't enough specific context or details...,There's no definitive rule for using one over ...
1,"title: Logstash JDBC input, filter event times...",\nOK I finally figure how to get the @timestam...,\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,550,556,You're experiencing issues with Logstash's `da...,The issue lies in how Logstash interprets the ...

In [ ]:
device_testset.to_excel("../responses/device/llm_ocr_response_device_mistral_8b_instruct_2410_cot.xlsx", index=False)