# Environment

In [1]:
! pip install pandas
! pip install pillow

Collecting pandas
  Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 2.3 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 220.2 MB/s eta 0:00:0000:010:01
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 152.1 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 kB 124.7 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2025.2 tzdata-2025.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (9.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

In [2]:
! pip install transformers accelerate bitsandbytes safetensors torch torchvision

Collecting transformers
  Downloading transformers-4.52.4-py3-none-any.whl.metadata (38 kB)
Collecting accelerate
  Downloading accelerate-1.7.0-py3-none-any.whl.metadata (19 kB)
Collecting bitsandbytes
  Downloading bitsandbytes-0.46.0-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting safetensors
  Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.1.0+cu118)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (0.16.0+cu118)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.9.0)
Collecting huggingface-hub<1.0,>=0.30.0 (from transformers)
  Downloading huggingface_hub-0.32.4-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.24.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 16.2 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting tqdm>=4.27 (from transformers)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 15.0 MB/s eta 0:00:00
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.6)
Collecting torch
  Downloading torch-2.7.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading typing_extensions-4.14.0-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2023.4.0)
Collecting nvidia-cuda-nvrtc-cu12==12.6.77 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.6.77 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.6.80 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.5.1.17 (from torch)
  Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.6.4.1 (from torch)
  Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.3.0.4 (from torch)
  Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.7.77 (from torch)
  Downloading nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.7.1.2 (from torch)
  Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.5.4.2 (from torch)
  Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparselt-cu12==0.6.3 (from torch)
  Downloading nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.26.2 (from torch)
  Downloading nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvtx-cu12==12.6.77 (from torch)
  Downloading nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nvjitlink-cu12==12.6.85 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufile-cu12==1.11.1.6 (from torch)
  Downloading nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.3.0 (from torch)
  Downloading triton-3.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: setuptools>=40.8.0 in /usr/local/lib/python3.10/dist-packages (from triton==3.3.0->torch) (68.2.2)
INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
Collecting torchvision
  Downloading torchvision-0.22.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision) (9.3.0)
Collecting fsspec (from torch)
  Downloading fsspec-2025.5.1-py3-none-any.whl.metadata (11 kB)
Collecting hf-xet<2.0.0,>=1.1.2 (from huggingface-hub<1.0,>=0.30.0->transformers)
  Downloading hf_xet-1.1.3-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (879 bytes)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2022.12.7)
Downloading transformers-4.52.4-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 250.7 MB/s eta 0:00:0000:01
Downloading accelerate-1.7.0-py3-none-any.whl (362 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 362.1/362.1 kB 132.0 MB/s eta 0:00:00
Downloading bitsandbytes-0.46.0-py3-none-manylinux_2_24_x86_64.whl (67.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.0/67.0 MB 109.1 MB/s eta 0:00:0000:0100:01
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 89.4 MB/s eta 0:00:00
Downloading torch-2.7.0-cp310-cp310-manylinux_2_28_x86_64.whl (865.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 865.2/865.2 MB 14.9 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (393.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 31.6 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 234.0 MB/s eta 0:00:0000:01
Downloading nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 189.3 MB/s eta 0:00:00a 0:00:01
Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (897 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 kB 184.6 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl (571.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.0/571.0 MB 22.1 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (200.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 55.3 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 228.7 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 143.3 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (158.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 MB 63.5 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (216.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 MB 55.9 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl (156.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.8/156.8 MB 71.1 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (201.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.3/201.3 MB 52.1 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (19.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 205.0 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.3/89.3 kB 35.3 MB/s eta 0:00:00
Downloading triton-3.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (156.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.4/156.4 MB 65.3 MB/s eta 0:00:0000:0100:01
Downloading torchvision-0.22.0-cp310-cp310-manylinux_2_28_x86_64.whl (7.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 255.6 MB/s eta 0:00:00
Downloading huggingface_hub-0.32.4-py3-none-any.whl (512 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 512.1/512.1 kB 141.2 MB/s eta 0:00:00
Downloading fsspec-2025.5.1-py3-none-any.whl (199 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 kB 95.0 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.7/781.7 kB 191.0 MB/s eta 0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 257.9 MB/s eta 0:00:00
Downloading tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 237.9 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 42.4 MB/s eta 0:00:00
Downloading typing_extensions-4.14.0-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 24.2 MB/s eta 0:00:00
Downloading hf_xet-1.1.3-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 258.4 MB/s eta 0:00:00
Installing collected packages: nvidia-cusparselt-cu12, typing-extensions, triton, tqdm, sympy, safetensors, regex, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, hf-xet, fsspec, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, torchvision, bitsandbytes, accelerate
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.4.0
    Uninstalling typing_extensions-4.4.0:
      Successfully uninstalled typing_extensions-4.4.0
  Attempting uninstall: triton
    Found existing installation: triton 2.1.0
    Uninstalling triton-2.1.0:
      Successfully uninstalled triton-2.1.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12
    Uninstalling sympy-1.12:
      Successfully uninstalled sympy-1.12
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2023.4.0
    Uninstalling fsspec-2023.4.0:
      Successfully uninstalled fsspec-2023.4.0
  Attempting uninstall: torch
    Found existing installation: torch 2.1.0+cu118
    Uninstalling torch-2.1.0+cu118:
      Successfully uninstalled torch-2.1.0+cu118
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.16.0+cu118
    Uninstalling torchvision-0.16.0+cu118:
      Successfully uninstalled torchvision-0.16.0+cu118
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.0+cu118 requires torch==2.1.0, but you have torch 2.7.0 which is incompatible.
Successfully installed accelerate-1.7.0 bitsandbytes-0.46.0 fsspec-2025.5.1 hf-xet-1.1.3 huggingface-hub-0.32.4 nvidia-cublas-cu12-12.6.4.1 nvidia-cuda-cupti-cu12-12.6.80 nvidia-cuda-nvrtc-cu12-12.6.77 nvidia-cuda-runtime-cu12-12.6.77 nvidia-cudnn-cu12-9.5.1.17 nvidia-cufft-cu12-11.3.0.4 nvidia-cufile-cu12-1.11.1.6 nvidia-curand-cu12-10.3.7.77 nvidia-cusolver-cu12-11.7.1.2 nvidia-cusparse-cu12-12.5.4.2 nvidia-cusparselt-cu12-0.6.3 nvidia-nccl-cu12-2.26.2 nvidia-nvjitlink-cu12-12.6.85 nvidia-nvtx-cu12-12.6.77 regex-2024.11.6 safetensors-0.5.3 sympy-1.14.0 tokenizers-0.21.1 torch-2.7.0 torchvision-0.22.0 tqdm-4.67.1 transformers-4.52.4 triton-3.3.0 typing-extensions-4.14.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

In [3]:
! pip install huggingface-hub

Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.10/dist-packages (0.32.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (3.9.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (2025.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (6.0.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (1.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub) (2022.12.7)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

## Import Library

In [4]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig,pipeline
from tqdm import tqdm
import pandas as pd
import json

# Load Model

In [5]:
! nvidia-smi

Wed Jun  4 01:14:36 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.05             Driver Version: 550.127.05     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A40                     On  |   00000000:98:00.0 Off |                    0 |
|  0%   29C    P8             21W /  300W |       1MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [8]:
# token = "HF_TOKEN_REDACTED"

In [6]:
from huggingface_hub import login
import os

token = "HF_TOKEN_REDACTED"
os.environ['HF_TOKEN'] = token

login(token=token)
print("Logged in to Hugging Face!")

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Logged in to Hugging Face!

In [7]:
"""from huggingface_hub import login
import os

# Get HF token injected from RunPod secret
hf_token = os.getenv('HF_TOKEN')

# Login
login(token=hf_token)

print("Hugging Face login successful via RunPod Secret!")"""

'from huggingface_hub import login\nimport os\n\n# Get HF token injected from RunPod secret\nhf_token = os.getenv(\'HF_TOKEN\')\n\n# Login\nlogin(token=hf_token)\n\nprint("Hugging Face login successful via RunPod Secret!")'

## Full Model

In [8]:
from transformers import MllamaForConditionalGeneration, AutoProcessor
import torch, os

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"

model_id = "meta-llama/Llama-3.2-11B-Vision-Instruct"

# Load model
model = MllamaForConditionalGeneration.from_pretrained(
    model_id,
    device_map="auto",
    low_cpu_mem_usage=True,
)

min_pixels = 224 * 28 * 28              
max_pixels = 768 * 28 * 28  

processor = AutoProcessor.from_pretrained(
    model_id, min_pixels=min_pixels, max_pixels=max_pixels
)

config.json:   0%|          | 0.00/5.07k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/89.4k [00:00<?, ?B/s]

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

model-00001-of-00005.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00005-of-00005.safetensors:   0%|          | 0.00/1.47G [00:00<?, ?B/s]

model-00004-of-00005.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00005.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00002-of-00005.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

Some parameters are on the meta device because they were offloaded to the cpu.

preprocessor_config.json:   0%|          | 0.00/437 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/55.8k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

chat_template.json:   0%|          | 0.00/5.09k [00:00<?, ?B/s]

### Testing Response with Images

In [12]:
# multiple images

In [ ]:
from PIL import Image
import requests
import torch
import gc

# Helper to resize images for VRAM optimization
def resize_images(image_list, size=(224, 224)):
    return [img.resize(size, Image.BILINEAR) for img in image_list]

# Load and resize images
image_urls = [
    "https://media.istockphoto.com/id/1018245126/photo/siberian-tiger-portrait.jpg?s=612x612&w=0&k=20&c=ONrnG-JrcVuqdtIjfr4Pj85ZswUPt8wD-VbJOnWYPw0=",
    "https://images.pexels.com/photos/458991/pexels-photo-458991.jpeg?cs=srgb&dl=pexels-pixabay-458991.jpg&fm=jpg"
]
original_images = [Image.open(requests.get(url, stream=True).raw).convert("RGB") for url in image_urls]
images = [Image.open(requests.get(url, stream=True).raw).convert("RGB") for url in image_urls]


question = "whats the difference between these images"

messages = [
    {
        "role": "user",
        "content": [{"type": "image", "image": img} for img in images] + [{"type": "text", "text": question}]
    }
]
print(messages)
# Generate prompt with Qwen-style chat template
input_text = processor.apply_chat_template(messages, add_generation_prompt=True)

# Debug info
print("\n---- DEBUG INFO ----")
print("Generated Prompt:\n")
print(input_text)
print("\nNumber of <|vision_start|> tokens:", input_text.count("<|vision_start|>"))
print("Number of images passed:", len(images))
print("---------------------\n")

# Tokenize inputs
inputs = processor(
    text=[input_text],
    images=images,
    return_tensors="pt"
).to(model.device)

# Clear memory before generation
torch.cuda.empty_cache()
gc.collect()

# Generate response (deterministic)
with torch.amp.autocast(device_type="cuda" if torch.cuda.is_available() else "cpu"):
    generate_ids = model.generate(
        **inputs,
        max_new_tokens=200,
        do_sample=False
    )

# Decode only model's output, skipping the prompt
prompt_len = inputs["input_ids"].shape[1]
reply_ids = generate_ids[:, prompt_len:]
output_text = processor.tokenizer.decode(reply_ids[0], skip_special_tokens=True)

# Output
print("\n# Response:\n")
print(output_text)

# Load Datasets

In [9]:
import pandas as pd
cloud=pd.read_excel("../../Dataset/cloud/split_data/cloud_test.xlsx")
device=pd.read_excel("../../Dataset/device/split_data/device_test.xlsx")

## Cloud

In [10]:
cloud.head(2)

,title,body,tags,link,score,creation_date,answer_count,comments,answers,selected_answer,images
0,Some recently changed resources are not yet pu...,\n \nEvery once in a while i ge...,"['java', 'eclipse', 'google-app-engine', 'java...",https://stackoverflow.com/questions/49711724/s...,4,2018-04-07 20:34:12Z,1,"[""@code511788465541441, if you consider Chanse...",[{'body': '\n \nIf that happens...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,FAILED TO INITIALIZE RUN FROM PACKAGE.txt,\n \nOur pipeline indicates suc...,"['azure-web-app-service', 'azure-deployment', ...",https://stackoverflow.com/questions/65255839/f...,7,2020-12-11 17:20:22Z,2,"[""thanks for the hint. i am going to verify th...","[{'body': ""\nI am almost certain that the pack...",\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

In [11]:
cloud.shape

(1622, 11)

## Processed

In [17]:
cloud=cloud[['title','body','selected_answer','images']]

In [18]:
cloud.head(2)

,title,body,selected_answer,images
0,Some recently changed resources are not yet pu...,\n \nEvery once in a while i ge...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,FAILED TO INITIALIZE RUN FROM PACKAGE.txt,\n \nOur pipeline indicates suc...,\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

In [19]:
cloud['context'] = "title: " + cloud['title'].astype(str) + "\nbody: " + cloud['body'].astype(str).str.strip()

In [20]:
cloud_processed=pd.DataFrame(
    {
        'context':cloud['context'],
        'gt':cloud['selected_answer'],
        'img':cloud['images']
    }
)

In [21]:
cloud_processed.head(2)

,context,gt,img
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

## Device

In [22]:
device.head(2)

,title,body,tags,link,score,creation_date,answer_count,comments,answers,selected_answer,images
0,What is the purpose of the INPUT chain in the ...,\n \nWhat is the purpose of the...,"['linux', 'iptables', 'linux', 'iptables']",https://serverfault.com/questions/993878/what-...,1,2019-12-01 00:23:16Z,1,"['OK, also please add this to your answer so o...",[{'body': '\nIf some NAT operation needs to be...,\nIf some NAT operation needs to be only done ...,['https://i.sstatic.net/NUh2k.png']
1,"Logstash JDBC input, filter event timestamp di...",\n \nI am trying to change the ...,"['elasticsearch', 'logstash', 'elastic-stack',...",https://stackoverflow.com/questions/33787795/l...,0,2015-11-18 18:38:40Z,3,"['could you suggest how I could fix?', 'Your d...",[{'body': '\nOK I finally figure how to get th...,\nOK I finally figure how to get the @timestam...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

In [23]:
device.shape

(993, 11)

## Processed

In [24]:
device=device[['title','body','selected_answer','images']]

In [25]:
device.head(2)

,title,body,selected_answer,images
0,What is the purpose of the INPUT chain in the ...,\n \nWhat is the purpose of the...,\nIf some NAT operation needs to be only done ...,['https://i.sstatic.net/NUh2k.png']
1,"Logstash JDBC input, filter event timestamp di...",\n \nI am trying to change the ...,\nOK I finally figure how to get the @timestam...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

In [26]:
device['context'] = "title: " + device['title'].astype(str) + "\nbody: " + device['body'].astype(str).str.strip()

In [27]:
device_processed=pd.DataFrame(
    {
        'context':device['context'],
        'gt':device['selected_answer'],
        'img':device['images']
    }
)

In [28]:
device_processed.head(2)

,context,gt,img
0,title: What is the purpose of the INPUT chain ...,\nIf some NAT operation needs to be only done ...,['https://i.sstatic.net/NUh2k.png']
1,"title: Logstash JDBC input, filter event times...",\nOK I finally figure how to get the @timestam...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

# Prompt Setup

## Cloud

### Zero Shot

In [29]:
zero_shot = """
You are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."

Question:
{}

Answer:
"""

In [30]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['context'])

cloud_processed['zero-shot-question'] = cloud_processed.apply(generate_zero_shot_prompt, axis=1)

In [31]:
print(cloud_processed['zero-shot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Answer:

### CoT

In [32]:
cot = '''
You are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."
Question:
{}

Lets think step by step:
Answer:
'''

In [33]:
def generate_cot_prompt(row):
    return cot.format(row['context'])

cloud_processed['cot-question'] = cloud_processed.apply(generate_cot_prompt, axis=1)

In [34]:
print(cloud_processed['cot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."
Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Lets think step by step:
Answer:

## Device

### Zero Shot

In [35]:
zero_shot = '''
You are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."

Question:
{}

Answer:

'''

In [36]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['context'])

device_processed['zero-shot-question'] =device_processed.apply(generate_zero_shot_prompt, axis=1)

In [37]:
print(device_processed['zero-shot-question'][0])

You are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."

Question:
title: What is the purpose of the INPUT chain in the nat table?
body: What is the purpose of the INPUT chain in the nat table ?

The PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".

The nat:INPUT and nat:PREROUTING chains seem redundant.

What would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?

Answer:

### CoT

In [38]:
cot = '''
You are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."
Question:
{}

Lets think step by step:
Answer:
'''

In [39]:
def generate_cot_prompt(row):
    return cot.format(row['context'])

device_processed['cot-question'] = device_processed.apply(generate_cot_prompt, axis=1)

In [40]:
print(device_processed['cot-question'][0])

You are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."
Question:
title: What is the purpose of the INPUT chain in the nat table?
body: What is the purpose of the INPUT chain in the nat table ?

The PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".

The nat:INPUT and nat:PREROUTING chains seem redundant.

What would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?

Lets think step by step:
Answer:

## Prompt Length

In [41]:
# extract prompt length
def prompt_length(text, add_special_tokens=True):
    if pd.isnull(text) or not isinstance(text, str) or not text.strip():
        return 0
    temp_inputs = processor.tokenizer(text, return_tensors="pt", add_special_tokens=add_special_tokens)
    return temp_inputs.input_ids.shape[1]

In [42]:
# Prompt Length -> Cloud Logs
cloud_processed['zero-shot-question-length'] = cloud_processed['zero-shot-question'].apply(prompt_length)
cloud_processed['cot-question-length'] = cloud_processed['cot-question'].apply(prompt_length)

In [43]:
# Prompt Length -> Device Logs
device_processed['zero-shot-question-length'] = device_processed['zero-shot-question'].apply(prompt_length)
device_processed['cot-question-length'] = device_processed['cot-question'].apply(prompt_length)

# Message Setup ( Prompt + Images )

In [44]:
import ast

def setup_messages(dataset, prompt_column="", image_column="img"):
    messages = []

    for _, row in dataset.iterrows():
        imgs = row.get(image_column, [])
        if isinstance(imgs, str):
            try:
                imgs = ast.literal_eval(imgs)
            except Exception:
                imgs = []

        if imgs:
            # Build structured message with image placeholders and direct question
            content = [{"type": "image", "image": img} for img in imgs if img]
            content.append({
                "type": "text",
                "text": row.get(prompt_column, "")
            })

            messages.append({
                "role": "user",
                "qa": content
            })

    return messages

In [45]:
messages = setup_messages(device_processed,prompt_column="cot-question")

In [46]:
messages[1]

{'role': 'user',
 'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/3nAZ9.png'},
  {'type': 'image', 'image': 'https://i.sstatic.net/bsoVL.png'},
  {'type': 'image', 'image': 'https://i.sstatic.net/wM2pW.png'},
  {'type': 'text',
   'text': '\nYou are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\nQuestion:\ntitle: Logstash JDBC input, filter event timestamp different to @timestamp\nbody: I am trying to change the @timestamp to match my timestamp, this is the time my event occurred at not when logstash time stamped it.\n\nhere is my conf file\n\ninput {\n jdbc {\n   jdbc_driver_library => "C:/logstash/lib/mysql-connector-java-5.1.37-bin.jar"\n   jdbc_driver_class => "com.mysql.jdbc.Driver"\n   jdbc_connection_string => "jdbc:mysql://127.0.0.1:3306/transport"\n   jdbc_user => "root"\n   jdbc_password => ""\n   schedule => "* * * * *"\n   statement => "select id, timestamp, type, service, data, success, trans_id from audit where timestamp >= :sql_last_start"    \n }\n}\n\nfilter {\n    date {\n      match => [ "timestamp", "YYYY-MM-dd HH:mm:ss,SSS" ]\n      add_tag => [ "tsmatch" ]\n}\n}\n\noutput {\n  elasticsearch {\n     hosts => ["127.0.0.1:9200"]\n     index => "audit-%{+YYYY.MM.dd}"\n     document_id => "%{id}"\n }\n stdout {\n     codec => rubydebug\n }  \n}\n\n\nOut put\n\n{\n        "id" => 32,\n "timestamp" => 2015-11-18 18:21:44 +0000,\n      "type" => "Scheduled",\n   "service" => "Road",\n      "data" => "Changing the time",\n   "success" => 1,\n  "trans_id" => "ta819rsc",\n  "@version" => "1",\n"@timestamp" => "2015-11-18T18:22:00.069Z",\n      "tags" => [\n    [0] "_dateparsefailure"\n]\n}\n\n\nElasticsearch\n\n\n\nAs can be seen, the timestamps (times) are different. This will mess up my data when I bring it into Kibana as I want the histogram to filter on when the event happened not when logstash gave it the timestamp.\n\nCan some one provide me with the work around.\n\nUPDATE:\n\nI have changed the filter as suggested to \n\nmatch => [ "timestamp", "YYYY-MM-dd HH:mm:ss ZZZ" ] \n\n\nand the times are still out, and get the same _dateparsefailure in response. Would it have anything to do with the fact it\'s a Datestamp from MySQL and it can\'t be converted?\n\nG\n\nLets think step by step:\nAnswer:\n'}]}

# Generate Response

## Setup Model

In [47]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()

You shouldn't move a model that is dispatched using accelerate hooks.

RuntimeError: You can't move a model that has some modules offloaded to cpu or disk.

In [62]:
import math
from PIL import Image

MAX_LONG_EDGE = 224   
PATCH_SIZE    = 14    
MIN_EDGE      = 28   

def img_resize(img: Image.Image) -> Image.Image:
    w, h = img.size

    # Down-scale if long edge > 224
    scale = min(1.0, MAX_LONG_EDGE / max(w, h))
    w, h = int(round(w * scale)), int(round(h * scale))

    #  Guarantee minimum size
    w, h = max(w, MIN_EDGE), max(h, MIN_EDGE)

    # nearest multiple of patch size
    w  = math.ceil(w / PATCH_SIZE) * PATCH_SIZE
    h  = math.ceil(h / PATCH_SIZE) * PATCH_SIZE

    return img.resize((w, h), Image.Resampling.LANCZOS)

In [63]:
import torch
import gc
import traceback
import requests
import json
import os
from PIL import Image

torch.set_grad_enabled(False)
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"
torch.manual_seed(42)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

failed_responses = []

# Load and prepare image(s) from message
def process_vision_info(messages):
    images = []
    for msg in messages:
        for item in msg.get("content", []):
            if item["type"] == "image":
                img = item["image"]
                if isinstance(img, str):
                    img = Image.open(requests.get(img, stream=True).raw).convert("RGB")
                images.append(img_resize(img))
    return images

# Process message with debug info and collect failed responses
def process_message(msg: dict, idx: int):
    try:
        prompt_str = processor.apply_chat_template(
            [msg], tokenize=False, add_generation_prompt=True
        )

        imgs = process_vision_info([msg])
        if not imgs:
            raise ValueError("No images found in message.")

        inputs = processor(
            text=[prompt_str],
            images=imgs,
            return_tensors="pt"
        ).to(model.device)

        gen_ids = model.generate(
            **inputs,
            max_new_tokens=768,
            do_sample=False,
            use_cache=True
        )

        reply_ids = gen_ids[:, inputs.input_ids.shape[-1]:]
        answer = processor.batch_decode(
            reply_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )[0]

        return {"idx": idx, "response": answer}

    except Exception as e:
        failed_responses.append({
            "idx": idx,
            "question": msg.get("content", ""),
            "error": str(e),
            "traceback": traceback.format_exc()
        })
        return {"idx": idx, "response": f"[ERROR] {e}"}

    finally:
        for name in ("inputs", "gen_ids"):
            if name in locals():
                del locals()[name]
        torch.cuda.empty_cache()
        gc.collect()

## Testing Samples

In [46]:
#sample=cloud_processed[:5]
sample=cloud_processed[:5]

In [47]:
sample.head(2)

,context,gt,img,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,121,127
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,393,399

In [48]:
# Setup messages for model
sample_messages = setup_messages(sample,prompt_column="zero-shot-question")
#sample_messages = setup_messages(sample,prompt_column="cot-question")

In [49]:
sample_messages[:1]

[{'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/QQmRh.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Some recently changed resources are not yet published\nbody: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I\'ve tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?\n\nAnswer:\n'}]}]

### Get response for Sample  -> Test

In [50]:
# Output setup
sample_results = []
success_output_path = "sample_results_full.jsonl"
failure_output_path = "failed_response_sample.jsonl"

sample["generated_response"] = None

# Clear output files first
with open(success_output_path, "w"): pass
with open(failure_output_path, "w"): pass

# Process each message
for row_idx, msg in enumerate(tqdm(sample_messages, desc="Processing Messages")):
    try:
        # Build message
        qa_content = msg.get("qa", [])
        message = {
            "role": msg.get("role", "user"),
            "content": qa_content
        }

        # Extract image URLs
        image_urls = [c.get("image") for c in qa_content if c.get("type") == "image"]

        # Run inference
        result = process_message(message, idx=row_idx)
        response_text = result["response"]

    except Exception as e:
        # Handle unexpected exception
        response_text = f"[ERROR] {e}"
        image_urls = [c.get("image") for c in msg.get("qa", []) if c.get("type") == "image"]
        failed_row = {
            "row": row_idx,
            "response": response_text,
            "error": str(e),
            "traceback": traceback.format_exc(),
            "question": msg.get("qa", []),
            "image_urls": image_urls
        }

        sample.at[row_idx, "generated_response"] = response_text

        # Save to failed file
        with open(failure_output_path, "a") as f:
            f.write(json.dumps(failed_row) + "\n")
        continue

    # Update DataFrame
    sample.at[row_idx, "generated_response"] = response_text

    # Print first sample
    if row_idx == 0:
        print("\n#Prompt:##\n")
        print(message["content"])
        print("\n##Sample Response:##\n")
        print(response_text)

    # Build row
    row_data = {
        "row": row_idx,
        "response": response_text,
        "image_urls": image_urls
    }
    sample_results.append(row_data)

    # Split output based on success/failure
    if response_text.startswith("[ERROR]"):
        failed_row = {
            "row": row_idx,
            "response": response_text,
            "error": response_text,
            "traceback": result.get("traceback", ""),
            "question": msg.get("qa", []),
            "image_urls": image_urls
        }
        with open(failure_output_path, "a") as f:
            f.write(json.dumps(failed_row) + "\n")
    else:
        with open(success_output_path, "a") as f:
            f.write(json.dumps(row_data) + "\n")

/tmp/ipykernel_791/1180642016.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample["generated_response"] = None
Processing Messages:   0%|          | 0/5 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  20%|██        | 1/5 [00:42<02:51, 42.81s/it]

#Prompt:##

[{'type': 'image', 'image': 'https://i.sstatic.net/QQmRh.png'}, {'type': 'text', 'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Some recently changed resources are not yet published\nbody: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I\'ve tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?\n\nAnswer:\n'}]

##Sample Response:##

The error message "Some recently changed resources are not yet published" is a common issue in Google App Engine (GAE) development. This error occurs when the GAE server is unable to detect changes made to the project's resources, such as Java classes, HTML files, or other assets, and therefore uses the old code instead of the updated version.

To resolve this issue, you can try the following steps:

1. **Clean and rebuild the project**: Go to Project > Clean in Eclipse, then select the project and click Clean. This will delete all temporary files and rebuild the project.
2. **Restart Eclipse**: Sometimes, a simple restart of Eclipse can resolve the issue.
3. **Delete the .metadata directory**: The .metadata directory contains configuration files for Eclipse. Deleting it may resolve the issue. However, be aware that this will delete all your project settings, so make sure to back up your project before doing so.
4. **Check the project's configuration**: Ensure that the project's configuration is correct. Check the project's properties, especially the "Google App Engine" settings, to ensure that the correct SDK and project ID are selected.
5. **Update the project's dependencies**: If you're using any third-party libraries or dependencies, ensure that they are up-to-date and compatible with the GAE SDK version you're using.
6. **Try a different launch configuration**: If you've already tried deleting and re-adding the launch configuration, try creating a new one. Go to Run > Run Configurations, select the GAE configuration, and click New. Then, select the project and click Run.
7. **Check for conflicts with other plugins**: If you have other plugins installed in Eclipse, such as Maven or Gradle, they might be interfering with the GAE plugin. Try disabling or uninstalling these plugins to see if the issue persists.
8. **Update the GAE SDK**: Ensure that you're using the latest version of the GAE SDK. You can download the latest version from the Google Cloud Platform Console.
9. **Contact Google support**: If none of the above steps resolve the issue, you can contact Google support for further assistance.

By following these steps, you should be able to resolve the "Some recently changed resources are not yet published" error and deploy your updated code to the GAE server.

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  40%|████      | 2/5 [00:45<00:56, 18.92s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  60%|██████    | 3/5 [01:22<00:55, 27.52s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  80%|████████  | 4/5 [01:48<00:26, 26.98s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages: 100%|██████████| 5/5 [01:52<00:00, 22.54s/it]

In [51]:
# result sample
sample_results[:1]

[{'row': 0,
  'response': 'The error message "Some recently changed resources are not yet published" is a common issue in Google App Engine (GAE) development. This error occurs when the GAE server is unable to detect changes made to the project\'s resources, such as Java classes, HTML files, or other assets, and therefore uses the old code instead of the updated version.\n\nTo resolve this issue, you can try the following steps:\n\n1. **Clean and rebuild the project**: Go to Project > Clean in Eclipse, then select the project and click Clean. This will delete all temporary files and rebuild the project.\n2. **Restart Eclipse**: Sometimes, a simple restart of Eclipse can resolve the issue.\n3. **Delete the .metadata directory**: The .metadata directory contains configuration files for Eclipse. Deleting it may resolve the issue. However, be aware that this will delete all your project settings, so make sure to back up your project before doing so.\n4. **Check the project\'s configuration**: Ensure that the project\'s configuration is correct. Check the project\'s properties, especially the "Google App Engine" settings, to ensure that the correct SDK and project ID are selected.\n5. **Update the project\'s dependencies**: If you\'re using any third-party libraries or dependencies, ensure that they are up-to-date and compatible with the GAE SDK version you\'re using.\n6. **Try a different launch configuration**: If you\'ve already tried deleting and re-adding the launch configuration, try creating a new one. Go to Run > Run Configurations, select the GAE configuration, and click New. Then, select the project and click Run.\n7. **Check for conflicts with other plugins**: If you have other plugins installed in Eclipse, such as Maven or Gradle, they might be interfering with the GAE plugin. Try disabling or uninstalling these plugins to see if the issue persists.\n8. **Update the GAE SDK**: Ensure that you\'re using the latest version of the GAE SDK. You can download the latest version from the Google Cloud Platform Console.\n9. **Contact Google support**: If none of the above steps resolve the issue, you can contact Google support for further assistance.\n\nBy following these steps, you should be able to resolve the "Some recently changed resources are not yet published" error and deploy your updated code to the GAE server.',
  'image_urls': ['https://i.sstatic.net/QQmRh.png']}]

In [52]:
sample['zero-shot-prompt'] = setup_messages(sample, prompt_column="zero-shot-question")

/tmp/ipykernel_791/536900671.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['zero-shot-prompt'] = setup_messages(sample, prompt_column="zero-shot-question")

In [53]:
sample.head(2)

,context,gt,img,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,generated_response,zero-shot-prompt
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,121,127,"The error message ""Some recently changed resou...","{'role': 'user', 'qa': [{'type': 'image', 'ima..."
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\r\nI am almost certain that the package path ...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,393,399,[ERROR] CUDA out of memory. Tried to allocate ...,"{'role': 'user', 'qa': [{'type': 'image', 'ima..."

In [54]:
sample.to_csv("sample_vlm_llama_3_2_vl_11b.csv", index=False)

## Cloud

In [48]:
cloud_processed.head(2)

,context,gt,img,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,121,127
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,390,396

### Zero-shot

In [58]:
# Setup messages for mode
cloud_messages = setup_messages(cloud_processed,prompt_column="zero-shot-question")

In [59]:
cloud_messages[:1]

[{'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/QQmRh.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Some recently changed resources are not yet published\nbody: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I\'ve tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?\n\nAnswer:\n'}]}]

In [60]:
cloud_processed.head(2)

,context,gt,img,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero_shot_generated_response
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,121,127,None
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,390,396,None

In [67]:
cloud_messages[1515]

{'role': 'user',
 'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/n8Vw7.png'},
  {'type': 'image', 'image': 'https://i.sstatic.net/EdDPP.png'},
  {'type': 'image', 'image': 'https://i.sstatic.net/pliqf.png'},
  {'type': 'image', 'image': 'https://i.sstatic.net/ITnjX.png'},
  {'type': 'image', 'image': 'https://i.sstatic.net/Ms3Vz.jpg'},
  {'type': 'image', 'image': 'https://i.sstatic.net/bw6Ui.png'},
  {'type': 'image', 'image': 'https://i.sstatic.net/KI2Dn.png'},
  {'type': 'text',
   'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Visual Studio Team Services Continuous Integration: NuGet Restore Task Failed\nbody: I am using Continuous Integration feature in Team Services (was Visual Studio Online). My build definition targets a specific project in a solution (not the whole solution), which is ClientUI MVC website.\n\nThe solution contains three projects:\n\n\nClientUI\nAdminUI\nClient Services\n\n\n\n\nThe Build Definition for ClientUI Project:\n\nRepository:\n\n\n\nNuget Installer Step:\nI have tried different params but not working.\n\n\nVisual Studio Build \n\n\n\nBefore trying to target the a single project, my build definition was targeting the whole solution with the following parameters:\n\n\nNuGet Installer -> Path to Solution: **\\*.sln\nVisual Studio Build -> Solution: **\\*.sln  ; MSBuild Arguments:  /p:outdir=$(build.artifactstagingdirectory) \n\n\nIt was working. However now, it generates this error in the Nugget Restore Task:\n\n\r\n\r\n2016-04-22T21:07:00.6716725Z Set workingFolder to default: C:\\LR\\MMS\\Services\\Mms\\TaskAgentProvisioner\\Tools\\agents\\1.98.1\\tasks\\NuGetInstaller\\0.1.25\r\n2016-04-22T21:07:00.8163908Z Executing the powershell script: C:\\LR\\MMS\\Services\\Mms\\TaskAgentProvisioner\\Tools\\agents\\1.98.1\\tasks\\NuGetInstaller\\0.1.25\\NuGetInstaller.ps1\r\n\r\n\r\n2016-04-22T21:07:01.5283529Z ##[error]Cannot find path \'C:\\a\\1\\s\\packages.config\' because it does not exist.\r\n2016-04-22T21:07:01.5439897Z C:\\LR\\MMS\\Services\\Mms\\TaskAgentProvisioner\\Tools\\agents\\1.98.1\\agent\\worker\\tools\\NuGet.exe restore "C:\\a\\1\\s\\packages.config"  -NonInteractive\r\n\r\n\r\n2016-04-22T21:07:03.0441507Z MSBuild auto-detection: using msbuild version \'14.0\' from \'C:\\Program Files (x86)\\MSBuild\\14.0\\bin\'.\r\n\r\n\r\n2016-04-22T21:07:03.0597010Z ##[error]Cannot determine the packages folder to restore NuGet packages. Please specify either -PackagesDirectory or -SolutionDirectory.\r\n2016-04-22T21:07:03.0909881Z ##[error]Unexpected exit code 1 returned from tool NuGet.exe\n\nAnswer:\n'}]}

#### Get response

In [68]:
# Output setup
cloud_logs_zero_shot_results = []
success_output_path ="vlm_cloud_llama_3_2_vl_11b_zero_shot_results.jsonl"
failure_output_path = "failed_response_cloud_zero_shot.jsonl"

cloud_processed["zero_shot_generated_response"] = None

# Clear output files first
with open(success_output_path, "w"): pass
with open(failure_output_path, "w"): pass

start_index= 1514
# Process each message
for row_idx, msg in enumerate(tqdm(cloud_messages[1514:], desc="Processing Messages")):
    try:
        # Build message
        qa_content = msg.get("qa", [])
        message = {
            "role": msg.get("role", "user"),
            "content": qa_content
        }

        # Extract image URLs
        image_urls = [c.get("image") for c in qa_content if c.get("type") == "image"]

        # Run inference
        result = process_message(message, idx=row_idx)
        response_text = result["response"]

    except Exception as e:
        # Handle unexpected exception
        response_text = f"[ERROR] {e}"
        image_urls = [c.get("image") for c in msg.get("qa", []) if c.get("type") == "image"]
        failed_row = {
            "row": row_idx + start_index,
            "response": response_text,
            "error": str(e),
            "traceback": traceback.format_exc(),
            "question": msg.get("qa", []),
            "image_urls": image_urls
        }

        cloud_processed.at[row_idx, "zero_shot_generated_response"] = response_text

        # Save to failed file
        with open(failure_output_path, "a") as f:
            f.write(json.dumps(failed_row) + "\n")
        continue

    # Update DataFrame
    cloud_processed.at[row_idx, "zero_shot_generated_response"] = response_text

    # Print first sample
    if row_idx == 0:
        print("\n#Prompt:##\n")
        print(message["content"])
        print("\n##Sample Response:##\n")
        print(response_text)

    # Build row
    row_data = {
        "row": row_idx + start_index,
        "response": response_text,
        "image_urls": image_urls
    }
    cloud_logs_zero_shot_results.append(row_data)

    # Split output based on success/failure
    if response_text.startswith("[ERROR]"):
        failed_row = {
            "row": row_idx + start_index,
            "response": response_text,
            "error": response_text,
            "traceback": result.get("traceback", ""),
            "question": msg.get("qa", []),
            "image_urls": image_urls
        }
        with open(failure_output_path, "a") as f:
            f.write(json.dumps(failed_row) + "\n")
    else:
        with open(success_output_path, "a") as f:
            f.write(json.dumps(row_data) + "\n")

Processing Messages:   0%|          | 0/108 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 1/108 [01:48<3:13:59, 108.78s/it]

#Prompt:##

[{'type': 'image', 'image': 'https://i.sstatic.net/dc8dP.png'}, {'type': 'image', 'image': 'https://i.sstatic.net/9QXJW.png'}, {'type': 'text', 'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Run "node test" as part of Visual Studio Team Services build task with results in "tests" tab\nbody: I have a project that contains tests that I am running with Mocha from the command line. I have set up a test script in my packages.json, which looks as follows:\n\n"test": "mocha ./**/*.spec.js --reporter dot --require jsdom-global/register"\n\nI have currently got a simple task set up in Visual Studio Team Services, which just runs the npm test command, this runs Mocha within a console and continues/fails the build depending on whether the tests pass.\n\nWhat I\'d like to be able to do is have the results of my tests populate the "tests" tab in the build definition after it\'s run. In the same way that I can get this tab populated if I\'m running tests on C# code.\n\nI\'ve tried using Chutzpah for this, but it\'s overly complicated and seems to require that I jump through all sorts of hoops that mean changing my tests and writing long config files. I already have loads of tests written, so really don\'t want to have to do that. When it did finally discover any of my tests, it complained about require and other things related to Node modules.\n\nIs what I\'m asking for actually possible? Is there a simple way of achieving this that\'s compatible with running my tests in Node?\n\nAnswer:\n'}]

##Sample Response:##

Yes, it is possible to publish test results in the "tests" tab of a Visual Studio Team Services build definition for Node.js tests. You can use the "Publish Test Results" task in your build definition to achieve this.

Here's an example of how you can configure the task:

1. Add a new task to your build definition and select "Publish Test Results" as the task type.
2. In the "Test Results Files" field, enter the path to your test results file, which is typically generated by Mocha. For example, if your test script is running in the root of your project, the file path might be `test-results.xml`.
3. In the "Test Results File Pattern" field, enter a pattern that matches the test results file. For example, `**/test-results.xml`.
4. In the "Test Run Title" field, enter a title for your test run. This will be displayed in the "tests" tab of the build definition.

Here's an example of what the task configuration might look like:

| Task | Value |
| --- | --- |
| Test Results Files | test-results.xml |
| Test Results File Pattern | **/test-results.xml |
| Test Run Title | My Node.js Tests |

Once you've configured the task, save and queue your build. The test results should be published to the "tests" tab of the build definition.

Note that you may need to adjust the file path and pattern to match the location of your test results file. Additionally, make sure that the test results file is generated correctly by Mocha and that it contains the necessary information for the "Publish Test Results" task to work correctly.

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 2/108 [01:53<1:24:27, 47.80s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 3/108 [02:53<1:33:17, 53.31s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 4/108 [05:17<2:34:22, 89.06s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 5/108 [05:23<1:41:13, 58.96s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 6/108 [06:28<1:43:39, 60.97s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▋         | 7/108 [10:52<3:34:32, 127.45s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 8/108 [12:01<3:01:15, 108.76s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 9/108 [15:03<3:37:36, 131.88s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 10/108 [15:09<2:31:48, 92.94s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|█         | 11/108 [19:01<3:39:03, 135.50s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  11%|█         | 12/108 [21:40<3:48:14, 142.65s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  12%|█▏        | 13/108 [22:56<3:14:04, 122.57s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  13%|█▎        | 14/108 [23:29<2:29:11, 95.23s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▍        | 15/108 [24:09<2:02:08, 78.80s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  15%|█▍        | 16/108 [24:15<1:27:12, 56.87s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  16%|█▌        | 17/108 [26:53<2:12:18, 87.23s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  17%|█▋        | 18/108 [27:45<1:54:48, 76.54s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  18%|█▊        | 19/108 [29:23<2:03:03, 82.97s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  19%|█▊        | 20/108 [31:15<2:14:37, 91.80s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  19%|█▉        | 21/108 [32:42<2:11:08, 90.44s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  20%|██        | 22/108 [33:43<1:56:52, 81.54s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  21%|██▏       | 23/108 [35:11<1:58:03, 83.34s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  22%|██▏       | 24/108 [35:17<1:24:31, 60.37s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  23%|██▎       | 25/108 [36:11<1:20:36, 58.28s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  24%|██▍       | 26/108 [36:17<58:22, 42.71s/it]  The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  25%|██▌       | 27/108 [36:47<52:19, 38.75s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  26%|██▌       | 28/108 [37:34<55:11, 41.40s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  27%|██▋       | 29/108 [38:51<1:08:21, 51.92s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  28%|██▊       | 30/108 [38:58<49:54, 38.39s/it]  The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  29%|██▊       | 31/108 [39:03<36:39, 28.56s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  30%|██▉       | 32/108 [41:42<1:25:31, 67.52s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  31%|███       | 33/108 [43:42<1:44:07, 83.29s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  31%|███▏      | 34/108 [45:22<1:49:05, 88.45s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  32%|███▏      | 35/108 [45:29<1:17:52, 64.01s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  33%|███▎      | 36/108 [46:56<1:25:10, 70.98s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  34%|███▍      | 37/108 [49:35<1:55:11, 97.35s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  35%|███▌      | 38/108 [50:43<1:43:10, 88.44s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  36%|███▌      | 39/108 [53:18<2:04:51, 108.57s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  37%|███▋      | 40/108 [55:02<2:01:19, 107.06s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  38%|███▊      | 41/108 [56:30<1:53:12, 101.38s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  39%|███▉      | 42/108 [58:01<1:47:59, 98.17s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  40%|███▉      | 43/108 [1:00:08<1:55:49, 106.91s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  41%|████      | 44/108 [1:00:15<1:22:04, 76.95s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  42%|████▏     | 45/108 [1:01:41<1:23:33, 79.57s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  43%|████▎     | 46/108 [1:02:51<1:19:21, 76.79s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  44%|████▎     | 47/108 [1:04:41<1:28:14, 86.79s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  44%|████▍     | 48/108 [1:06:26<1:32:06, 92.12s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  45%|████▌     | 49/108 [1:07:14<1:17:41, 79.01s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  46%|████▋     | 50/108 [1:08:18<1:12:01, 74.51s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  47%|████▋     | 51/108 [1:08:54<59:47, 62.93s/it]  The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  48%|████▊     | 52/108 [1:10:56<1:15:17, 80.68s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  49%|████▉     | 53/108 [1:13:00<1:25:41, 93.48s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  50%|█████     | 54/108 [1:15:00<1:31:25, 101.57s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  51%|█████     | 55/108 [1:15:06<1:04:19, 72.83s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  52%|█████▏    | 56/108 [1:15:53<56:33, 65.25s/it]  The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  53%|█████▎    | 57/108 [1:16:00<40:22, 47.51s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  54%|█████▎    | 58/108 [1:16:20<32:46, 39.33s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  55%|█████▍    | 59/108 [1:17:16<36:21, 44.51s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  56%|█████▌    | 60/108 [1:19:27<56:11, 70.25s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  56%|█████▋    | 61/108 [1:19:43<42:23, 54.11s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  57%|█████▋    | 62/108 [1:20:44<43:04, 56.18s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  58%|█████▊    | 63/108 [1:20:51<31:02, 41.39s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  59%|█████▉    | 64/108 [1:21:20<27:36, 37.65s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  60%|██████    | 65/108 [1:21:27<20:23, 28.45s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  61%|██████    | 66/108 [1:21:34<15:26, 22.06s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  62%|██████▏   | 67/108 [1:22:00<15:57, 23.35s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  63%|██████▎   | 68/108 [1:22:06<12:04, 18.11s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  64%|██████▍   | 69/108 [1:22:22<11:13, 17.26s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  65%|██████▍   | 70/108 [1:23:23<19:20, 30.53s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  66%|██████▌   | 71/108 [1:25:36<37:42, 61.15s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  67%|██████▋   | 72/108 [1:25:42<26:45, 44.61s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  69%|██████▊   | 74/108 [1:26:38<19:07, 33.76s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  69%|██████▉   | 75/108 [1:28:15<28:55, 52.60s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  70%|███████   | 76/108 [1:29:30<31:44, 59.53s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  71%|███████▏  | 77/108 [1:31:36<41:02, 79.42s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  72%|███████▏  | 78/108 [1:33:34<45:30, 91.03s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  73%|███████▎  | 79/108 [1:35:18<45:46, 94.70s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  74%|███████▍  | 80/108 [1:35:24<31:51, 68.25s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  75%|███████▌  | 81/108 [1:36:51<33:14, 73.86s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  76%|███████▌  | 82/108 [1:36:56<22:59, 53.06s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  77%|███████▋  | 83/108 [1:39:48<37:02, 88.89s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  78%|███████▊  | 84/108 [1:39:55<25:39, 64.15s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  79%|███████▊  | 85/108 [1:42:03<31:59, 83.46s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  80%|███████▉  | 86/108 [1:42:09<22:04, 60.18s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  81%|████████  | 87/108 [1:43:11<21:14, 60.69s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  81%|████████▏ | 88/108 [1:44:43<23:24, 70.21s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  82%|████████▏ | 89/108 [1:46:17<24:30, 77.37s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  83%|████████▎ | 90/108 [1:49:00<30:54, 103.01s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  84%|████████▍ | 91/108 [1:51:13<31:41, 111.85s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  85%|████████▌ | 92/108 [1:52:38<27:41, 103.82s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  86%|████████▌ | 93/108 [1:53:50<23:36, 94.43s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  87%|████████▋ | 94/108 [1:57:15<29:44, 127.49s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

In [69]:
cloud_processed['zero-shot-prompt'] = setup_messages(cloud_processed, prompt_column="zero-shot-question")

In [70]:
cloud_processed.head(2)

,context,gt,img,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero_shot_generated_response,zero-shot-prompt
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,121,127,"Yes, it is possible to publish test results in...","{'role': 'user', 'qa': [{'type': 'image', 'ima..."
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,390,396,[ERROR] CUDA out of memory. Tried to allocate ...,"{'role': 'user', 'qa': [{'type': 'image', 'ima..."

In [60]:
cloud_processed.to_excel("../responses/cloud/vlm_response_cloud_llama_3_1_8b_instruct.xlsx", index=False)

### CoT

In [72]:
# Setup messages for mode
cloud_messages = setup_messages(cloud_processed,prompt_column="cot-question")

In [73]:
cloud_messages[0:1]

[{'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/QQmRh.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\nQuestion:\ntitle: Some recently changed resources are not yet published\nbody: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I\'ve tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?\n\nLets think step by step:\nAnswer:\n'}]}]

In [74]:
cloud_processed.head(2)

,context,gt,img,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,zero_shot_generated_response,zero-shot-prompt
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,121,127,"Yes, it is possible to publish test results in...","{'role': 'user', 'qa': [{'type': 'image', 'ima..."
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,390,396,[ERROR] CUDA out of memory. Tried to allocate ...,"{'role': 'user', 'qa': [{'type': 'image', 'ima..."

In [77]:
cloud_messages[1000]

{'role': 'user',
 'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/k6Xia.png'},
  {'type': 'image', 'image': 'https://i.sstatic.net/NocKP.png'},
  {'type': 'text',
   'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\nQuestion:\ntitle: AWS AppSync: pass arguments from parent resolver to children\nbody: In AWS AppSync, arguments send on the main query don\'t seem to be forwarded to all children resolvers.\ntype Query {\n  article(id: String!, consistentRead: Boolean): Article\n  book(id: String!, consistentRead: Boolean): Book\n}\n\ntype Article {\n  title: String!\n  id: String!\n}\n\ntype Book {\n  articleIds: [String]!\n  articles: [Article]!\n  id: String!\n}\n\nwhen I call:\nquery GetBook {\n  book(id: 123, consistentRead: true) {\n    articles {\n      title\n    }\n  }\n}\n\nthe first query to get the book receives the consistentRead param in $context.arguments, but the subsequent query to retrieve the article does not. ($context.arguments is empty)\nI also tried articles(consistentRead: Boolean): [Article]! inside book but no luck.\nDoes anyone know if it\'s possible in AppSync to pass arguments to all queries part of the same request?\n\nLets think step by step:\nAnswer:\n'}]}

#### Get response

In [ ]:
# Output setup
cloud_logs_cot_results = []
success_output_path ="vlm_cloud_llama_3_2_vl_11b_cot_results.jsonl"
failure_output_path = "failed_response_cloud_cot.jsonl"

cloud_processed["cot_generated_response"] = None

# Clear output files first
with open(success_output_path, "w"): pass
with open(failure_output_path, "w"): pass
start_index= 1000
# Process each message
for row_idx, msg in enumerate(tqdm(cloud_messages[1000:], desc="Processing Messages")):
    try:
        # Build message
        qa_content = msg.get("qa", [])
        message = {
            "role": msg.get("role", "user"),
            "content": qa_content
        }

        # Extract image URLs
        image_urls = [c.get("image") for c in qa_content if c.get("type") == "image"]

        # Run inference
        result = process_message(message, idx=row_idx)
        response_text = result["response"]

    except Exception as e:
        # Handle unexpected exception
        response_text = f"[ERROR] {e}"
        image_urls = [c.get("image") for c in msg.get("qa", []) if c.get("type") == "image"]
        failed_row = {
            "row": row_idx + start_index,
            "response": response_text,
            "error": str(e),
            "traceback": traceback.format_exc(),
            "question": msg.get("qa", []),
            "image_urls": image_urls
        }

        cloud_processed.at[row_idx, "cot_generated_response"] = response_text

        # Save to failed file
        with open(failure_output_path, "a") as f:
            f.write(json.dumps(failed_row) + "\n")
        continue

    # Update DataFrame
    cloud_processed.at[row_idx, "cot_generated_response"] = response_text

    # Print first sample
    if row_idx == 0:
        print("\n#Prompt:##\n")
        print(message["content"])
        print("\n##Sample Response:##\n")
        print(response_text)

    # Build row
    row_data = {
        "row": row_idx + start_index,
        "response": response_text,
        "image_urls": image_urls
    }
    cloud_logs_cot_results.append(row_data)

    # Split output based on success/failure
    if response_text.startswith("[ERROR]"):
        failed_row = {
            "row": row_idx + start_index,
            "response": response_text,
            "error": response_text,
            "traceback": result.get("traceback", ""),
            "question": msg.get("qa", []),
            "image_urls": image_urls
        }
        with open(failure_output_path, "a") as f:
            f.write(json.dumps(failed_row) + "\n")
    else:
        with open(success_output_path, "a") as f:
            f.write(json.dumps(row_data) + "\n")

Processing Messages:   0%|          | 0/622 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 1/622 [03:02<31:30:20, 182.64s/it]

#Prompt:##

[{'type': 'image', 'image': 'https://i.sstatic.net/k6Xia.png'}, {'type': 'image', 'image': 'https://i.sstatic.net/NocKP.png'}, {'type': 'text', 'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\nQuestion:\ntitle: AWS AppSync: pass arguments from parent resolver to children\nbody: In AWS AppSync, arguments send on the main query don\'t seem to be forwarded to all children resolvers.\ntype Query {\n  article(id: String!, consistentRead: Boolean): Article\n  book(id: String!, consistentRead: Boolean): Book\n}\n\ntype Article {\n  title: String!\n  id: String!\n}\n\ntype Book {\n  articleIds: [String]!\n  articles: [Article]!\n  id: String!\n}\n\nwhen I call:\nquery GetBook {\n  book(id: 123, consistentRead: true) {\n    articles {\n      title\n    }\n  }\n}\n\nthe first query to get the book receives the consistentRead param in $context.arguments, but the subsequent query to retrieve the article does not. ($context.arguments is empty)\nI also tried articles(consistentRead: Boolean): [Article]! inside book but no luck.\nDoes anyone know if it\'s possible in AppSync to pass arguments to all queries part of the same request?\n\nLets think step by step:\nAnswer:\n'}]

##Sample Response:##

To pass arguments from a parent resolver to child resolvers in AWS AppSync, you can use the `$context.arguments` object. However, this object is only available in the resolver that is called directly by the client. In your case, the first query to get the book receives the `consistentRead` parameter in `$context.arguments`, but the subsequent query to retrieve the article does not.

The reason for this is that the `$context.arguments` object is not propagated to child resolvers. To pass arguments to all queries part of the same request, you can use a different approach.

One solution is to use a custom directive to pass the arguments to the child resolvers. You can create a custom directive that takes the arguments as input and then calls the child resolvers with those arguments.

Here's an example of how you can define a custom directive:

```graphql
directive @passArguments(
  consistentRead: Boolean = false
) on FIELD_DEFINITION

type Query {
  article(id: String!, consistentRead: Boolean @passArguments): Article
  book(id: String!, consistentRead: Boolean @passArguments): Book
}

type Article {
  title: String!
  id: String!
}

type Book {
  articleIds: [String]!
  articles: [Article]!
  id: String!
}
```

In the resolver for the `book` field, you can then use the `@passArguments` directive to pass the `consistentRead` argument to the child resolvers:

```graphql
type Query {
  book(id: String!, consistentRead: Boolean @passArguments): Book {
    articles {
      title
    }
  }
}
```

In the resolver for the `articles` field, you can then use the `@passArguments` directive to pass the `consistentRead` argument to the `article` resolver:

```graphql
type Query {
  book(id: String!, consistentRead: Boolean @passArguments): Book {
    articles {
      title @passArguments
    }
  }
}
```

By using the `@passArguments` directive, you can pass the `consistentRead` argument to all child resolvers, including the `article` resolver.

Note that this approach requires you to define a custom directive and modify the schema to include the `@passArguments` directive on the fields that need to receive the arguments. Additionally, you need to update the resolvers to use the `@passArguments` directive to pass the arguments to the child resolvers.

Alternatively, you can also use a different approach, such as using a custom resolver function that takes the arguments as input and calls the child resolvers with those arguments. However, this approach requires more complex code and may not be as straightforward as using a custom directive.

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 2/622 [05:03<25:11:14, 146.25s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 3/622 [06:52<22:12:50, 129.19s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 4/622 [08:54<21:40:42, 126.28s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 5/622 [10:38<20:18:00, 118.45s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 6/622 [12:24<19:31:46, 114.13s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 7/622 [16:16<26:05:26, 152.73s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|▏         | 8/622 [16:22<18:03:25, 105.87s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|▏         | 9/622 [16:28<12:44:18, 74.81s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 10/622 [17:43<12:44:37, 74.96s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 11/622 [17:51<9:13:43, 54.37s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 12/622 [19:35<11:44:58, 69.34s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 13/622 [20:56<12:19:55, 72.90s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 14/622 [24:49<20:29:53, 121.37s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 15/622 [24:56<14:37:42, 86.76s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 16/622 [26:24<14:41:08, 87.24s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 17/622 [28:25<16:20:24, 97.23s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 18/622 [29:45<15:29:05, 92.29s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 19/622 [32:28<19:00:59, 113.53s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 20/622 [34:47<20:14:44, 121.07s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 21/622 [36:03<17:57:19, 107.55s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 22/622 [37:23<16:32:56, 99.29s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 23/622 [39:23<17:34:16, 105.60s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 24/622 [40:55<16:50:33, 101.39s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 25/622 [43:48<20:22:50, 122.90s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 26/622 [43:55<14:33:44, 87.96s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 27/622 [47:02<19:27:04, 117.69s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 28/622 [49:09<19:52:44, 120.48s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 29/622 [50:57<19:15:20, 116.90s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 30/622 [51:59<16:29:55, 100.33s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 31/622 [53:19<15:27:48, 94.19s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 32/622 [54:56<15:34:25, 95.03s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 33/622 [56:46<16:18:22, 99.66s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 34/622 [59:28<19:20:15, 118.39s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 35/622 [1:01:27<19:19:04, 118.47s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 36/622 [1:03:39<19:58:03, 122.67s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 37/622 [1:05:43<19:58:36, 122.94s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 38/622 [1:08:10<21:08:02, 130.28s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▋         | 39/622 [1:09:49<19:34:36, 120.89s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▋         | 40/622 [1:12:02<20:07:32, 124.49s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 41/622 [1:14:05<20:02:03, 124.14s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 42/622 [1:14:31<15:15:00, 94.66s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 43/622 [1:16:35<16:36:47, 103.29s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 44/622 [1:18:05<15:56:07, 99.25s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 45/622 [1:19:58<16:34:41, 103.43s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 46/622 [1:22:39<19:18:15, 120.65s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 47/622 [1:23:54<17:07:21, 107.20s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 48/622 [1:24:01<12:15:58, 76.93s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 49/622 [1:25:15<12:08:03, 76.24s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 50/622 [1:27:55<16:05:19, 101.26s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 51/622 [1:29:48<16:38:05, 104.88s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 52/622 [1:31:35<16:41:23, 105.41s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▊         | 53/622 [1:32:54<15:25:52, 97.63s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▊         | 54/622 [1:36:13<20:11:55, 128.02s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 55/622 [1:38:13<19:47:09, 125.63s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 56/622 [1:40:36<20:32:30, 130.65s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 57/622 [1:41:45<17:35:59, 112.14s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 58/622 [1:44:10<19:07:56, 122.12s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 59/622 [1:46:59<21:17:43, 136.17s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|▉         | 60/622 [1:47:10<15:23:42, 98.62s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|▉         | 61/622 [1:49:05<16:09:02, 103.64s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|▉         | 62/622 [1:50:03<13:58:29, 89.84s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|█         | 63/622 [1:51:52<14:50:42, 95.60s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|█         | 64/622 [1:54:23<17:24:03, 112.26s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|█         | 65/622 [1:56:40<18:31:15, 119.70s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  11%|█         | 66/622 [1:58:43<18:37:03, 120.55s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  11%|█         | 67/622 [2:01:30<20:45:06, 134.61s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  11%|█         | 68/622 [2:04:06<21:41:41, 140.98s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  11%|█         | 69/622 [2:05:56<20:14:11, 131.74s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  11%|█▏        | 70/622 [2:07:37<18:47:32, 122.56s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  11%|█▏        | 71/622 [2:09:51<19:16:28, 125.93s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  12%|█▏        | 72/622 [2:12:27<20:35:22, 134.77s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  12%|█▏        | 73/622 [2:14:05<18:54:25, 123.98s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  12%|█▏        | 74/622 [2:15:53<18:06:48, 118.99s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  12%|█▏        | 75/622 [2:19:08<21:32:21, 141.76s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  12%|█▏        | 76/622 [2:21:06<20:26:12, 134.75s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  12%|█▏        | 77/622 [2:25:00<24:53:06, 164.38s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  13%|█▎        | 78/622 [2:27:10<23:18:25, 154.24s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  13%|█▎        | 79/622 [2:28:43<20:29:47, 135.89s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  13%|█▎        | 80/622 [2:30:01<17:51:17, 118.59s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  13%|█▎        | 81/622 [2:31:54<17:31:46, 116.65s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  13%|█▎        | 82/622 [2:33:31<16:38:03, 110.90s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  13%|█▎        | 83/622 [2:36:41<20:09:52, 134.68s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▎        | 84/622 [2:38:26<18:45:50, 125.56s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▎        | 85/622 [2:38:31<13:22:29, 89.66s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▍        | 86/622 [2:40:24<14:23:10, 96.62s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▍        | 87/622 [2:42:39<16:02:59, 108.00s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▍        | 88/622 [2:44:59<17:26:04, 117.54s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▍        | 89/622 [2:48:11<20:42:51, 139.91s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▍        | 90/622 [2:50:13<19:53:24, 134.59s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  15%|█▍        | 91/622 [2:52:56<21:07:18, 143.20s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  15%|█▍        | 92/622 [2:55:31<21:36:03, 146.72s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

In [ ]:
cloud_processed['cot-prompt'] = setup_messages(cloud_processed, prompt_column="cot-question")

In [ ]:
cloud_processed.head(2)

In [68]:
cloud_processed.to_excel("../responses/cloud/vlm_response_cloud_llama_3_1_8b_instruct_cot.xlsx", index=False)

## Device

In [45]:
device_processed.head(2)

,context,gt,img,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: What is the purpose of the INPUT chain ...,\nIf some NAT operation needs to be only done ...,['https://i.sstatic.net/NUh2k.png'],\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,151,157
1,"title: Logstash JDBC input, filter event times...",\nOK I finally figure how to get the @timestam...,"['https://i.sstatic.net/3nAZ9.png', 'https://i...",\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,557,563

### Zero-Shot

In [46]:
# Setup messages for mode
device_messages = setup_messages(device_processed,prompt_column="zero-shot-question")

In [47]:
device_messages[:2]

[{'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/NUh2k.png'},
   {'type': 'text',
    'text': '\nYou are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: What is the purpose of the INPUT chain in the nat table?\nbody: What is the purpose of the INPUT chain in the nat table ?\n\nThe PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".\n\nThe nat:INPUT and nat:PREROUTING chains seem redundant.\n\nWhat would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?\n\nAnswer:\n\n'}]},
 {'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/3nAZ9.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/bsoVL.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/wM2pW.png'},
   {'type': 'text',
    'text': '\nYou are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Logstash JDBC input, filter event timestamp different to @timestamp\nbody: I am trying to change the @timestamp to match my timestamp, this is the time my event occurred at not when logstash time stamped it.\n\nhere is my conf file\n\ninput {\n jdbc {\n   jdbc_driver_library => "C:/logstash/lib/mysql-connector-java-5.1.37-bin.jar"\n   jdbc_driver_class => "com.mysql.jdbc.Driver"\n   jdbc_connection_string => "jdbc:mysql://127.0.0.1:3306/transport"\n   jdbc_user => "root"\n   jdbc_password => ""\n   schedule => "* * * * *"\n   statement => "select id, timestamp, type, service, data, success, trans_id from audit where timestamp >= :sql_last_start"    \n }\n}\n\nfilter {\n    date {\n      match => [ "timestamp", "YYYY-MM-dd HH:mm:ss,SSS" ]\n      add_tag => [ "tsmatch" ]\n}\n}\n\noutput {\n  elasticsearch {\n     hosts => ["127.0.0.1:9200"]\n     index => "audit-%{+YYYY.MM.dd}"\n     document_id => "%{id}"\n }\n stdout {\n     codec => rubydebug\n }  \n}\n\n\nOut put\n\n{\n        "id" => 32,\n "timestamp" => 2015-11-18 18:21:44 +0000,\n      "type" => "Scheduled",\n   "service" => "Road",\n      "data" => "Changing the time",\n   "success" => 1,\n  "trans_id" => "ta819rsc",\n  "@version" => "1",\n"@timestamp" => "2015-11-18T18:22:00.069Z",\n      "tags" => [\n    [0] "_dateparsefailure"\n]\n}\n\n\nElasticsearch\n\n\n\nAs can be seen, the timestamps (times) are different. This will mess up my data when I bring it into Kibana as I want the histogram to filter on when the event happened not when logstash gave it the timestamp.\n\nCan some one provide me with the work around.\n\nUPDATE:\n\nI have changed the filter as suggested to \n\nmatch => [ "timestamp", "YYYY-MM-dd HH:mm:ss ZZZ" ] \n\n\nand the times are still out, and get the same _dateparsefailure in response. Would it have anything to do with the fact it\'s a Datestamp from MySQL and it can\'t be converted?\n\nG\n\nAnswer:\n\n'}]}]

#### Get response

In [ ]:
# Output setup
device_logs_zero_shot_results = []
success_output_path ="vlm_device_llama_3_2_vl_11b_zero_shot_results.jsonl"
failure_output_path = "failed_response_device_zero_shot.jsonl"

device_processed["zero_shot_generated_response"] = None

# Clear output files first
with open(success_output_path, "w"): pass
with open(failure_output_path, "w"): pass

# Process each message
for row_idx, msg in enumerate(tqdm(device_messages, desc="Processing Messages")):
    try:
        # Build message
        qa_content = msg.get("qa", [])
        message = {
            "role": msg.get("role", "user"),
            "content": qa_content
        }

        # Extract image URLs
        image_urls = [c.get("image") for c in qa_content if c.get("type") == "image"]

        # Run inference
        result = process_message(message, idx=row_idx)
        response_text = result["response"]

    except Exception as e:
        # Handle unexpected exception
        response_text = f"[ERROR] {e}"
        image_urls = [c.get("image") for c in msg.get("qa", []) if c.get("type") == "image"]
        failed_row = {
            "row": row_idx,
            "response": response_text,
            "error": str(e),
            "traceback": traceback.format_exc(),
            "question": msg.get("qa", []),
            "image_urls": image_urls
        }

        device_processed.at[row_idx, "zero_shot_generated_response"] = response_text

        # Save to failed file
        with open(failure_output_path, "a") as f:
            f.write(json.dumps(failed_row) + "\n")
        continue

    # Update DataFrame
    device_processed.at[row_idx, "zero_shot_generated_response"] = response_text

    # Print first sample
    if row_idx == 0:
        print("\n#Prompt:##\n")
        print(message["content"])
        print("\n##Sample Response:##\n")
        print(response_text)

    # Build row
    row_data = {
        "row": row_idx,
        "response": response_text,
        "image_urls": image_urls
    }
    device_logs_zero_shot_results.append(row_data)

    # Split output based on success/failure
    if response_text.startswith("[ERROR]"):
        failed_row = {
            "row": row_idx,
            "response": response_text,
            "error": response_text,
            "traceback": result.get("traceback", ""),
            "question": msg.get("qa", []),
            "image_urls": image_urls
        }
        with open(failure_output_path, "a") as f:
            f.write(json.dumps(failed_row) + "\n")
    else:
        with open(success_output_path, "a") as f:
            f.write(json.dumps(row_data) + "\n")

Processing Messages:   0%|          | 0/993 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 1/993 [00:15<4:12:52, 15.29s/it]

#Prompt:##

[{'type': 'image', 'image': 'https://i.sstatic.net/NUh2k.png'}, {'type': 'text', 'text': '\nYou are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: What is the purpose of the INPUT chain in the nat table?\nbody: What is the purpose of the INPUT chain in the nat table ?\n\nThe PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".\n\nThe nat:INPUT and nat:PREROUTING chains seem redundant.\n\nWhat would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?\n\nAnswer:\n\n'}]

##Sample Response:##

The nat:INPUT chain in the nat table is used for the translation of the source addresses (SNAT) of outgoing packets. This is typically used when a host behind a NAT device wants to send packets to a destination that does not support NAT, or when the NAT device needs to translate the source IP address of the packets to a different IP address.

The nat:INPUT chain cannot be accomplished in the nat:PREROUTING chain because the PREROUTING chain only handles incoming packets, whereas the INPUT chain handles outgoing packets. Therefore, the nat:INPUT chain is necessary to perform SNAT on outgoing packets.

*Answer*: The nat:INPUT chain is used for the translation of the source addresses (SNAT) of outgoing packets.

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 2/993 [00:18<2:18:31,  8.39s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 3/993 [00:44<4:26:55, 16.18s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 4/993 [00:48<3:06:08, 11.29s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 5/993 [00:54<2:38:35,  9.63s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 6/993 [01:14<3:32:44, 12.93s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 7/993 [01:32<4:03:40, 14.83s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 8/993 [01:55<4:44:47, 17.35s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 9/993 [02:16<5:01:25, 18.38s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 10/993 [02:48<6:09:16, 22.54s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 11/993 [03:31<7:53:01, 28.90s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 12/993 [03:53<7:17:09, 26.74s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|▏         | 13/993 [03:56<5:18:39, 19.51s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|▏         | 14/993 [04:15<5:19:42, 19.59s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 15/993 [04:41<5:51:13, 21.55s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 16/993 [05:02<5:44:59, 21.19s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 17/993 [05:19<5:27:30, 20.13s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 18/993 [05:38<5:18:13, 19.58s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 19/993 [05:56<5:13:23, 19.31s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 20/993 [06:32<6:32:50, 24.22s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 21/993 [07:05<7:13:01, 26.73s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 22/993 [07:58<9:23:46, 34.84s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 23/993 [08:40<9:56:13, 36.88s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 24/993 [08:52<7:55:19, 29.43s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 25/993 [09:01<6:12:59, 23.12s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 26/993 [09:32<6:55:14, 25.76s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 27/993 [09:35<5:01:09, 18.71s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 28/993 [10:14<6:38:18, 24.77s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 29/993 [10:45<7:11:20, 26.85s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 30/993 [11:59<10:55:31, 40.84s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 31/993 [12:24<9:40:13, 36.19s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 32/993 [12:50<8:49:49, 33.08s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 33/993 [13:21<8:37:10, 32.32s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 34/993 [14:01<9:15:32, 34.76s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 35/993 [14:17<7:45:43, 29.17s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 36/993 [14:43<7:30:48, 28.26s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 37/993 [15:13<7:38:48, 28.80s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 38/993 [15:39<7:25:55, 28.02s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 39/993 [16:11<7:42:56, 29.12s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 40/993 [16:15<5:41:50, 21.52s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 41/993 [17:00<7:32:49, 28.54s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 42/993 [17:03<5:29:12, 20.77s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 43/993 [17:34<6:21:57, 24.12s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 44/993 [17:38<4:45:33, 18.05s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 45/993 [17:57<4:50:12, 18.37s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 46/993 [18:30<5:57:52, 22.67s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 47/993 [18:57<6:17:00, 23.91s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 48/993 [19:01<4:41:59, 17.90s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 49/993 [19:03<3:27:24, 13.18s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 50/993 [19:56<6:35:08, 25.14s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 51/993 [20:33<7:27:48, 28.52s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 52/993 [21:33<9:59:08, 38.20s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 53/993 [21:37<7:16:15, 27.85s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 54/993 [22:02<7:03:24, 27.05s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 55/993 [22:30<7:07:35, 27.35s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 56/993 [22:45<6:08:45, 23.61s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 57/993 [23:29<7:42:19, 29.64s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 58/993 [23:51<7:05:24, 27.30s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 59/993 [24:08<6:19:50, 24.40s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 60/993 [24:33<6:22:43, 24.61s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 61/993 [24:44<5:16:39, 20.39s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 62/993 [25:30<7:13:51, 27.96s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▋         | 63/993 [25:58<7:15:32, 28.10s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▋         | 64/993 [26:02<5:21:15, 20.75s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 65/993 [26:36<6:22:33, 24.73s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 66/993 [26:54<5:53:35, 22.89s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 67/993 [27:03<4:49:12, 18.74s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 68/993 [27:36<5:54:31, 23.00s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 69/993 [28:24<7:47:52, 30.38s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 70/993 [28:59<8:09:32, 31.82s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 71/993 [29:36<8:33:00, 33.38s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 72/993 [30:20<9:20:08, 36.49s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 73/993 [31:04<9:53:21, 38.70s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 74/993 [31:22<8:19:53, 32.64s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 75/993 [31:45<7:35:44, 29.79s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 77/993 [32:14<5:16:29, 20.73s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 78/993 [32:53<6:36:45, 26.02s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 79/993 [33:03<5:24:56, 21.33s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 80/993 [33:26<5:32:50, 21.87s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 81/993 [33:58<6:18:21, 24.89s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 82/993 [34:26<6:31:54, 25.81s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 83/993 [34:57<6:53:15, 27.25s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 84/993 [35:30<7:20:50, 29.10s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▊         | 85/993 [36:12<8:16:09, 32.79s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▊         | 86/993 [36:51<8:46:56, 34.86s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 87/993 [37:26<8:46:51, 34.89s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 88/993 [38:27<10:42:11, 42.58s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 89/993 [39:04<10:18:29, 41.05s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 90/993 [39:27<8:53:50, 35.47s/it] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 91/993 [39:48<7:48:27, 31.16s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 92/993 [40:24<8:09:02, 32.57s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 93/993 [40:57<8:10:29, 32.70s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 94/993 [42:11<11:19:26, 45.35s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

In [ ]:
device_logs_zero_shot_results[:2]

In [ ]:
device_processed['zero-shot-prompt'] = setup_messages(device_processed, prompt_column="zero-shot-question")

In [ ]:
device_processed.head(2)

In [76]:
device_processed.to_excel("../responses/device/vlm_response_device_llama_3_1_8b_instruct.xlsx", index=False)

### CoT

In [77]:
# Setup messages for mode
device_messages = setup_messages(device_processed,prompt_column="cot-question")

In [78]:
device_messages[:2]

[{'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/NUh2k.png'},
   {'type': 'text',
    'text': '\nYou are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\nQuestion:\ntitle: What is the purpose of the INPUT chain in the nat table?\nbody: What is the purpose of the INPUT chain in the nat table ?\r\n\r\nThe PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".\r\n\r\nThe nat:INPUT and nat:PREROUTING chains seem redundant.\r\n\r\nWhat would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?\n\nLets think step by step:\nAnswer:\n'}]},
 {'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/3nAZ9.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/bsoVL.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/wM2pW.png'},
   {'type': 'text',
    'text': '\nYou are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\nQuestion:\ntitle: Logstash JDBC input, filter event timestamp different to @timestamp\nbody: I am trying to change the @timestamp to match my timestamp, this is the time my event occurred at not when logstash time stamped it.\r\n\r\nhere is my conf file\r\n\r\ninput {\r\n jdbc {\r\n   jdbc_driver_library => "C:/logstash/lib/mysql-connector-java-5.1.37-bin.jar"\r\n   jdbc_driver_class => "com.mysql.jdbc.Driver"\r\n   jdbc_connection_string => "jdbc:mysql://127.0.0.1:3306/transport"\r\n   jdbc_user => "root"\r\n   jdbc_password => ""\r\n   schedule => "* * * * *"\r\n   statement => "select id, timestamp, type, service, data, success, trans_id from audit where timestamp >= :sql_last_start"    \r\n }\r\n}\r\n\r\nfilter {\r\n    date {\r\n      match => [ "timestamp", "YYYY-MM-dd HH:mm:ss,SSS" ]\r\n      add_tag => [ "tsmatch" ]\r\n}\r\n}\r\n\r\noutput {\r\n  elasticsearch {\r\n     hosts => ["127.0.0.1:9200"]\r\n     index => "audit-%{+YYYY.MM.dd}"\r\n     document_id => "%{id}"\r\n }\r\n stdout {\r\n     codec => rubydebug\r\n }  \r\n}\r\n\r\n\r\nOut put\r\n\r\n{\r\n        "id" => 32,\r\n "timestamp" => 2015-11-18 18:21:44 +0000,\r\n      "type" => "Scheduled",\r\n   "service" => "Road",\r\n      "data" => "Changing the time",\r\n   "success" => 1,\r\n  "trans_id" => "ta819rsc",\r\n  "@version" => "1",\r\n"@timestamp" => "2015-11-18T18:22:00.069Z",\r\n      "tags" => [\r\n    [0] "_dateparsefailure"\r\n]\r\n}\r\n\r\n\r\nElasticsearch\r\n\r\n\r\n\r\nAs can be seen, the timestamps (times) are different. This will mess up my data when I bring it into Kibana as I want the histogram to filter on when the event happened not when logstash gave it the timestamp.\r\n\r\nCan some one provide me with the work around.\r\n\r\nUPDATE:\r\n\r\nI have changed the filter as suggested to \r\n\r\nmatch => [ "timestamp", "YYYY-MM-dd HH:mm:ss ZZZ" ] \r\n\r\n\r\nand the times are still out, and get the same _dateparsefailure in response. Would it have anything to do with the fact it\'s a Datestamp from MySQL and it can\'t be converted?\r\n\r\nG\n\nLets think step by step:\nAnswer:\n'}]}]

#### Get response

In [ ]:
# Output setup
device_logs_cot_results = []
success_output_path ="vlm_device_llama_3_2_vl_11b_cot_results.jsonl"
failure_output_path = "failed_response_device_cot.jsonl"

device_processed["cot_generated_response"] = None

# Clear output files first
with open(success_output_path, "w"): pass
with open(failure_output_path, "w"): pass

# Process each message
for row_idx, msg in enumerate(tqdm(device_messages[, desc="Processing Messages")):
    try:
        # Build message
        qa_content = msg.get("qa", [])
        message = {
            "role": msg.get("role", "user"),
            "content": qa_content
        }

        # Extract image URLs
        image_urls = [c.get("image") for c in qa_content if c.get("type") == "image"]

        # Run inference
        result = process_message(message, idx=row_idx)
        response_text = result["response"]

    except Exception as e:
        # Handle unexpected exception
        response_text = f"[ERROR] {e}"
        image_urls = [c.get("image") for c in msg.get("qa", []) if c.get("type") == "image"]
        failed_row = {
            "row": row_idx,
            "response": response_text,
            "error": str(e),
            "traceback": traceback.format_exc(),
            "question": msg.get("qa", []),
            "image_urls": image_urls
        }

        device_processed.at[row_idx, "cot_generated_response"] = response_text

        # Save to failed file
        with open(failure_output_path, "a") as f:
            f.write(json.dumps(failed_row) + "\n")
        continue

    # Update DataFrame
    device_processed.at[row_idx, "cot_generated_response"] = response_text

    # Print first sample
    if row_idx == 0:
        print("\n#Prompt:##\n")
        print(message["content"])
        print("\n##Sample Response:##\n")
        print(response_text)

    # Build row
    row_data = {
        "row": row_idx,
        "response": response_text,
        "image_urls": image_urls
    }
    device_logs_cot_results.append(row_data)

    # Split output based on success/failure
    if response_text.startswith("[ERROR]"):
        failed_row = {
            "row": row_idx,
            "response": response_text,
            "error": response_text,
            "traceback": result.get("traceback", ""),
            "question": msg.get("qa", []),
            "image_urls": image_urls
        }
        with open(failure_output_path, "a") as f:
            f.write(json.dumps(failed_row) + "\n")
    else:
        with open(success_output_path, "a") as f:
            f.write(json.dumps(row_data) + "\n")

In [ ]:
device_logs_cot_results[:2]

[{'row': 0,
  'response': 'The INPUT chain in the nat table is typically used for handling packets destined for the local host itself. This includes packets that are not destined for any specific port but are instead handled by the kernel\'s routing code or other system components. The PREROUTING chain, on the other hand, is specifically designed for translating the destination address of incoming packets, which is commonly referred to as "port forwarding." Therefore, the INPUT chain in the nat table serves a different purpose than the PREROUTING chain.',
  'image_urls': ['https://i.sstatic.net/NUh2k.png']},
 {'row': 1,
  'response': 'The issue arises because the `@timestamp` field in Elasticsearch is being parsed incorrectly due to the format mismatch between your `timestamp` field and the expected format for parsing. The `@timestamp` field is being set to a default value (`2015-11-18T18:22:00.069Z`) which is not matching the actual `timestamp` value in the document.\n\nHere’s how you can resolve this:\n\n### Step-by-Step Solution:\n\n1. **Ensure the `timestamp` field is correctly formatted**: \n   - Your `timestamp` field should be in a format that can be parsed by the `date` filter in Logstash. The format `YYYY-MM-dd HH:mm:ss,SSS` seems correct but ensure it matches exactly what is stored in your database.\n\n2. **Use the `@timestamp` field correctly**:\n   - The `@timestamp` field is automatically generated by Logstash and should be used for the timestamp of when the event was received by Logstash, not the timestamp of the event itself.\n\n3. **Correctly parse the `timestamp` field**:\n   - You need to ensure that the `timestamp` field is correctly parsed using the `date` filter. The format `YYYY-MM-dd HH:mm:ss,SSS` looks correct, but make sure there are no extra characters or spaces that might cause issues.\n\n4. **Update the Logstash configuration**:\n   ```ruby\n   input {\n       jdbc {\n           jdbc_driver_library => "C:/logstash/lib/mysql-connector-java-5.1.37-bin.jar"\n           jdbc_driver_class => "com.mysql.jdbc.Driver"\n           jdbc_connection_string => "jdbc:mysql://127.0.0.1:3306/transport"\n           jdbc_user => "root"\n           jdbc_password => ""\n           schedule => "* * * * *"\n           statement => "select id, timestamp, type, service, data, success, trans_id from audit where timestamp >= :sql_last_start"    \n       }\n   }\n\n   filter {\n       date {\n           match => [ "timestamp", "YYYY-MM-dd HH:mm:ss,SSS" ]\n           add_tag => [ "tsmatch" ]\n       }\n   }\n\n   output {\n       elasticsearch {\n           hosts => ["127.0.0.1:9200"]\n           index => "audit-%{+YYYY.MM.dd}"\n           document_id => "%{id}"\n       }\n       stdout {\n           codec => rubydebug\n       }\n   }\n   ```\n\n5. **Check the Elasticsearch mapping**:\n   - Ensure that the `timestamp` field is properly indexed and mapped in Elasticsearch. You can check this by running:\n     ```bash\n     GET audit-2015.11.18/_mapping\n     ```\n   - If the mapping is incorrect, you may need to reindex the data or update the mapping.\n\n### Additional Tips:\n- **Verify the exact format**: Double-check the exact format of the `timestamp` field in your database. Sometimes, there might be additional characters or timezone information that needs to be accounted for.\n- **Use the `@timestamp` field wisely**: The `@timestamp` field should be used for the timestamp of the event receipt by Logstash, not the event\'s occurrence time. If you need the event\'s occurrence time, use the `timestamp` field directly in your queries.\n\nBy ensuring the `timestamp` field is correctly formatted and parsed, you should be able to resolve the discrepancy between the `timestamp` and `@timestamp` fields.',
  'image_urls': ['https://i.sstatic.net/3nAZ9.png',
   'https://i.sstatic.net/bsoVL.png',
   'https://i.sstatic.net/wM2pW.png']},
 {'row': 2,
  'response': 'The issue arises because the `FORWARD` chain in iptables processes packets that are routed between different network interfaces. When you drop a packet in the `FORWARD` chain, it affects packets that are being routed through the system, not just those coming directly from or going directly to the specified interface.\n\nHere’s a step-by-step breakdown:\n\n1. **Understanding the `FORWARD` Chain**: The `FORWARD` chain is used to control packets that are being routed between different network interfaces. This includes packets that are moving from one interface to another within the same bridge.\n\n2. **Effect of Dropping Packets in `FORWARD`**: When you drop a packet in the `FORWARD` chain, it stops the packet from being routed between the interfaces. However, this does not affect packets that are directly coming in or going out of the specified interface (`eth1` in your case).\n\n3. **Impact of Dropping Specific Interfaces**: If you drop packets specifically on an interface like `eth1`, it will stop packets destined for `eth1` from entering the system. However, it won’t affect packets that are being routed between other interfaces.\n\nTo achieve your goal of allowing `eth2` to `eth5` to communicate freely while limiting traffic from `eth1`, you should use the `PREROUTING` chain instead of the `FORWARD` chain. Here’s how you can do it:\n\n```bash\n# Allow traffic between eth2-eth5\niptables -A FORWARD -i eth2 -o eth3 -j ACCEPT\niptables -A FORWARD -i eth2 -o eth4 -j ACCEPT\niptables -A FORWARD -i eth2 -o eth5 -j ACCEPT\niptables -A FORWARD -i eth3 -o eth4 -j ACCEPT\niptables -A FORWARD -i eth3 -o eth5 -j ACCEPT\niptables -A FORWARD -i eth4 -o eth5 -j ACCEPT\n\n# Drop traffic from eth1\niptables -A PREROUTING -i eth1 -j DROP\n```\n\nThis configuration ensures that packets destined for `eth1` are dropped before they even reach the `FORWARD` chain, effectively achieving your goal without affecting the routing between `eth2` to `eth5`.',
  'image_urls': ['https://i.sstatic.net/mVVao.png']},
 {'row': 3,
  'response': 'The error message indicates that the "Defer to user" setting cannot be used when specifying additional scopes (in this case, the IP address range `10.10.1.0/24`). To achieve your goal of allowing connections only from the local LAN (`10.10.1.x`), you should:\n\n1. **Set the Remote IP Address Scope**: Ensure the "Remote IP address" scope is set to "These IP addresses" and enter `10.10.1.0/24`.\n2. **Configure the User Tab**: In the "Users" tab, select "Only allow connections from these users" and specify the local LAN IP addresses or ranges.\n\nHere’s how to proceed:\n\n1. **Open Windows Firewall**.\n2. **Navigate to the "Inbound Rules"** under the "Programs and Services" tab.\n3. **Edit the rule** that was auto-created by the application.\n4. **Go to the "Scope" tab**.\n5. **Under Remote IP address**, ensure "These IP addresses" is selected and input `10.10.1.0/24`.\n6. **Go to the "Users" tab**.\n7. **Select "Only allow connections from these users"** and specify the local LAN IP addresses or ranges.\n\nBy following these steps, you should be able to create a rule that accepts connections only from the specified local LAN addresses while denying access from other IP addresses.',
  'image_urls': ['https://i.sstatic.net/A5Xhp.png',
   'https://i.sstatic.net/WPdVg.png',
   'https://i.sstatic.net/78g6c.jpg']},
 {'row': 4,
  'response': 'No answer.',
  'image_urls': ['https://i.sstatic.net/dPRmi.png']},
 {'row': 5,
  'response': "A computer virus is like a sneaky little bug that tries to sneak into your computer and make it do things you don't want it to do. It's like if someone put a tiny robot inside your toy car that makes it drive off without you knowing!",
  'image_urls': ['https://i.sstatic.net/BQTXV.gif']},
 {'row': 6,
  'response': 'In Android, `Log.d()` (Debug) is used for logging detailed information that is useful during development but not necessarily important for production. It\'s typically used for debugging purposes.\n\n`Log.w()` (Warn) is used for logging warnings or situations that might indicate something is wrong but isn\'t necessarily a critical error. It\'s useful for indicating potential issues that developers should be aware of.\n\nIn your code snippet:\n\n- `Log.d(TAG, "DocumentSnapshot successfully written!");` is used in the `onSuccess()` method because it logs a success message which is a detail that developers would want to see during development but can be ignored in production.\n  \n- `Log.w(TAG, "Error writing document", e);` is used in the `onFailure()` method because it logs a warning about an error that occurred during the operation. This is important for developers to know what went wrong so they can fix the issue.\n\nThe choice between `Log.d()` and `Log.w()` depends on the severity and importance of the logged information. `Log.d()` is for less critical details, while `Log.w()` is for more serious issues that need attention.',
  'image_urls': ['https://i.sstatic.net/tOs9Q.png']},
 {'row': 7,
  'response': "To determine the source and destination of the outbound traffic spike, follow these steps:\n\n1. **Check the Traffic Graph**: The graph shows the bandwidth usage over time. The spike you're observing is clearly visible. However, the graph alone doesn't provide specific details about the source or destination.\n\n2. **Host List**: The host list on the right side of the interface shows the IP addresses and their corresponding bandwidth usage. If the numbers fluctuate and don't match the graph, it might indicate that the data isn't being updated in real-time or there could be issues with the graphing mechanism.\n\n3. **Detailed Traffic Analysis**:\n   - **Packet Capture**: Use a packet capture tool like Wireshark to capture packets during the period when the traffic spike occurs. This will allow you to see the source and destination IP addresses of the packets.\n   - **pfSense Logs**: Check the pfSense logs for any entries related to the traffic spike. The logs can provide detailed information about the packets, including source and destination IP addresses, protocols, and more.\n\n4. **Network Monitoring Tools**: Consider using network monitoring tools like Nagios or Zabbix to set up alerts for high outbound traffic. These tools can help you monitor and troubleshoot network issues more effectively.\n\nGiven the limitations mentioned, the best approach would be to use a packet capture tool to directly observe the source and destination of the packets causing the spike. This will give you the exact IP addresses needed to identify the source and destination of the traffic.\n\nIf you still cannot pinpoint the source and destination, consider reaching out to your network administrator or IT support team for further assistance.",
  'image_urls': ['https://i.sstatic.net/ChKpX.png']},
 {'row': 8,
  'response': "The issue likely stems from the fact that `ipinfo.io` is being used as a callback parameter within a jQuery function call (`jQuery3600090`). This means that the script source is dynamically generated rather than being a static script file. The Content Security Policy (CSP) directive `script-src 'self' *.ipinfo.io;` only allows scripts directly served from `*.ipinfo.io`, not dynamically generated content.\n\nTo resolve this, you can either:\n\n1. **Modify the CSP policy** to include dynamic sources or allow more flexibility.\n2. **Use a different method** to fetch the data if possible, such as using an AJAX request instead of a script tag.\n3. **Consider using a proxy server** that can handle the dynamic content and ensure it adheres to the CSP policy.\n\nHere's a potential solution using an AJAX request:\n\n```javascript\n$.ajax({\n    url: 'https://ipinfo.io',\n    type: 'GET',\n    success: function(data) {\n        // Process the data here\n    }\n});\n```\n\nThis approach avoids the CSP violation by not loading the script directly but instead fetching the data via an AJAX request.",
  'image_urls': ['https://i.sstatic.net/rjpZ2.jpg']},
 {'row': 9,
  'response': "To disable the colored console output in the NestJS default logger, you can set the `LOG_COLORS` environment variable to `false`. Here's how you can do it:\n\n1. Open your terminal or command prompt.\n2. Run the following command before starting your NestJS application:\n\n```bash\nexport LOG_COLORS=false\n```\n\n3. Start your NestJS application using the `nest start client-app --watch` command.\n\nThis should disable the colored console output.",
  'image_urls': ['https://i.sstatic.net/j9pMm.png',
   'https://i.sstatic.net/0dGPF.png']}]

In [ ]:
device_processed['cot-prompt'] = setup_messages(device_processed, prompt_column="cot-question")

In [ ]:
device_processed.head(2)

In [ ]:
device_processed.to_excel("../responses/device/vlm_response_device_llama_3_1_8b_instruct_cot.xlsx", index=False)