# Environment

In [1]:
! pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 2.1 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 207.6 MB/s eta 0:00:0000:010:01
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 151.6 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 kB 115.0 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2025.2 tzdata-2025.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

In [2]:
!pip install --upgrade torch transformers accelerate pillow

Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.1.0+cu118)
Collecting torch
  Downloading torch-2.7.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting transformers
  Downloading transformers-4.52.3-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.2/40.2 kB 21.6 MB/s eta 0:00:00
Collecting accelerate
  Downloading accelerate-1.7.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (9.3.0)
Collecting pillow
  Downloading pillow-11.2.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (8.9 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.9.0)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading typing_extensions-4.13.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2023.4.0)
Collecting nvidia-cuda-nvrtc-cu12==12.6.77 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.6.77 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.6.80 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.5.1.17 (from torch)
  Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.6.4.1 (from torch)
  Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.3.0.4 (from torch)
  Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.7.77 (from torch)
  Downloading nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.7.1.2 (from torch)
  Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.5.4.2 (from torch)
  Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparselt-cu12==0.6.3 (from torch)
  Downloading nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.26.2 (from torch)
  Downloading nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvtx-cu12==12.6.77 (from torch)
  Downloading nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nvjitlink-cu12==12.6.85 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufile-cu12==1.11.1.6 (from torch)
  Downloading nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.3.0 (from torch)
  Downloading triton-3.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: setuptools>=40.8.0 in /usr/local/lib/python3.10/dist-packages (from triton==3.3.0->torch) (68.2.2)
Collecting huggingface-hub<1.0,>=0.30.0 (from transformers)
  Downloading huggingface_hub-0.31.4-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.24.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 18.0 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting tqdm>=4.27 (from transformers)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 31.4 MB/s eta 0:00:00
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.6)
Collecting fsspec (from torch)
  Downloading fsspec-2025.5.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2022.12.7)
Downloading torch-2.7.0-cp310-cp310-manylinux_2_28_x86_64.whl (865.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 865.2/865.2 MB 19.6 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (393.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 39.6 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 272.5 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 236.3 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (897 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 kB 234.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl (571.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.0/571.0 MB 31.4 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (200.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 75.9 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 244.9 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 139.0 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (158.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 MB 77.9 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (216.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 MB 72.3 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl (156.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.8/156.8 MB 91.1 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (201.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.3/201.3 MB 78.8 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (19.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 260.2 MB/s eta 0:00:00a 0:00:01
Downloading nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.3/89.3 kB 55.8 MB/s eta 0:00:00
Downloading triton-3.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (156.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.4/156.4 MB 71.1 MB/s eta 0:00:0000:0100:01
Downloading transformers-4.52.3-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 249.8 MB/s eta 0:00:0000:01
Downloading accelerate-1.7.0-py3-none-any.whl (362 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 362.1/362.1 kB 138.4 MB/s eta 0:00:00
Downloading pillow-11.2.1-cp310-cp310-manylinux_2_28_x86_64.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 183.4 MB/s eta 0:00:00
Downloading huggingface_hub-0.31.4-py3-none-any.whl (489 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 489.3/489.3 kB 168.7 MB/s eta 0:00:00
Downloading fsspec-2025.5.0-py3-none-any.whl (196 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.2/196.2 kB 98.6 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.7/781.7 kB 206.3 MB/s eta 0:00:00
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 165.6 MB/s eta 0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 111.4 MB/s eta 0:00:00a 0:00:01
Downloading tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 259.9 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 44.4 MB/s eta 0:00:00
Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 25.3 MB/s eta 0:00:00
Installing collected packages: nvidia-cusparselt-cu12, typing-extensions, triton, tqdm, sympy, safetensors, regex, pillow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, fsspec, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, accelerate
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.4.0
    Uninstalling typing_extensions-4.4.0:
      Successfully uninstalled typing_extensions-4.4.0
  Attempting uninstall: triton
    Found existing installation: triton 2.1.0
    Uninstalling triton-2.1.0:
      Successfully uninstalled triton-2.1.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12
    Uninstalling sympy-1.12:
      Successfully uninstalled sympy-1.12
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.3.0
    Uninstalling Pillow-9.3.0:
      Successfully uninstalled Pillow-9.3.0
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2023.4.0
    Uninstalling fsspec-2023.4.0:
      Successfully uninstalled fsspec-2023.4.0
  Attempting uninstall: torch
    Found existing installation: torch 2.1.0+cu118
    Uninstalling torch-2.1.0+cu118:
      Successfully uninstalled torch-2.1.0+cu118
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.0+cu118 requires torch==2.1.0, but you have torch 2.7.0 which is incompatible.
torchvision 0.16.0+cu118 requires torch==2.1.0, but you have torch 2.7.0 which is incompatible.
Successfully installed accelerate-1.7.0 fsspec-2025.5.0 huggingface-hub-0.31.4 nvidia-cublas-cu12-12.6.4.1 nvidia-cuda-cupti-cu12-12.6.80 nvidia-cuda-nvrtc-cu12-12.6.77 nvidia-cuda-runtime-cu12-12.6.77 nvidia-cudnn-cu12-9.5.1.17 nvidia-cufft-cu12-11.3.0.4 nvidia-cufile-cu12-1.11.1.6 nvidia-curand-cu12-10.3.7.77 nvidia-cusolver-cu12-11.7.1.2 nvidia-cusparse-cu12-12.5.4.2 nvidia-cusparselt-cu12-0.6.3 nvidia-nccl-cu12-2.26.2 nvidia-nvjitlink-cu12-12.6.85 nvidia-nvtx-cu12-12.6.77 pillow-11.2.1 regex-2024.11.6 safetensors-0.5.3 sympy-1.14.0 tokenizers-0.21.1 torch-2.7.0 tqdm-4.67.1 transformers-4.52.3 triton-3.3.0 typing-extensions-4.13.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

In [3]:
! pip install huggingface_hub

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.10/dist-packages (0.31.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (3.9.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (2025.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (6.0.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (2022.12.7)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

In [4]:
! pip install qwen-vl-utils

Collecting qwen-vl-utils
  Downloading qwen_vl_utils-0.0.11-py3-none-any.whl.metadata (6.3 kB)
Collecting av (from qwen-vl-utils)
  Downloading av-14.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from qwen-vl-utils) (23.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from qwen-vl-utils) (11.2.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from qwen-vl-utils) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->qwen-vl-utils) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->qwen-vl-utils) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->qwen-vl-utils) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->qwen-vl-utils) (2022.12.7)
Downloading qwen_vl_utils-0.0.11-py3-none-any.whl (7.6 kB)
Downloading av-14.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.8/34.8 MB 175.1 MB/s eta 0:00:0000:0100:01
Installing collected packages: av, qwen-vl-utils
Successfully installed av-14.4.0 qwen-vl-utils-0.0.11
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip

## Import Library

In [5]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm import tqdm
import pandas as pd
import json

# Load Model

In [6]:
! nvidia-smi

Fri May 23 01:46:01 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A40                     On  |   00000000:D5:00.0 Off |                    0 |
|  0%   24C    P8             29W /  300W |       1MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [9]:
# token = "HF_TOKEN_REDACTED"

In [7]:
from huggingface_hub import login
import os

token = "HF_TOKEN_REDACTED"
os.environ['HF_TOKEN'] = token

login(token=token)
print("Logged in to Hugging Face!")

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Logged in to Hugging Face!

In [11]:
"""from huggingface_hub import login
import os

# Get HF token injected from RunPod secret
hf_token = os.getenv('HF_TOKEN')

# Login
login(token=hf_token)

print("Hugging Face login successful via RunPod Secret!")"""

'from huggingface_hub import login\nimport os\n\n# Get HF token injected from RunPod secret\nhf_token = os.getenv(\'HF_TOKEN\')\n\n# Login\nlogin(token=hf_token)\n\nprint("Hugging Face login successful via RunPod Secret!")'

## Full Model

In [8]:
from transformers import Qwen2_5_VLForConditionalGeneration, AutoProcessor
from qwen_vl_utils import process_vision_info         
import torch, os

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"

model_id = "Qwen/Qwen2.5-VL-7B-Instruct"

model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    model_id,
    device_map="auto",                  
    low_cpu_mem_usage=True,
)

# limit visual tokens to keep the vision encoder light
min_pixels = 224 * 28 * 28              
max_pixels = 768 * 28 * 28              
processor = AutoProcessor.from_pretrained(
    model_id, min_pixels=min_pixels, max_pixels=max_pixels
)

/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(

config.json:   0%|          | 0.00/1.37k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/57.6k [00:00<?, ?B/s]

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model-00005-of-00005.safetensors:   0%|          | 0.00/1.09G [00:00<?, ?B/s]

model-00001-of-00005.safetensors:   0%|          | 0.00/3.90G [00:00<?, ?B/s]

model-00002-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00004-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00003-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/216 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

tokenizer_config.json:   0%|          | 0.00/5.70k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

You have video processor config saved in `preprocessor.json` file which is deprecated. Video processor configs should be saved in their own `video_preprocessor.json` file. You can rename the file or load and save the processor back which renames it automatically. Loading from `preprocessor.json` will be removed in v5.0.

chat_template.json:   0%|          | 0.00/1.05k [00:00<?, ?B/s]

### Testing Response with Images

In [ ]:
# multiple images

In [ ]:
from PIL import Image
import requests
import torch
import gc

# Helper to resize images for VRAM optimization
def resize_images(image_list, size=(384, 384)):
    return [img.resize(size, Image.BILINEAR) for img in image_list]

# Load and resize images
image_urls = [
    "https://media.istockphoto.com/id/1018245126/photo/siberian-tiger-portrait.jpg?s=612x612&w=0&k=20&c=ONrnG-JrcVuqdtIjfr4Pj85ZswUPt8wD-VbJOnWYPw0=",
    "https://images.pexels.com/photos/458991/pexels-photo-458991.jpeg?cs=srgb&dl=pexels-pixabay-458991.jpg&fm=jpg"
]
original_images = [Image.open(requests.get(url, stream=True).raw).convert("RGB") for url in image_urls]
images = resize_images(original_images, size=(384, 384))


question = "What animal is shown in each image?"

messages = [
    {
        "role": "user",
        "content": [{"type": "image", "image": img} for img in images] + [{"type": "text", "text": question}]
    }
]
print(messages)
# Generate prompt with Qwen-style chat template
input_text = processor.apply_chat_template(messages, add_generation_prompt=True)

# Debug info
print("\n---- DEBUG INFO ----")
print("Generated Prompt:\n")
print(input_text)
print("\nNumber of <|vision_start|> tokens:", input_text.count("<|vision_start|>"))
print("Number of images passed:", len(images))
print("---------------------\n")

# Tokenize inputs
inputs = processor(
    text=[input_text],
    images=images,
    return_tensors="pt"
).to(model.device)

# Clear memory before generation
torch.cuda.empty_cache()
gc.collect()

# Generate response (deterministic)
with torch.amp.autocast(device_type="cuda" if torch.cuda.is_available() else "cpu"):
    generate_ids = model.generate(
        **inputs,
        max_new_tokens=100,
        do_sample=False
    )

# Decode only model's output, skipping the prompt
prompt_len = inputs["input_ids"].shape[1]
reply_ids = generate_ids[:, prompt_len:]
output_text = processor.tokenizer.decode(reply_ids[0], skip_special_tokens=True)

# Output
print("\n# Response:\n")
print(output_text)

[{'role': 'user', 'content': [{'type': 'image', 'image': <PIL.Image.Image image mode=RGB size=384x384 at 0x7AB65A3D55D0>}, {'type': 'image', 'image': <PIL.Image.Image image mode=RGB size=384x384 at 0x7AB65A15EF50>}, {'type': 'text', 'text': 'What animal is shown in each image?'}]}]

---- DEBUG INFO ----
Generated Prompt:

<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
<|vision_start|><|image_pad|><|vision_end|><|vision_start|><|image_pad|><|vision_end|>What animal is shown in each image?<|im_end|>
<|im_start|>assistant


Number of <|vision_start|> tokens: 2
Number of images passed: 2
---------------------


# Response:

The first image shows a tiger, and the second image shows a cow.

# Load Datasets

In [62]:
import pandas as pd
cloud=pd.read_excel("../../Dataset/cloud/split_data/cloud_test.xlsx")
device=pd.read_excel("../../Dataset/device/split_data/device_test.xlsx")

## Cloud

In [63]:
cloud.head(2)

,title,body,tags,link,score,creation_date,answer_count,comments,answers,selected_answer,images
0,Some recently changed resources are not yet pu...,\n \nEvery once in a while i ge...,"['java', 'eclipse', 'google-app-engine', 'java...",https://stackoverflow.com/questions/49711724/s...,4,2018-04-07 20:34:12Z,1,"[""@code511788465541441, if you consider Chanse...",[{'body': '\n \nIf that happens...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,FAILED TO INITIALIZE RUN FROM PACKAGE.txt,\n \nOur pipeline indicates suc...,"['azure-web-app-service', 'azure-deployment', ...",https://stackoverflow.com/questions/65255839/f...,7,2020-12-11 17:20:22Z,2,"[""thanks for the hint. i am going to verify th...","[{'body': ""\nI am almost certain that the pack...",\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

## Processed

In [64]:
cloud=cloud[['title','body','selected_answer','images']]

In [65]:
cloud.head(2)

,title,body,selected_answer,images
0,Some recently changed resources are not yet pu...,\n \nEvery once in a while i ge...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,FAILED TO INITIALIZE RUN FROM PACKAGE.txt,\n \nOur pipeline indicates suc...,\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

In [66]:
cloud['context'] = "title: " + cloud['title'].astype(str) + "\nbody: " + cloud['body'].astype(str).str.strip()

In [67]:
cloud_processed=pd.DataFrame(
    {
        'context':cloud['context'],
        'gt':cloud['selected_answer'],
        'img':cloud['images']
    }
)

In [68]:
cloud_processed.head(2)

,context,gt,img
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png']
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i..."

## Device

In [69]:
device.head(2)

,title,body,tags,link,score,creation_date,answer_count,comments,answers,selected_answer,images
0,What is the purpose of the INPUT chain in the ...,\n \nWhat is the purpose of the...,"['linux', 'iptables', 'linux', 'iptables']",https://serverfault.com/questions/993878/what-...,1,2019-12-01 00:23:16Z,1,"['OK, also please add this to your answer so o...",[{'body': '\nIf some NAT operation needs to be...,\nIf some NAT operation needs to be only done ...,['https://i.sstatic.net/NUh2k.png']
1,"Logstash JDBC input, filter event timestamp di...",\n \nI am trying to change the ...,"['elasticsearch', 'logstash', 'elastic-stack',...",https://stackoverflow.com/questions/33787795/l...,0,2015-11-18 18:38:40Z,3,"['could you suggest how I could fix?', 'Your d...",[{'body': '\nOK I finally figure how to get th...,\nOK I finally figure how to get the @timestam...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

## Processed

In [70]:
device=device[['title','body','selected_answer','images']]

In [71]:
device.head(2)

,title,body,selected_answer,images
0,What is the purpose of the INPUT chain in the ...,\n \nWhat is the purpose of the...,\nIf some NAT operation needs to be only done ...,['https://i.sstatic.net/NUh2k.png']
1,"Logstash JDBC input, filter event timestamp di...",\n \nI am trying to change the ...,\nOK I finally figure how to get the @timestam...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

In [72]:
device['context'] = "title: " + device['title'].astype(str) + "\nbody: " + device['body'].astype(str).str.strip()

In [73]:
device_processed=pd.DataFrame(
    {
        'context':device['context'],
        'gt':device['selected_answer'],
        'img':device['images']
    }
)

In [74]:
device_processed.head(2)

,context,gt,img
0,title: What is the purpose of the INPUT chain ...,\nIf some NAT operation needs to be only done ...,['https://i.sstatic.net/NUh2k.png']
1,"title: Logstash JDBC input, filter event times...",\nOK I finally figure how to get the @timestam...,"['https://i.sstatic.net/3nAZ9.png', 'https://i..."

# Prompt Setup

## Cloud

### Zero Shot

In [75]:
zero_shot = """
You are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."

Question:
{}

Answer:
"""

In [76]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['context'])

cloud_processed['zero-shot-question'] = cloud_processed.apply(generate_zero_shot_prompt, axis=1)

In [77]:
print(cloud_processed['zero-shot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."

Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Answer:

### CoT

In [78]:
cot = '''
You are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."
Question:
{}

Lets think step by step:
Answer:
'''

In [79]:
def generate_cot_prompt(row):
    return cot.format(row['context'])

cloud_processed['cot-question'] = cloud_processed.apply(generate_cot_prompt, axis=1)

In [80]:
print(cloud_processed['cot-question'][0])

You are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."
Question:
title: Some recently changed resources are not yet published
body: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I've tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?

Lets think step by step:
Answer:

## Device

### Zero Shot

In [81]:
zero_shot = '''
You are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."

Question:
{}

Answer:

'''

In [82]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['context'])

device_processed['zero-shot-question'] =device_processed.apply(generate_zero_shot_prompt, axis=1)

In [83]:
print(device_processed['zero-shot-question'][0])

You are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."

Question:
title: What is the purpose of the INPUT chain in the nat table?
body: What is the purpose of the INPUT chain in the nat table ?

The PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".

The nat:INPUT and nat:PREROUTING chains seem redundant.

What would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?

Answer:

### CoT

In [84]:
cot = '''
You are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."
Question:
{}

Lets think step by step:
Answer:
'''

In [85]:
def generate_cot_prompt(row):
    return cot.format(row['context'])

device_processed['cot-question'] = device_processed.apply(generate_cot_prompt, axis=1)

In [86]:
print(device_processed['cot-question'][0])

You are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.
If you lack sufficient information to answer, respond with "No answer."
Question:
title: What is the purpose of the INPUT chain in the nat table?
body: What is the purpose of the INPUT chain in the nat table ?

The PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".

The nat:INPUT and nat:PREROUTING chains seem redundant.

What would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?

Lets think step by step:
Answer:

## Prompt Length

In [87]:
# extract prompt length
def prompt_length(text, add_special_tokens=True):
    if pd.isnull(text) or not isinstance(text, str) or not text.strip():
        return 0
    temp_inputs = processor.tokenizer(text, return_tensors="pt", add_special_tokens=add_special_tokens)
    return temp_inputs.input_ids.shape[1]

In [88]:
# Prompt Length -> Cloud Logs
cloud_processed['zero-shot-question-length'] = cloud_processed['zero-shot-question'].apply(prompt_length)
cloud_processed['cot-question-length'] = cloud_processed['cot-question'].apply(prompt_length)

In [89]:
# Prompt Length -> Device Logs
device_processed['zero-shot-question-length'] = device_processed['zero-shot-question'].apply(prompt_length)
device_processed['cot-question-length'] = device_processed['cot-question'].apply(prompt_length)

# Message Setup ( Prompt + Images )

In [90]:
import ast

def setup_messages(dataset, prompt_column="", image_column="img"):
    messages = []

    for _, row in dataset.iterrows():
        imgs = row.get(image_column, [])
        if isinstance(imgs, str):
            try:
                imgs = ast.literal_eval(imgs)
            except Exception:
                imgs = []

        if imgs:
            # Build structured message with image placeholders and direct question
            content = [{"type": "image", "image": img} for img in imgs if img]
            content.append({
                "type": "text",
                "text": row.get(prompt_column, "")
            })

            messages.append({
                "role": "user",
                "qa": content
            })

    return messages

In [91]:
messages = setup_messages(device_processed,prompt_column="cot-question")

In [92]:
messages[1]

{'role': 'user',
 'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/3nAZ9.png'},
  {'type': 'image', 'image': 'https://i.sstatic.net/bsoVL.png'},
  {'type': 'image', 'image': 'https://i.sstatic.net/wM2pW.png'},
  {'type': 'text',
   'text': '\nYou are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\nQuestion:\ntitle: Logstash JDBC input, filter event timestamp different to @timestamp\nbody: I am trying to change the @timestamp to match my timestamp, this is the time my event occurred at not when logstash time stamped it.\n\nhere is my conf file\n\ninput {\n jdbc {\n   jdbc_driver_library => "C:/logstash/lib/mysql-connector-java-5.1.37-bin.jar"\n   jdbc_driver_class => "com.mysql.jdbc.Driver"\n   jdbc_connection_string => "jdbc:mysql://127.0.0.1:3306/transport"\n   jdbc_user => "root"\n   jdbc_password => ""\n   schedule => "* * * * *"\n   statement => "select id, timestamp, type, service, data, success, trans_id from audit where timestamp >= :sql_last_start"    \n }\n}\n\nfilter {\n    date {\n      match => [ "timestamp", "YYYY-MM-dd HH:mm:ss,SSS" ]\n      add_tag => [ "tsmatch" ]\n}\n}\n\noutput {\n  elasticsearch {\n     hosts => ["127.0.0.1:9200"]\n     index => "audit-%{+YYYY.MM.dd}"\n     document_id => "%{id}"\n }\n stdout {\n     codec => rubydebug\n }  \n}\n\n\nOut put\n\n{\n        "id" => 32,\n "timestamp" => 2015-11-18 18:21:44 +0000,\n      "type" => "Scheduled",\n   "service" => "Road",\n      "data" => "Changing the time",\n   "success" => 1,\n  "trans_id" => "ta819rsc",\n  "@version" => "1",\n"@timestamp" => "2015-11-18T18:22:00.069Z",\n      "tags" => [\n    [0] "_dateparsefailure"\n]\n}\n\n\nElasticsearch\n\n\n\nAs can be seen, the timestamps (times) are different. This will mess up my data when I bring it into Kibana as I want the histogram to filter on when the event happened not when logstash gave it the timestamp.\n\nCan some one provide me with the work around.\n\nUPDATE:\n\nI have changed the filter as suggested to \n\nmatch => [ "timestamp", "YYYY-MM-dd HH:mm:ss ZZZ" ] \n\n\nand the times are still out, and get the same _dateparsefailure in response. Would it have anything to do with the fact it\'s a Datestamp from MySQL and it can\'t be converted?\n\nG\n\nLets think step by step:\nAnswer:\n'}]}

# Generate Response

## Setup Model

In [93]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)  # move model to device once
model.eval()

Qwen2_5_VLForConditionalGeneration(
  (model): Qwen2_5_VLModel(
    (visual): Qwen2_5_VisionTransformerPretrainedModel(
      (patch_embed): Qwen2_5_VisionPatchEmbed(
        (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
      )
      (rotary_pos_emb): Qwen2_5_VisionRotaryEmbedding()
      (blocks): ModuleList(
        (0-31): 32 x Qwen2_5_VLVisionBlock(
          (norm1): Qwen2RMSNorm((1280,), eps=1e-06)
          (norm2): Qwen2RMSNorm((1280,), eps=1e-06)
          (attn): Qwen2_5_VLVisionSdpaAttention(
            (qkv): Linear(in_features=1280, out_features=3840, bias=True)
            (proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (mlp): Qwen2_5_VLMLP(
            (gate_proj): Linear(in_features=1280, out_features=3420, bias=True)
            (up_proj): Linear(in_features=1280, out_features=3420, bias=True)
            (down_proj): Linear(in_features=3420, out_features=1280, bias=True)
            (act_fn): SiLU()
          )
        )
      )
      (merger): Qwen2_5_VLPatchMerger(
        (ln_q): Qwen2RMSNorm((1280,), eps=1e-06)
        (mlp): Sequential(
          (0): Linear(in_features=5120, out_features=5120, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=5120, out_features=3584, bias=True)
        )
      )
    )
    (language_model): Qwen2_5_VLTextModel(
      (embed_tokens): Embedding(152064, 3584)
      (layers): ModuleList(
        (0-27): 28 x Qwen2_5_VLDecoderLayer(
          (self_attn): Qwen2_5_VLSdpaAttention(
            (q_proj): Linear(in_features=3584, out_features=3584, bias=True)
            (k_proj): Linear(in_features=3584, out_features=512, bias=True)
            (v_proj): Linear(in_features=3584, out_features=512, bias=True)
            (o_proj): Linear(in_features=3584, out_features=3584, bias=False)
            (rotary_emb): Qwen2_5_VLRotaryEmbedding()
          )
          (mlp): Qwen2MLP(
            (gate_proj): Linear(in_features=3584, out_features=18944, bias=False)
            (up_proj): Linear(in_features=3584, out_features=18944, bias=False)
            (down_proj): Linear(in_features=18944, out_features=3584, bias=False)
            (act_fn): SiLU()
          )
          (input_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
          (post_attention_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
        )
      )
      (norm): Qwen2RMSNorm((3584,), eps=1e-06)
      (rotary_emb): Qwen2_5_VLRotaryEmbedding()
    )
  )
  (lm_head): Linear(in_features=3584, out_features=152064, bias=False)
)

In [94]:
import math
from PIL import Image

MAX_LONG_EDGE = 224   # longest side after down-scaling
PATCH_SIZE    = 14    # ViT patch dimension
MIN_EDGE      = 28    # shortest side must be ≥ 28 px

def img_resize(img: Image.Image) -> Image.Image:
    w, h = img.size

    # Down-scale if long edge > 224
    scale = min(1.0, MAX_LONG_EDGE / max(w, h))
    w, h = int(round(w * scale)), int(round(h * scale))

    #  Guarantee minimum size
    w, h = max(w, MIN_EDGE), max(h, MIN_EDGE)

    # nearest multiple of patch size
    w  = math.ceil(w / PATCH_SIZE) * PATCH_SIZE
    h  = math.ceil(h / PATCH_SIZE) * PATCH_SIZE

    return img.resize((w, h), Image.Resampling.LANCZOS)

In [95]:
import torch
import gc
import traceback
import requests
torch.set_grad_enabled(False)

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"
torch.set_grad_enabled(False)

torch.manual_seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

# Load and prepare image(s) from message
def process_vision_info(messages):
    images = []
    for msg in messages:
        for item in msg.get("content", []):
            if item["type"] == "image":
                img = item["image"]
                if isinstance(img, str):
                    img = Image.open(requests.get(img, stream=True).raw).convert("RGB")
                images.append(img_resize(img))
    return images

# Process message with debug info
def process_message(msg: dict, idx: int):
    try:
        prompt_str = processor.apply_chat_template(
            [msg], tokenize=False, add_generation_prompt=True
        )

        imgs = process_vision_info([msg])
        if not imgs:
            raise ValueError("No images found in message.")

        inputs = processor(
            text=[prompt_str],
            images=imgs,
            return_tensors="pt"
        ).to(model.device)

        gen_ids = model.generate(
            **inputs,
            max_new_tokens=768,
            do_sample=False,
            use_cache=True
        )

        reply_ids = gen_ids[:, inputs.input_ids.shape[-1]:]
        answer = processor.batch_decode(
            reply_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )[0]

        return {"idx": idx, "response": answer}

    except Exception as e:
        return {
            "idx": idx,
            "response": f"[ERROR] {e}",
            "traceback": traceback.format_exc()
        }

    finally:
        for name in ("inputs", "gen_ids"):
            if name in locals():
                del locals()[name]
        torch.cuda.empty_cache()
        gc.collect()

## Testing Samples

In [43]:
#sample=cloud_processed[:5]
sample=cloud_processed[:10]

In [44]:
sample.head(2)

,context,gt,img,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,120,126
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,391,397

In [45]:
# Setup messages for model
sample_messages = setup_messages(sample,prompt_column="zero-shot-question")
#sample_messages = setup_messages(sample,prompt_column="cot-question")

In [46]:
sample_messages

[{'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/QQmRh.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Some recently changed resources are not yet published\nbody: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I\'ve tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?\n\nAnswer:\n'}]},
 {'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/VJ1po.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/OG2ny.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/2wzYd.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/Qz7WW.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/zyaI1.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/GxqxN.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/0fwEA.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: FAILED TO INITIALIZE RUN FROM PACKAGE.txt\nbody: Our pipeline indicates success after deployment.\nWhen looking in "Kudo console" in folder wwwroot i observe the following behavior:\n\nDeploy Task is nothing special:\n- task: AzureRmWebAppDeployment@4\n  displayName: \'Deploy Frontend\'\n  inputs:\n    ConnectionType: \'AzureRM\'\n    azureSubscription: # subscription #\n    appType: \'webApp\'\n    WebAppName: # appname #\n    packageForLinux: # package #\n\nThe artifact that gets build is approx. 17 MB of size and exists. I downloaded it. It is a ZIP file that can be extracted.\n\nWhen looking at data\\sitepackages i observe the following behaviour:\nAll deployment runs have a size of 1 KB.\nThis explains why the ZIP cannot be extracted.\nBut WHY is it 1 KB?\n\nUPDATE (1):\nWhen we use the feature "Zip Push Deploy" from "Kudo Console" we can drag&drop the ZIP file that we have downloaded from our artefacts before.\nThe zip gets extracted and the app is working!\nThis means the ZIP in the artefacts is not corrupt.\n\nUPDATE (2):\nThe complete run indicates success and produces a artefact with 17 MB. After Deployment the size of the ZIP file is 1 KB. There has to be an issue with the deploy task?\n\nUPDATE (3):\nScreenhot from Deploy Step that also shows success:\n\nUPDATE (4):\nMSFT support suggested to use V3 of the deploy Job: AzureRmWebAppDeployment@3.\nDifferent output:\n\nSame result.\nUPDATE (5):\ni have recreated the app service in the meanwhile (deleted and created).\nSame result.\n\nAnswer:\n'}]},
 {'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/FRtNR.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Deploy to Heroku button with env variables\nbody: I\'d like to add a "Deploy to Heroku" button to my application hosted on GitHub, but the only problem is it requires env variables to run, and will require the user to enter them before it will work. Is there a way in the app.json schema to prompt the user prior to install to set these up? Or is my best bet setting them to a standard string such as "replace_me" and telling the users to enter their data from there in my readme file.\n\nI saw that you could generate a "secret" in their documentation but I\'m not sure if that\'s what I\'m looking for.\n\nAnswer:\n'}]},
 {'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/MDMix.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/MqJxt.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Publish azure functions and use appsettings.json\nbody: I have an Azure Functions project, which I am writing in C# using Visual Studio 2017 15.3 preview 7. The functions project contains two seperate functions, both of which are timer triggered. I have a number of appsettings which I have specified in an appsettings.json file, which is set to Copy to the output directory on build.\n\nWhen I publish the Azure Functions project, the two functions are displayed in the Azure portal, however they fail as they do not have access to the app settings. Now I know I can specifiy the settings in the application settings blade, but I want to use appsettings.json which should be possible according to this github issue: https://github.com/Azure/azure-functions-cli/issues/33\n\nThis SO answer contains some information about getting it to work Azure Functions - using appsettings.json. Now the issue lies in "Azure will try looking for after appsettings.json file into your root folder of the Function that you working on." My function project as it stands contains the following file structure:\n\n-appsettings.json\n-Function_function1.cs\n-Function_function2.cs\n-host.json\n\n\nWhen the project is built and deployed, I end up with a folder for each of the functions in the wwwroot, each of these contains a function.json file. The appsettings.json file goes into the wwwroot/bin folder and the functions are not able to access it.\n\nI thought that maybe if I changed functions project to have a folder structure it would deploy the appsettings.json, I changed it to the following\n\n-host.json\n-Function_function1\\\n--Function_function1.cs\n--appsettings.json\n-Function_function2\\\n--Function_function2.cs\n--appsettings.json\n\n\nThis didn\'t have the result I expected and at this point I am not quite sure what I need to do to get appsettings copied into the function folders under the wwwroot rather than the bin folder, any guidance will be appreciated.\n\nAnswer:\n'}]},
 {'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/Cap0y.jpg'},
   {'type': 'image', 'image': 'https://i.sstatic.net/SsPuj.jpg'},
   {'type': 'image', 'image': 'https://i.sstatic.net/oAsMn.jpg'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: VSTS Build: Replacing token with build number\nbody: I\'m trying to update a web.config app setting called \'AppVersion\' with the build number when building my application in VSTS.\n\nHere are my build steps:\n\n\n\nThe \'Replace tokens\' step converts any variables you set for your build and replaces the tokens you\'ve set in your config files. This part works but what it won\'t do is get an environment variable like the build number and do a replace. It will just replace whatever text has been specified. Here\'s my build variables:\n\n\n\nSo after the build step is completed, my app setting is...\n\n<add key="AppVersion" value="$(BuildNumber)" />\n\nwhen it should be something like...\n\n<add key="AppVersion" value="20160520.1" />\n\nCan anyone point me in the right direction?\nMany thanks.\n\nAnswer:\n'}]},
 {'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/jMSBc.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Visual Studio Team Services Build Queue Not Appearing in List\nbody: I\'m setting up a build definition in Visual Studio Team Services using a Build Agent installed on my local machine for testing.\n\nI\'m following these instructions for creating a build agent, setting up a build definition, and queuing a build. I\'ve created the agent on my local computer and it appears in the agent pool in VSTS. The agent is enabled and ready to go. I\'ve also created a build definition that invokes my build script. Everything up to this point appears to work fine.\n\nAt this point I\'m ready to queue a build and run it. The dialog for this looks like:\n\n\n\nThe dropdown labeled "Queue" only shows the Hosted agent pool. There should be a second pool called Default but it is not appearing. I can get it to "appear" by right clicking and inspecting the HTML and then using dev tools to change the value for the Hosted option. Hosted\'s ID is 2, I changed it to 1 since I assumed this to be the ID for Default. Once I do this I can click "OK" and the build runs as expected -- everything is checked out on my local machine by the build agent. Presumably my assumption about the ID value is correct.\n\nSo...everything it working correctly once I muck around with the plumbing a bit. But this is definitely not the way things should be working. Why is the Default queue not showing up in the dropdown? Do I need to flip a switch somewhere to make it work? Does my account not have enough access?\n\nSome other details:\n\n\nMy account is a "Pool Administrator"\nThe build agent is not installed as a Windows service. I start it manually from a command prompt. I\'ve not been able to install it as a service.\nThe machine that has the build agent installed on it is running Windows 10 x64 Pro. It was upgraded from Windows 8 x64 Pro.\nI cannot use a hosted agent as I\'m building a Unity project and Unity is not supported by for hosted agents.\nI know I can use Unity Cloud Build but I do not want to.\n\n\nUPDATE\n\nI\'ve removed my previous Build Agent and installed a new one, as a service, on a Windows Azure VM running Windows 10 Enterprise x64. With this change the "Hosted" and "Default" queues are appearing as expected.\n\nAnswer:\n'}]},
 {'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/e6fFL.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Confused about Amazon DynamoDB, what is per hour for units of write capacity?\nbody: I\'ve been working on a new project and have put some data on Amazon DynamoDB. The project was kind of on hold last month and I was surprised to see such high costs for a DB that was essentially almost untouched for the whole month.\nHere is the bill details:\n\nWhat does per hour for units of write capacity beyond the free tier mean?\nThanks.\n\nAnswer:\n'}]},
 {'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/goCGM.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: How to get the cost for each Azure Function within the Azure Function App?\nbody: I\'m monitoring my Azure Function App costs from the Azure Cost Management tool, but from there, it isn\'t possible to get the cost for each different Azure Function within the app.\nI\'ve noticed an unexpected increase in costs and I\'d like to know the which functions are costing more in order to make cost optimization.\nIs it possible to get Azure Functions cost by function name?\n\nAnswer:\n'}]},
 {'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/dPN75.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Start NodeJS runtime in AWS lambda with a specific option or environment variable\nbody: Getting NodeJS deprecation error when execute an AWS Lambda (using node 12.x):\n\n[DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated\n\n\ncan not find which module/piece of code is producing it. Nothing seems to reference _headers or _headerNames. \n\nIn Node should be possible to set a parameter or environment variable as explain here to --trace-deprecation and/or --trace-warnings and/or --throw-deprecation. When setting one or multiple of these values in AWS Console Environment variables for the lambda, no extra information is displayed.\n\n\n\nWhat is the way to set this runtime parameter for an AWS Lambda? Is there a way to catch the stack trace to know where is the deprecated error happening?\n\nAnswer:\n'}]},
 {'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/fQ9Uz.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/zMboW.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: How to do file transforms / variable substitution with Visual Studio Online and .NET Desktop App\nbody: Visual Studio Team Services Online (www.visualstudio.com) Release Definitions has a setting within IIS Web App Deploy to perform XML variable substitution.  Based on the in-line help:\n\n\n  Variables defined in the Build or Release Definition will be matched against the \'key\' or \'name\' entries in the appSettings, applicationSettings, and connectionStrings sections of any config file and parameters.xml. Variable Substitution is run after config transforms. \n\n\nIs there any such simple Task that can be applied when deploying .NET Desktop-oriented releases (for desktop apps or Windows services)?  Specifically, I want to replace the value part of key-value elements of appSettings.config files (or, post-build they are now *.exe.config).  \n\nI\'ve seen some token replacement marketplace add-ons, but those don\'t do the trick.  They\'ll replace the value part of appSetting, but not based on key.  I could probably shoe-horn it, but its inelegant & fragile.\n\nAnswer:\n'}]}]

### Get response for Sample  -> Test

In [47]:
# Output setup
sample_results = []
output_path = "sample_results_full.jsonl"

# Ensure column exists for generated responses
sample["generated_response"] = None

# Clear the output file first
with open(output_path, "w"):
    pass

# Process each message
for row_idx, msg in enumerate(tqdm(sample_messages, desc="Processing Messages")):

    # Build the message
    message = {
        "role": msg["role"],
        "content": msg["qa"]
    }

    # Get image URLs
    image_urls = [c["image"] for c in msg["qa"] if c["type"] == "image"]

    # Run inference
    result = process_message(message, idx=row_idx)
    response_text = result["response"]

    # Update DataFrame
    sample.at[row_idx, "generated_response"] = response_text

    if row_idx==0:
      print("\n#Prompt:##\n")
      print(message["content"])
      print("\n##Sample Response:##\n")
      print(response_text)

    # Save row result
    row_data = {
        "row": row_idx,
        "response": response_text,
        "image_urls": image_urls
    }
    sample_results.append(row_data)

    # Save incrementally to file
    with open(output_path, "a") as f:
        f.write(json.dumps(row_data) + "\n")

/tmp/ipykernel_645/2944900821.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample["generated_response"] = None
Processing Messages:   0%|          | 0/10 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|█         | 1/10 [00:19<02:55, 19.55s/it]

#Prompt:##

[{'type': 'image', 'image': 'https://i.sstatic.net/QQmRh.png'}, {'type': 'text', 'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Some recently changed resources are not yet published\nbody: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I\'ve tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?\n\nAnswer:\n'}]

##Sample Response:##

The error message indicates that some recently changed resources have not been published, which is preventing the GAE (Google App Engine) server from starting with the updated code. This can happen if the changes made to your resources are not being recognized or applied correctly by the development environment.

To resolve this issue, you might want to try the following steps:

1. **Check for Pending Changes**: Ensure that all your recent changes are committed to version control. Sometimes, uncommitted changes can cause issues when trying to publish.

2. **Force Publish**: In Eclipse, you can force a publish of your resources by right-clicking on the project in the Package Explorer, selecting "Team" -> "Synchronize with Team", and then choosing "Force Publish".

3. **Clean and Rebuild**: Sometimes, a simple clean and rebuild can resolve the issue. Right-click on the project, select "Project" -> "Clean", and then "Project" -> "Build Project".

4. **Update Dependencies**: Make sure all your dependencies are up-to-date and there are no conflicts.

5. **Restart Eclipse**: Sometimes, a restart of Eclipse can help clear any lingering issues.

6. **Check Server Logs**: Look at the logs of your GAE server to see if there are any specific errors related to the resources not being published.

7. **Check Project Settings**: Ensure that your project settings are correct and that the paths to your resources are accurate.

If none of these steps work, it might be worth checking the documentation for Google App Engine or seeking support from the community forums dedicated to GAE and Eclipse.

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  20%|██        | 2/10 [00:50<03:28, 26.00s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  30%|███       | 3/10 [00:58<02:05, 17.86s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  40%|████      | 4/10 [01:31<02:24, 24.03s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  50%|█████     | 5/10 [01:58<02:04, 24.87s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  60%|██████    | 6/10 [02:22<01:38, 24.55s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  70%|███████   | 7/10 [02:24<00:51, 17.24s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  80%|████████  | 8/10 [02:29<00:27, 13.53s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  90%|█████████ | 9/10 [02:41<00:12, 12.93s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages: 100%|██████████| 10/10 [02:51<00:00, 17.19s/it]

In [49]:
sample_results[:3]

[{'row': 0,
  'response': 'The error message indicates that some recently changed resources have not been published, which is preventing the GAE (Google App Engine) server from starting with the updated code. This can happen if the changes made to your resources are not being recognized or applied correctly by the development environment.\n\nTo resolve this issue, you might want to try the following steps:\n\n1. **Check for Pending Changes**: Ensure that all your recent changes are committed to version control. Sometimes, uncommitted changes can cause issues when trying to publish.\n\n2. **Force Publish**: In Eclipse, you can force a publish of your resources by right-clicking on the project in the Package Explorer, selecting "Team" -> "Synchronize with Team", and then choosing "Force Publish".\n\n3. **Clean and Rebuild**: Sometimes, a simple clean and rebuild can resolve the issue. Right-click on the project, select "Project" -> "Clean", and then "Project" -> "Build Project".\n\n4. **Update Dependencies**: Make sure all your dependencies are up-to-date and there are no conflicts.\n\n5. **Restart Eclipse**: Sometimes, a restart of Eclipse can help clear any lingering issues.\n\n6. **Check Server Logs**: Look at the logs of your GAE server to see if there are any specific errors related to the resources not being published.\n\n7. **Check Project Settings**: Ensure that your project settings are correct and that the paths to your resources are accurate.\n\nIf none of these steps work, it might be worth checking the documentation for Google App Engine or seeking support from the community forums dedicated to GAE and Eclipse.',
  'image_urls': ['https://i.sstatic.net/QQmRh.png']},
 {'row': 1,
  'response': "The issue seems to be related to how the ZIP file is being handled during the deployment process. Here's what could be happening:\n\n1. **Deployment Task Issue**: The deployment task might be overwriting or modifying the ZIP file contents during the deployment process, which results in the ZIP file being reduced to 1 KB. This could be due to the task not preserving the original ZIP structure or contents.\n\n2. **Deployment Task Configuration**: The configuration for the `AzureRmWebAppDeployment@4` task might not be correctly set up to handle the ZIP file properly. Ensure that the task is configured to preserve the ZIP file structure and contents.\n\n3. **Artifact Handling**: The artifact in the `Published artifacts` might be corrupted or incorrectly packaged. Verify the artifact by downloading it again and checking its contents.\n\n4. **Kudu Console Usage**: Using the `Zip Push Deploy` feature directly from Kudu console allows you to manually extract the ZIP file and deploy it successfully. This suggests that there might be an issue with the deployment task itself rather than the ZIP file.\n\n5. **Alternative Deployment Method**: Consider using the `AzureRmWebAppDeployment@3` task instead of `AzureRmWebAppDeployment@4`. If the issue persists, it may indicate a problem with the specific version of the task.\n\n6. **Recreate the App Service**: Since recreating the app service did not resolve the issue, it might be worth investigating if there are any underlying issues with the app service itself.\n\nTo resolve this, you should:\n\n- Review the deployment task logs for any errors or warnings.\n- Check if there are any custom scripts or configurations that might be affecting the ZIP file.\n- Verify the artifact contents and ensure they match the expected ZIP file.\n- Test with different versions of the deployment task to see if the issue persists.\n\nIf none of these steps resolve the issue, consider reaching out to Microsoft Support for further assistance.",
  'image_urls': ['https://i.sstatic.net/VJ1po.png',
   'https://i.sstatic.net/OG2ny.png',
   'https://i.sstatic.net/2wzYd.png',
   'https://i.sstatic.net/Qz7WW.png',
   'https://i.sstatic.net/zyaI1.png',
   'https://i.sstatic.net/GxqxN.png',
   'https://i.sstatic.net/0fwEA.png']},
 {'row': 2,
  'response': 'In the app.json schema, there isn\'t a direct way to prompt the user to set environment variables prior to installation. However, you can use placeholders or default values in your app.json file to indicate where these variables should be set. For example, you might use `"AWS_ACCESS_KEY_ID": "replace_me"` and instruct users to replace `replace_me` with their actual AWS access key ID in the README file.\n\nUsing a "secret" as mentioned in the Heroku documentation can also help secure sensitive information by generating a unique value that is not stored in the app.json file. This approach ensures that the secrets are not exposed during deployment.',
  'image_urls': ['https://i.sstatic.net/FRtNR.png']}]

## Cloud

In [50]:
cloud_processed.head(2)

,context,gt,img,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: Some recently changed resources are not...,"If that happens for whatever reasons, you need...",['https://i.sstatic.net/QQmRh.png'],\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,120,126
1,title: FAILED TO INITIALIZE RUN FROM PACKAGE.t...,\nI am almost certain that the package path is...,"['https://i.sstatic.net/VJ1po.png', 'https://i...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,391,397

### Zero-shot

In [51]:
# Setup messages for mode
cloud_messages = setup_messages(cloud_processed,prompt_column="zero-shot-question")

In [52]:
cloud_messages[0:1]

[{'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/QQmRh.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Some recently changed resources are not yet published\nbody: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I\'ve tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?\n\nAnswer:\n'}]}]

#### Get response

In [56]:
cloud_processed.loc[1131:]

,context,gt,img,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length,generated_response,cot-prompt
1130,title: Is event sourcing an enhanced pattern o...,\nThe two are compatible patterns that address...,"['https://i.sstatic.net/0hRZH.png', 'https://i...",\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,201,207,None,"{'role': 'user', 'qa': [{'type': 'image', 'ima..."
1131,title: Are Kafka Streams Appropriate for Trigg...,\n\nHow can I signal a Stream that all of the ...,['https://i.sstatic.net/CKA7t.png'],\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,569,575,None,"{'role': 'user', 'qa': [{'type': 'image', 'ima..."
1132,title: on_failure_callback triggered multiple ...,\nYou can use trigger_rule + PythonOperator to...,['https://i.sstatic.net/49U8S.png'],\nYou are an expert cloud assistant. Provide a...,\nYou are an expert cloud assistant. Provide a...,1049,1055,None,"{'role': 'user', 'qa': [{'type': 'image', 'ima..."

In [57]:
# Output setup
cloud_logs_zero_shot_results = []
output_path = "vlm_cloud_qwen2_5_vl_7b_zero_shot_results.jsonl"

# Ensure column exists for generated responses
cloud_processed["generated_response"] = None

# Clear the output file first
with open(output_path, "w"):
    pass

start_index=1131
# Process each message
for row_idx, msg in enumerate(tqdm(cloud_messages[1131:], desc="Processing Messages")):

    # Build the message
    message = {
        "role": msg["role"],
        "content": msg["qa"]
    }

    # Get image URLs
    image_urls = [c["image"] for c in msg["qa"] if c["type"] == "image"]

    # Run inference
    result = process_message(message, idx=row_idx)
    response_text = result["response"]

    # Update DataFrame
    device_processed.at[row_idx, "generated_response"] = response_text

    #Sample Response
    if row_idx==0:
      print("\n#Prompt:##\n")
      print(message["content"])
      print("\n##Sample Response:##\n")
      print(response_text)

    # Save row result
    row_data = {
        "row": row_idx+start_index,
        "response": response_text,
        "image_urls": image_urls
    }
    cloud_logs_zero_shot_results.append(row_data)

    # Save incrementally to file
    with open(output_path, "a") as f:
        f.write(json.dumps(row_data) + "\n")

Processing Messages:   0%|          | 0/491 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 1/491 [00:42<5:44:12, 42.15s/it]

#Prompt:##

[{'type': 'image', 'image': 'https://i.sstatic.net/CKA7t.png'}, {'type': 'text', 'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\nQuestion:\ntitle: Are Kafka Streams Appropriate for Triggering Batch Processing of Records?\nbody: Context\nI have three services in place, each of which generate a certain JSON payload (and take different times to do so) that is needed to be able to process a message which is the result of combining all three JSON payloads into a single payload. This final payload in turn is to be sent to another Kafka Topic so that it can then be consumed by another service.\nBelow you can find a diagram that better explains the problem at hand. The information aggregator service receives a request to aggregate information, it sends that request to a Kafka topic so that Service 1, Service 2 and Service 3 consume that request and send their data (JSON Payload) to 3 different Kafka Topics.\n\nThe Information Aggregator has to consume the messages from the three services (Which are sent to their respective Kafka Topics at very different times e.g. Service 1 takes half an hour to respond while service 2 and 3 take under 10 minutes) so that it can generate a final payload (Represented as Aggregated Information) to send to another Kafka Topic.\nResearch\nAfter having researched a lot about Kafka and Kafka Streams, I came across this article that provides some great insights on how this should be elaborated.\nIn this article, the author consumes messages from a single topic while in my specific use case I must consume from three different topics, wait for each message from each topic with a certain ID to arrive so that I can then signal my process that it can proceed to consume the 3 messages with the same ID in different topics to generate the final message and send that final message to another Kafka topic (Which then another service will consume that message).\nThought Out Solution\nMy thoughts are that I need to have a Kafka Stream checking all three topics and when it sees that has all the 3 messages available, send a message to a kafka topic called e.g. TopicEvents from which the Information Aggregator will be consuming and by consuming the message will know exactly which messages to get from which topic, partition and offset and then can proceed to send the final payload to another Kafka Topic.\nQuestions\n\nAm I making a very wrong use of Kafka Streams and Batch\nProcessing?\n\nHow can I signal a Stream that all of the messages have arrived so that it can generate the message to place in the TopicEvent so as to signal the Information Aggregator that all the messages in the different topics have arrived and are ready to be consumed?\n\n\nSorry for this long post, any pointers that you can provide will be very helpful and thank you in advance\n\nLets think step by step:\nAnswer:\n'}]

##Sample Response:##

Based on the context provided, your approach using Kafka Streams to aggregate messages from multiple topics and trigger batch processing seems appropriate. However, there are a few considerations:

1. **Kafka Streams for Multiple Topics**: Kafka Streams can indeed handle multiple input topics. You can create a `KStream` for each topic and then merge them into a single stream if necessary. This aligns well with your requirement to consume messages from three different topics.

2. **Signal for Completion**: To signal a Stream that all messages have arrived, you can use a combination of Kafka Streams' `KTable` and `KStream`. Here’s a high-level approach:

   - Create a `KTable` that tracks the status of messages received from each topic.
   - Use a `KStream` to monitor the `KTable` and trigger a batch processing action once all expected messages have been received.

Here's a simplified example of how you might implement this:

```java
import org.apache.kafka.streams.KafkaStreams;
import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.kstream.KTable;
import org.apache.kafka.streams.kstream.KStream;

public class MessageAggregator {
    public static void main(String[] args) {
        // Initialize Kafka Streams
        StreamsBuilder builder = new StreamsBuilder();

        // Input topics
        KStream<String, String> stream1 = builder.stream("topic1");
        KStream<String, String> stream2 = builder.stream("topic2");
        KStream<String, String> stream3 = builder.stream("topic3");

        // Combine streams (if needed)
        KStream<String, String> combinedStream = stream1.join(stream2, stream3, (k, v1, v2, v3) -> v1 + v2 + v3);

        // Create a table to track message status
        KTable<String, Boolean> messageStatus = combinedStream.toStream().toTable("message-status", TableWindows.of(TimeWindows.of(5 * 60 * 1000))); // 5 minutes window

        // Signal when all messages are received
        KStream<String, Boolean> allMessagesReceived = messageStatus.count().filter((key, value) -> value == 3); // Assuming 3 messages per topic

        // Trigger batch processing
        allMessagesReceived.toStream().to("TopicEvents", Produced.with(Serdes.String(), Serdes.Boolean()));

        // Start the Kafka Streams application
        KafkaStreams streams = new KafkaStreams(builder.build(), props);
        streams.start();
    }
}
```

### Explanation:
- **KTable**: A `KTable` is used to track the status of messages received from each topic. It maintains a count of messages received for each key.
- **Count Operation**: The `count()` operation on the `KTable` gives you the total number of messages received for each key.
- **Filtering**: By filtering the `KTable` to only include keys where the count is equal to 3 (assuming one message per topic), you can determine when all messages have been received.
- **Signal**: The filtered `KStream` is then written to a new topic (`TopicEvents`) to signal the Information Aggregator.

This approach ensures that the Information Aggregator is notified only after all required messages have been received, thus avoiding unnecessary processing and ensuring data integrity.

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 2/491 [01:29<6:10:50, 45.50s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 3/491 [01:51<4:41:29, 34.61s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 4/491 [02:45<5:41:30, 42.07s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 5/491 [02:54<4:06:27, 30.43s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 6/491 [03:21<3:55:56, 29.19s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|▏         | 7/491 [03:57<4:11:46, 31.21s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 8/491 [04:14<3:36:37, 26.91s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 9/491 [05:02<4:29:32, 33.55s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 10/491 [05:12<3:28:53, 26.06s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 11/491 [06:05<4:35:53, 34.49s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 12/491 [06:28<4:07:05, 30.95s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 13/491 [07:07<4:26:29, 33.45s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 14/491 [07:18<3:30:20, 26.46s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 15/491 [07:35<3:07:57, 23.69s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 18/491 [07:40<1:09:59,  8.88s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 19/491 [07:56<1:27:46, 11.16s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 20/491 [08:40<2:43:29, 20.83s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 21/491 [09:04<2:52:07, 21.97s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 22/491 [09:28<2:56:04, 22.53s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 23/491 [09:34<2:17:29, 17.63s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 24/491 [10:02<2:39:42, 20.52s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 25/491 [10:53<3:51:45, 29.84s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 26/491 [11:17<3:38:08, 28.15s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 27/491 [11:36<3:14:48, 25.19s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 28/491 [12:01<3:13:34, 25.09s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 29/491 [12:43<3:54:00, 30.39s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▋         | 31/491 [13:07<2:31:53, 19.81s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 32/491 [13:44<3:12:46, 25.20s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 33/491 [13:46<2:17:23, 18.00s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 34/491 [14:07<2:25:36, 19.12s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 35/491 [14:29<2:31:30, 19.94s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 36/491 [14:47<2:26:02, 19.26s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 37/491 [15:15<2:46:32, 22.01s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 38/491 [15:24<2:17:15, 18.18s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 39/491 [15:48<2:29:18, 19.82s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 40/491 [16:15<2:45:01, 21.95s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 41/491 [16:18<2:00:59, 16.13s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▊         | 42/491 [16:42<2:18:19, 18.48s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 43/491 [16:55<2:06:47, 16.98s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 44/491 [17:07<1:55:35, 15.52s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 45/491 [17:32<2:15:03, 18.17s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 46/491 [17:49<2:14:00, 18.07s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|▉         | 47/491 [18:28<2:59:57, 24.32s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|▉         | 48/491 [18:37<2:25:10, 19.66s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|▉         | 49/491 [18:56<2:22:55, 19.40s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|█         | 50/491 [18:59<1:47:24, 14.61s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|█         | 51/491 [20:12<3:55:59, 32.18s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  11%|█         | 52/491 [20:31<3:25:51, 28.14s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  11%|█         | 53/491 [20:52<3:08:19, 25.80s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  11%|█         | 54/491 [21:04<2:39:40, 21.92s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  11%|█         | 55/491 [21:31<2:50:26, 23.45s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  11%|█▏        | 56/491 [21:53<2:45:48, 22.87s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  12%|█▏        | 57/491 [22:18<2:51:10, 23.66s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  12%|█▏        | 58/491 [22:30<2:24:59, 20.09s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  12%|█▏        | 59/491 [22:48<2:19:55, 19.43s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  12%|█▏        | 60/491 [22:59<2:00:16, 16.74s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  12%|█▏        | 61/491 [23:41<2:56:18, 24.60s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  13%|█▎        | 62/491 [23:42<2:05:11, 17.51s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  13%|█▎        | 63/491 [24:08<2:22:35, 19.99s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  13%|█▎        | 64/491 [24:28<2:21:28, 19.88s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  13%|█▎        | 65/491 [24:29<1:41:35, 14.31s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  13%|█▎        | 66/491 [24:44<1:43:12, 14.57s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▎        | 67/491 [25:11<2:09:09, 18.28s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▍        | 68/491 [25:20<1:48:38, 15.41s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▍        | 69/491 [25:39<1:55:16, 16.39s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▍        | 70/491 [26:19<2:46:00, 23.66s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  14%|█▍        | 71/491 [26:37<2:33:16, 21.90s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  15%|█▍        | 72/491 [26:56<2:27:17, 21.09s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  15%|█▍        | 73/491 [27:19<2:30:11, 21.56s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  15%|█▌        | 74/491 [27:36<2:21:12, 20.32s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  15%|█▌        | 75/491 [27:53<2:13:50, 19.30s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  15%|█▌        | 76/491 [28:13<2:14:09, 19.40s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  16%|█▌        | 77/491 [28:45<2:40:30, 23.26s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  16%|█▌        | 78/491 [29:13<2:48:42, 24.51s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  16%|█▌        | 79/491 [29:25<2:22:54, 20.81s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  16%|█▋        | 80/491 [29:34<1:57:56, 17.22s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  16%|█▋        | 81/491 [30:02<2:19:47, 20.46s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  17%|█▋        | 82/491 [30:43<3:02:48, 26.82s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  17%|█▋        | 83/491 [31:04<2:50:50, 25.12s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  17%|█▋        | 84/491 [31:23<2:37:50, 23.27s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  17%|█▋        | 85/491 [31:51<2:45:24, 24.44s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  18%|█▊        | 86/491 [31:54<2:03:00, 18.22s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  18%|█▊        | 87/491 [32:02<1:42:16, 15.19s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  18%|█▊        | 88/491 [32:23<1:53:06, 16.84s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  18%|█▊        | 89/491 [32:31<1:34:03, 14.04s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  18%|█▊        | 90/491 [32:48<1:39:50, 14.94s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  19%|█▊        | 91/491 [32:57<1:28:25, 13.26s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  19%|█▊        | 92/491 [33:17<1:42:08, 15.36s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  19%|█▉        | 93/491 [33:37<1:50:39, 16.68s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  19%|█▉        | 94/491 [33:52<1:46:32, 16.10s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  19%|█▉        | 95/491 [34:10<1:50:21, 16.72s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  20%|█▉        | 96/491 [34:26<1:49:05, 16.57s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  20%|█▉        | 97/491 [34:50<2:03:57, 18.88s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  20%|█▉        | 98/491 [34:56<1:37:19, 14.86s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  20%|██        | 99/491 [35:33<2:21:27, 21.65s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  20%|██        | 100/491 [35:34<1:40:37, 15.44s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

In [ ]:
cloud_processed['zero-shot-prompt'] = setup_messages(cloud_processed, prompt_column="zero-shot-question")

In [ ]:
cloud_processed.to_excel("../responses/cloud/vlm_response_cloud_qwen_7b_zero_shot.xlsx", index=False)

### CoT

In [43]:
# Setup messages for mode
cloud_messages = setup_messages(cloud_processed,prompt_column="cot-question")

In [ ]:
cloud_messages[0:1]

[{'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/QQmRh.png'},
   {'type': 'text',
    'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\nQuestion:\ntitle: Some recently changed resources are not yet published\nbody: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I\'ve tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?\n\nLets think step by step:\nAnswer:\n'}]}]

#### Get response

In [ ]:
# Output setup
cloud_logs_cot_results = []
output_path = "vlm_cloud_qwen2_5_vl_7b_cot_results.jsonl"

# Ensure column exists for generated responses
cloud_processed["generated_response"] = None

# Clear the output file first
with open(output_path, "w"):
    pass

# Process each message
for row_idx, msg in enumerate(tqdm(cloud_messages, desc="Processing Messages")):

    # Build the message
    message = {
        "role": msg["role"],
        "content": msg["qa"]
    }

    # Get image URLs
    image_urls = [c["image"] for c in msg["qa"] if c["type"] == "image"]

    # Run inference
    result = process_message(message, idx=row_idx)
    response_text = result["response"]

    # Update DataFrame
    device_processed.at[row_idx, "generated_response"] = response_text

    #Sample Response
    if row_idx==0:
      print("\n#Prompt:##\n")
      print(message["content"])
      print("\n##Sample Response:##\n")
      print(response_text)

    # Save row result
    row_data = {
        "row": row_idx,
        "response": response_text,
        "image_urls": image_urls
    }
    cloud_logs_cot_results.append(row_data)

    # Save incrementally to file
    with open(output_path, "a") as f:
        f.write(json.dumps(row_data) + "\n")

Processing Messages:   0%|          | 0/1622 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 1/1622 [00:19<8:41:03, 19.29s/it]

#Prompt:##

[{'type': 'image', 'image': 'https://i.sstatic.net/QQmRh.png'}, {'type': 'text', 'text': '\nYou are an expert cloud assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\nQuestion:\ntitle: Some recently changed resources are not yet published\nbody: Every once in a while i get this error message. If I click Yes then my GAE server starts but with old code. I\'ve tried cleaning, restarting eclipse, shutting down computer, closing and opening the project again, deleting the launch config and adding it again but nothing works. Does anyone know what causes this issue?\n\nLets think step by step:\nAnswer:\n'}]

##Sample Response:##

The error message indicates that some recently changed resources have not been published, which is causing the issue. When you click "Yes," your GAE server starts but with old code because the changes have not been deployed.

To resolve this issue, you can try the following steps:

1. **Publish the Changes**: Ensure that all recent changes are published to the server. You can do this by right-clicking on the project in Eclipse, selecting "Team" -> "Publish to Server," and then choosing the appropriate server (e.g., Google App Engine).

2. **Clean and Build Project**: Sometimes, cleaning and building the project can help refresh the environment. Right-click on the project, select "Project" -> "Clean," and then "Project" -> "Build All."

3. **Restart Eclipse**: Sometimes, simply restarting Eclipse can resolve issues related to resource tracking.

4. **Check for Conflicts**: Ensure there are no conflicts or uncommitted changes in your version control system (e.g., Git). Commit any pending changes before publishing.

5. **Update Dependencies**: Make sure all dependencies are up-to-date and correctly configured.

6. **Check Server Logs**: Review the logs of your GAE server to see if there are any specific errors or warnings that might indicate why the new code is not being recognized.

7. **Verify Configuration**: Double-check your deployment configuration to ensure it's set up correctly for the latest changes.

If none of these steps work, you might want to check the specific version of the code that is being deployed and compare it with the version you expect to be running.

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 2/1622 [00:55<13:14:19, 29.42s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 3/1622 [01:30<14:19:00, 31.83s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 4/1622 [01:57<13:21:43, 29.73s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 5/1622 [02:31<14:04:07, 31.32s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 6/1622 [02:52<12:33:52, 27.99s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 7/1622 [02:54<8:45:57, 19.54s/it] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 8/1622 [03:01<6:55:19, 15.44s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 9/1622 [03:12<6:15:42, 13.98s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 10/1622 [03:31<7:02:58, 15.74s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 11/1622 [03:36<5:32:18, 12.38s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 12/1622 [03:41<4:31:52, 10.13s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 13/1622 [04:09<6:57:15, 15.56s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 14/1622 [04:14<5:27:25, 12.22s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 15/1622 [04:26<5:30:47, 12.35s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 16/1622 [04:45<6:22:32, 14.29s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 17/1622 [05:06<7:11:41, 16.14s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 18/1622 [05:18<6:42:57, 15.07s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 19/1622 [05:35<7:00:00, 15.72s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 20/1622 [05:44<6:04:25, 13.65s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|▏         | 21/1622 [05:55<5:39:24, 12.72s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|▏         | 22/1622 [06:16<6:49:49, 15.37s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|▏         | 23/1622 [06:34<7:09:22, 16.11s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|▏         | 24/1622 [06:35<5:08:02, 11.57s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 25/1622 [06:48<5:14:37, 11.82s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 26/1622 [07:08<6:20:11, 14.29s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 27/1622 [07:34<7:58:44, 18.01s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 28/1622 [07:45<6:59:35, 15.79s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 29/1622 [08:03<7:16:26, 16.44s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 30/1622 [08:15<6:42:53, 15.18s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 31/1622 [09:08<11:44:29, 26.57s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 32/1622 [09:17<9:23:50, 21.28s/it] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 33/1622 [09:18<6:42:30, 15.20s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 34/1622 [09:21<5:02:36, 11.43s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 35/1622 [09:37<5:38:34, 12.80s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 36/1622 [09:54<6:13:31, 14.13s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 37/1622 [10:11<6:33:46, 14.91s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 38/1622 [10:32<7:23:17, 16.79s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 39/1622 [10:48<7:12:50, 16.41s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 40/1622 [10:54<5:50:39, 13.30s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 41/1622 [11:01<5:03:59, 11.54s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 42/1622 [11:20<5:59:18, 13.64s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 43/1622 [11:47<7:46:20, 17.72s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 44/1622 [12:05<7:47:23, 17.77s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 45/1622 [12:19<7:19:57, 16.74s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 46/1622 [12:48<8:59:00, 20.52s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 47/1622 [13:29<11:34:06, 26.44s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 48/1622 [13:51<10:58:35, 25.11s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 49/1622 [14:01<9:00:59, 20.64s/it] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 50/1622 [14:09<7:20:35, 16.82s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 51/1622 [14:13<5:41:16, 13.03s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 52/1622 [14:28<5:55:49, 13.60s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 53/1622 [14:40<5:47:17, 13.28s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 54/1622 [14:53<5:39:07, 12.98s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 55/1622 [15:16<6:58:50, 16.04s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 56/1622 [15:35<7:24:25, 17.03s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 57/1622 [15:40<5:47:29, 13.32s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 58/1622 [16:01<6:48:23, 15.67s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 59/1622 [16:18<6:57:22, 16.02s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 60/1622 [16:19<4:59:56, 11.52s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 61/1622 [16:44<6:47:34, 15.67s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 62/1622 [17:13<8:32:30, 19.71s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 63/1622 [17:42<9:42:22, 22.41s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 64/1622 [18:12<10:39:45, 24.64s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 65/1622 [18:23<8:53:35, 20.56s/it] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 66/1622 [18:36<7:51:22, 18.18s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 67/1622 [18:57<8:17:26, 19.19s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 68/1622 [19:21<8:53:46, 20.61s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 69/1622 [19:33<7:46:14, 18.01s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 70/1622 [19:39<6:11:26, 14.36s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 71/1622 [19:53<6:12:12, 14.40s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 72/1622 [20:04<5:40:34, 13.18s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 73/1622 [20:36<8:11:21, 19.03s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 74/1622 [21:07<9:42:27, 22.58s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 75/1622 [21:41<11:05:32, 25.81s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 76/1622 [22:02<10:28:13, 24.38s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 77/1622 [22:05<7:45:57, 18.10s/it] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 78/1622 [22:53<11:40:14, 27.21s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 79/1622 [23:00<8:56:56, 20.88s/it] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 80/1622 [23:02<6:31:17, 15.23s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 81/1622 [23:25<7:31:49, 17.59s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 82/1622 [23:40<7:12:44, 16.86s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 83/1622 [24:17<9:51:16, 23.05s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 84/1622 [24:39<9:39:28, 22.61s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 85/1622 [24:57<9:04:41, 21.26s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 86/1622 [25:14<8:33:46, 20.07s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 87/1622 [25:38<9:02:41, 21.21s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 88/1622 [25:46<7:20:16, 17.22s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 89/1622 [26:45<12:36:34, 29.61s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 90/1622 [27:05<11:21:26, 26.69s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 91/1622 [27:41<12:32:21, 29.49s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 92/1622 [27:54<10:30:13, 24.71s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 93/1622 [27:55<7:31:07, 17.70s/it] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 94/1622 [27:58<5:35:45, 13.18s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 95/1622 [28:02<4:24:25, 10.39s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 96/1622 [28:13<4:26:55, 10.50s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 97/1622 [28:38<6:17:49, 14.87s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

In [46]:
cloud_processed['cot-prompt'] = setup_messages(cloud_processed, prompt_column="cot-question")

In [47]:
cloud_processed.to_excel("../responses/cloud/vlm_response_cloud_qwen_7b.xlsx", index=False)

## Device

In [96]:
device_processed.head(2)

,context,gt,img,zero-shot-question,cot-question,zero-shot-question-length,cot-question-length
0,title: What is the purpose of the INPUT chain ...,\nIf some NAT operation needs to be only done ...,['https://i.sstatic.net/NUh2k.png'],\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,150,156
1,"title: Logstash JDBC input, filter event times...",\nOK I finally figure how to get the @timestam...,"['https://i.sstatic.net/3nAZ9.png', 'https://i...",\nYou are an expert device assistant. Provide ...,\nYou are an expert device assistant. Provide ...,586,592

### Zero-Shot

In [97]:
# Setup messages for mode
device_messages = setup_messages(device_processed,prompt_column="zero-shot-question")

In [98]:
device_messages[:2]

[{'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/NUh2k.png'},
   {'type': 'text',
    'text': '\nYou are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: What is the purpose of the INPUT chain in the nat table?\nbody: What is the purpose of the INPUT chain in the nat table ?\n\nThe PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".\n\nThe nat:INPUT and nat:PREROUTING chains seem redundant.\n\nWhat would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?\n\nAnswer:\n\n'}]},
 {'role': 'user',
  'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/3nAZ9.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/bsoVL.png'},
   {'type': 'image', 'image': 'https://i.sstatic.net/wM2pW.png'},
   {'type': 'text',
    'text': '\nYou are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Logstash JDBC input, filter event timestamp different to @timestamp\nbody: I am trying to change the @timestamp to match my timestamp, this is the time my event occurred at not when logstash time stamped it.\n\nhere is my conf file\n\ninput {\n jdbc {\n   jdbc_driver_library => "C:/logstash/lib/mysql-connector-java-5.1.37-bin.jar"\n   jdbc_driver_class => "com.mysql.jdbc.Driver"\n   jdbc_connection_string => "jdbc:mysql://127.0.0.1:3306/transport"\n   jdbc_user => "root"\n   jdbc_password => ""\n   schedule => "* * * * *"\n   statement => "select id, timestamp, type, service, data, success, trans_id from audit where timestamp >= :sql_last_start"    \n }\n}\n\nfilter {\n    date {\n      match => [ "timestamp", "YYYY-MM-dd HH:mm:ss,SSS" ]\n      add_tag => [ "tsmatch" ]\n}\n}\n\noutput {\n  elasticsearch {\n     hosts => ["127.0.0.1:9200"]\n     index => "audit-%{+YYYY.MM.dd}"\n     document_id => "%{id}"\n }\n stdout {\n     codec => rubydebug\n }  \n}\n\n\nOut put\n\n{\n        "id" => 32,\n "timestamp" => 2015-11-18 18:21:44 +0000,\n      "type" => "Scheduled",\n   "service" => "Road",\n      "data" => "Changing the time",\n   "success" => 1,\n  "trans_id" => "ta819rsc",\n  "@version" => "1",\n"@timestamp" => "2015-11-18T18:22:00.069Z",\n      "tags" => [\n    [0] "_dateparsefailure"\n]\n}\n\n\nElasticsearch\n\n\n\nAs can be seen, the timestamps (times) are different. This will mess up my data when I bring it into Kibana as I want the histogram to filter on when the event happened not when logstash gave it the timestamp.\n\nCan some one provide me with the work around.\n\nUPDATE:\n\nI have changed the filter as suggested to \n\nmatch => [ "timestamp", "YYYY-MM-dd HH:mm:ss ZZZ" ] \n\n\nand the times are still out, and get the same _dateparsefailure in response. Would it have anything to do with the fact it\'s a Datestamp from MySQL and it can\'t be converted?\n\nG\n\nAnswer:\n\n'}]}]

#### Get response

In [99]:
# Output setup
device_logs_zero_shot_results = []
output_path = "vlm_device_qwen2_5_vl_7b_zero_shot_results.jsonl"

# Ensure column exists for generated responses
device_processed["generated_response"] = None

# Clear the output file first
with open(output_path, "w"):
    pass

# Process each message
for row_idx, msg in enumerate(tqdm(device_messages, desc="Processing Messages")):

    # Build the message
    message = {
        "role": msg["role"],
        "content": msg["qa"]
    }

    # Get image URLs
    image_urls = [c["image"] for c in msg["qa"] if c["type"] == "image"]

    # Run inference
    result = process_message(message, idx=row_idx)
    response_text = result["response"]

    # Update DataFrame
    device_processed.at[row_idx, "generated_response"] = response_text

    #Sample Response
    if row_idx==0:
      print("\n#Prompt:##\n")
      print(message["content"])
      print("\n##Sample Response:##\n")
      print(response_text)


    # Save row result
    row_data = {
        "row": row_idx,
        "response": response_text,
        "image_urls": image_urls
    }
    device_logs_zero_shot_results.append(row_data)

    # Save incrementally to file
    with open(output_path, "a") as f:
        f.write(json.dumps(row_data) + "\n")

Processing Messages:   0%|          | 0/993 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 1/993 [00:05<1:32:55,  5.62s/it]

#Prompt:##

[{'type': 'image', 'image': 'https://i.sstatic.net/NUh2k.png'}, {'type': 'text', 'text': '\nYou are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: What is the purpose of the INPUT chain in the nat table?\nbody: What is the purpose of the INPUT chain in the nat table ?\n\nThe PREROUTING chain in the nat table is already doing the translation of the destination addresses (DNAT) of incoming packets ...as in what is commonly called "port forwarding".\n\nThe nat:INPUT and nat:PREROUTING chains seem redundant.\n\nWhat would be the typical use of the nat:INPUT chain that cannot be accomplished in the nat:PREROUTING chain ?\n\nAnswer:\n\n'}]

##Sample Response:##

The nat:INPUT chain in the nat table is typically used for network address translation (NAT) on packets that have already been routed to the host but have not yet reached the destination application or service. This means it can handle packets that are destined for local services or applications on the host itself, which the PREROUTING chain might not be able to process if they haven't been routed to the host yet.

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 2/993 [00:43<6:42:17, 24.36s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 3/993 [01:01<5:58:25, 21.72s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   0%|          | 4/993 [01:18<5:27:46, 19.89s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 5/993 [01:22<3:49:17, 13.92s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 6/993 [01:37<3:58:15, 14.48s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 7/993 [01:38<2:46:40, 10.14s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 8/993 [01:44<2:20:23,  8.55s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 9/993 [01:54<2:28:58,  9.08s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 10/993 [02:22<4:07:10, 15.09s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 11/993 [02:43<4:35:45, 16.85s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|          | 12/993 [02:49<3:38:49, 13.38s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|▏         | 13/993 [02:56<3:07:25, 11.48s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   1%|▏         | 14/993 [03:24<4:31:55, 16.67s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 15/993 [03:25<3:14:52, 11.96s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 16/993 [03:34<2:58:15, 10.95s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 17/993 [03:46<3:02:37, 11.23s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 18/993 [03:47<2:12:32,  8.16s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 19/993 [04:01<2:41:43,  9.96s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 20/993 [04:09<2:31:12,  9.32s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 21/993 [04:33<3:42:27, 13.73s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 22/993 [05:02<4:55:25, 18.26s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 23/993 [05:17<4:40:02, 17.32s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   2%|▏         | 24/993 [05:30<4:21:53, 16.22s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 25/993 [05:52<4:45:25, 17.69s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 26/993 [06:03<4:13:47, 15.75s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 27/993 [06:09<3:25:46, 12.78s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 28/993 [06:26<3:49:24, 14.26s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 29/993 [06:39<3:40:24, 13.72s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 30/993 [07:03<4:29:58, 16.82s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 31/993 [07:08<3:33:16, 13.30s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 32/993 [07:20<3:27:56, 12.98s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 33/993 [07:47<4:35:32, 17.22s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   3%|▎         | 34/993 [08:04<4:33:56, 17.14s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 35/993 [08:05<3:16:14, 12.29s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 36/993 [08:25<3:50:50, 14.47s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▎         | 37/993 [08:38<3:44:03, 14.06s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 38/993 [08:43<2:59:06, 11.25s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 39/993 [08:57<3:14:56, 12.26s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 40/993 [09:05<2:52:36, 10.87s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 41/993 [09:09<2:22:14,  8.96s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 42/993 [09:11<1:44:55,  6.62s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 43/993 [09:27<2:30:29,  9.50s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   4%|▍         | 44/993 [09:49<3:32:17, 13.42s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 45/993 [09:51<2:35:54,  9.87s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 46/993 [10:09<3:15:06, 12.36s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 47/993 [10:24<3:28:50, 13.25s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 48/993 [10:32<3:00:35, 11.47s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▍         | 49/993 [10:46<3:12:45, 12.25s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 50/993 [11:08<4:01:08, 15.34s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 51/993 [11:14<3:15:56, 12.48s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 52/993 [11:55<5:30:08, 21.05s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 53/993 [11:57<4:01:29, 15.41s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   5%|▌         | 54/993 [12:23<4:48:36, 18.44s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 55/993 [12:24<3:27:11, 13.25s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 56/993 [12:25<2:29:52,  9.60s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 57/993 [12:31<2:11:56,  8.46s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 58/993 [12:46<2:43:29, 10.49s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 59/993 [12:53<2:27:16,  9.46s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 60/993 [13:14<3:20:10, 12.87s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 61/993 [13:28<3:24:14, 13.15s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▌         | 62/993 [13:54<4:24:15, 17.03s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▋         | 63/993 [14:07<4:05:00, 15.81s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   6%|▋         | 64/993 [14:10<3:04:18, 11.90s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 65/993 [14:35<4:03:46, 15.76s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 66/993 [14:45<3:39:01, 14.18s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 67/993 [14:51<3:03:09, 11.87s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 68/993 [15:19<4:16:35, 16.64s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 69/993 [16:10<6:54:06, 26.89s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 70/993 [16:15<5:14:12, 20.43s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 71/993 [16:45<5:54:53, 23.09s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 72/993 [16:51<4:35:18, 17.94s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 73/993 [16:58<3:47:03, 14.81s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   7%|▋         | 74/993 [17:00<2:47:01, 10.91s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 75/993 [17:05<2:19:06,  9.09s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 77/993 [17:10<1:24:51,  5.56s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 78/993 [17:16<1:29:05,  5.84s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 79/993 [17:18<1:08:12,  4.48s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 80/993 [17:31<1:48:39,  7.14s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 81/993 [17:37<1:42:56,  6.77s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 82/993 [18:21<4:30:45, 17.83s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 83/993 [18:26<3:32:31, 14.01s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   8%|▊         | 84/993 [18:41<3:38:49, 14.44s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▊         | 85/993 [18:49<3:07:15, 12.37s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▊         | 86/993 [19:04<3:19:24, 13.19s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 87/993 [19:11<2:51:16, 11.34s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 88/993 [19:16<2:21:38,  9.39s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 89/993 [19:36<3:09:52, 12.60s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 90/993 [19:37<2:17:45,  9.15s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 91/993 [19:44<2:06:16,  8.40s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 92/993 [19:54<2:14:08,  8.93s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 93/993 [20:21<3:36:37, 14.44s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:   9%|▉         | 94/993 [20:36<3:38:19, 14.57s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|▉         | 95/993 [20:37<2:37:02, 10.49s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|▉         | 96/993 [20:52<2:58:25, 11.94s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|▉         | 97/993 [21:07<3:09:00, 12.66s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Processing Messages:  10%|▉         | 98/993 [21:27<3:45:14, 15.10s/it]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

In [100]:
device_messages[1]

{'role': 'user',
 'qa': [{'type': 'image', 'image': 'https://i.sstatic.net/3nAZ9.png'},
  {'type': 'image', 'image': 'https://i.sstatic.net/bsoVL.png'},
  {'type': 'image', 'image': 'https://i.sstatic.net/wM2pW.png'},
  {'type': 'text',
   'text': '\nYou are an expert device assistant. Provide a concise answer to the following question, and use the images as reference.\nIf you lack sufficient information to answer, respond with "No answer."\n\nQuestion:\ntitle: Logstash JDBC input, filter event timestamp different to @timestamp\nbody: I am trying to change the @timestamp to match my timestamp, this is the time my event occurred at not when logstash time stamped it.\n\nhere is my conf file\n\ninput {\n jdbc {\n   jdbc_driver_library => "C:/logstash/lib/mysql-connector-java-5.1.37-bin.jar"\n   jdbc_driver_class => "com.mysql.jdbc.Driver"\n   jdbc_connection_string => "jdbc:mysql://127.0.0.1:3306/transport"\n   jdbc_user => "root"\n   jdbc_password => ""\n   schedule => "* * * * *"\n   statement => "select id, timestamp, type, service, data, success, trans_id from audit where timestamp >= :sql_last_start"    \n }\n}\n\nfilter {\n    date {\n      match => [ "timestamp", "YYYY-MM-dd HH:mm:ss,SSS" ]\n      add_tag => [ "tsmatch" ]\n}\n}\n\noutput {\n  elasticsearch {\n     hosts => ["127.0.0.1:9200"]\n     index => "audit-%{+YYYY.MM.dd}"\n     document_id => "%{id}"\n }\n stdout {\n     codec => rubydebug\n }  \n}\n\n\nOut put\n\n{\n        "id" => 32,\n "timestamp" => 2015-11-18 18:21:44 +0000,\n      "type" => "Scheduled",\n   "service" => "Road",\n      "data" => "Changing the time",\n   "success" => 1,\n  "trans_id" => "ta819rsc",\n  "@version" => "1",\n"@timestamp" => "2015-11-18T18:22:00.069Z",\n      "tags" => [\n    [0] "_dateparsefailure"\n]\n}\n\n\nElasticsearch\n\n\n\nAs can be seen, the timestamps (times) are different. This will mess up my data when I bring it into Kibana as I want the histogram to filter on when the event happened not when logstash gave it the timestamp.\n\nCan some one provide me with the work around.\n\nUPDATE:\n\nI have changed the filter as suggested to \n\nmatch => [ "timestamp", "YYYY-MM-dd HH:mm:ss ZZZ" ] \n\n\nand the times are still out, and get the same _dateparsefailure in response. Would it have anything to do with the fact it\'s a Datestamp from MySQL and it can\'t be converted?\n\nG\n\nAnswer:\n\n'}]}

In [ ]:
device_logs_zero_shot_results

In [101]:
device_processed['zero-shot-prompt'] = setup_messages(device_processed, prompt_column="zero-shot-question")

In [102]:
device_processed.to_excel("../responses/device/vlm_response_device_qwen_7b_zero_shot.xlsx", index=False)

### CoT

In [ ]:
# Setup messages for mode
device_messages = setup_messages(device_processed,prompt_column="cot-question")

In [ ]:
device_messages[:2]

#### Get response

In [ ]:
# Output setup
device_logs_cot_results = []
output_path = "vlm_device_qwen2_5_vl_7b_cot_results.jsonl"

# Ensure column exists for generated responses
device_processed["generated_response"] = None

# Clear the output file first
with open(output_path, "w"):
    pass

# Process each message
for row_idx, msg in enumerate(tqdm(device_messages, desc="Processing Messages")):

    # Build the message
    message = {
        "role": msg["role"],
        "content": msg["qa"]
    }

    # Get image URLs
    image_urls = [c["image"] for c in msg["qa"] if c["type"] == "image"]

    # Run inference
    result = process_message(message, idx=row_idx)
    response_text = result["response"]

    # Update DataFrame
    device_processed.at[row_idx, "generated_response"] = response_text

    #Sample Response
    if row_idx==0:
      print("\n#Prompt:##\n")
      print(message["content"])
      print("\n##Sample Response:##\n")
      print(response_text)


    # Save row result
    row_data = {
        "row": row_idx,
        "response": response_text,
        "image_urls": image_urls
    }
    device_logs_cot_results.append(row_data)

    # Save incrementally to file
    with open(output_path, "a") as f:
        f.write(json.dumps(row_data) + "\n")

In [ ]:
device_logs_cot_results

In [ ]:
device_processed['cot-prompt'] = setup_messages(cloud_processed, prompt_column="cot-question")

In [ ]:
device_processed.to_excel("../responses/device/vlm_response_device_qwen_7b.xlsx", index=False)